### ISSUE TITLE
NPE when Autocrafting

### ISSUE THREAD

**Issue by Knito58** [raoulvdberge/refinedstorage#1207] opened 2017-05-09 14:46 UTC
#### Issue description:

Trying to craft the first 64k storage disk.

#### What happens:

Minecraft closes down and a crash-xxx-server.txt is written. The re-load of the world generates another crash. World can not be loaded atm.

#### What you expected to happen:

To craft very slowly a very big storage device :)

#### Steps to reproduce:

The ingredients are mostly stored in storage drawers and AA Crates. All that stacks may change the counting as a primordial crops farm tower pumps items in at all times. Those items go into the drawer system as well as into crates which are connected as external storage. Well, the stack size of the ingredients found by RS when starting the crafting will change. Iron, gold and restone are stored in **compacting drawers**. Idk what happens internally when such a drawer gets filled: Is only the blocks count updated and the stack size of the normal items is decremented and then too small for the copyStackWithSize() function??? Maybe there is only one stack of "normal" items in the drawer which goes down to zero when a new block is done? When checking to start up the crafting, everything is there. After the click on "start" the MC windows closes.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 1.11.2-13.20.0.2294
- Refined Storage: 1.4.4

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

https://www.dropbox.com/s/1ugqxxwapr0o0xi/crash-2017-05-09_14.46.35-server.txt?dl=0
https://www.dropbox.com/s/ga88vfdgwaw8mb5/crash-2017-05-09_14.52.34-server.txt?dl=0
https://www.dropbox.com/s/e090dv9abqget39/crash-2017-05-09_14.57.39-server.txt?dl=0

**Comment by raoulvdberge** [comment] 2017-05-11 23:21
Duplicate of #1070

**Closed by raoulvdberge** 2017-05-11 23:21 UTC
