### ISSUE TITLE
Mekanism gas tank autocrafting doesn't work

### ISSUE THREAD

**Issue by Vapervop** [raoulvdberge/refinedstorage#2334] opened 2019-10-24 13:17 UTC
#### Issue description: If I try to autocraft the ultimate gas tank (Mekanism)  the crafting preview says that i'm missing an Elite gas tank, but i already have that pattern. 
Note: I put the patterns in a Crafter.

#### What you expected to happen:
Autocrafting the Ultimate Gas Tank

#### Steps to reproduce:
1.Make all the patterns in order to autocraft the "Ultimate Gas Tank" from Mekanism
2.Open the crafting grid and select it to autocraft it
...

#### Version:
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Refined Storage: 1.6.15

Does this issue occur on a server? 
no

**Comment by Darkere** [comment] 2019-10-24 13:20
Duplicate of #2064

Manually replace the tank in the pattern with a tank that you have crafted.

**Comment by Vapervop** [comment] 2019-10-24 13:34
> Duplicate of #2064
> 
> Manually replace the tank in the pattern with a tank that you have crafted.

Still doesn't work :/

**Comment by Darkere** [comment] 2019-10-24 13:48
Other things that may add more NBT tags and cause this to not work include: 
- having the tank in your inventory
- placing the tank down
- inserting fluid into the tank

The only way to check these things is by looking at the actual NBT data.

**Comment by Vapervop** [comment] 2019-10-24 19:18
Might you explain me what "looking a the NBT data" means? I don't know what is it. If I need to craft the tank my self without putting it in my inventory, how could I replace that in the pattern? Thank you for your help.

**Comment by Darkere** [comment] 2019-10-24 19:48
>Might you explain me what "looking a the NBT data" means? I don't know what is it.
There are some mods that allow looking at the NBT data (the data that is on the item) depending on your pack there are different ways of doing so. 

>If I need to craft the tank my self without putting it in my inventory, how could I replace that in the pattern?
The item only goes into your inventory once you put it into one of the 36 slots of the inventory. If you keep the tank inside RS system or only on your cursor the changes are not applied. 

Oh and make sure you do not have Oredict enabled on the pattern.

**Closed** 2019-10-24 20:06 UTC
