### ISSUE TITLE
Suggestion: Controller to require some qty of RF before turning on

### ISSUE THREAD

**Issue by OrdinatorStouff** [raoulvdberge/refinedstorage#1359] opened 2017-07-11 19:12 UTC
#### Issue description:
I would like to suggest a setting/config to define some qty or percentage of RF needed in the controller before it fully "turns on"

Once on, it can stay on until it drops all the way down to 0 RF but can not come *back* on until above the engagement quantity

Even a small percentage (like it set to 5% by default) could drastically reduce the amount of "flickering" that low-power systems might encounter. This could also add some depth to themed/expert packs that want to make the controller more difficult to use (i.e. you must have a strong source of RF to keep the block powered like in conjunction with I:I:capacity and I:controllerBase and related energy settings in the config)

#### If a (crash)log is relevant for this issue, link it here:
Relevant/related to "flickering" issues like https://github.com/raoulvdberge/refinedstorage/issues/566

**Comment by raoulvdberge** [comment] 2017-07-11 19:14
Duplicate of #1358

**Closed by raoulvdberge** 2017-07-11 19:14 UTC
