### ISSUE TITLE
[1.12.x] Crafting Pattern for Chest is invisible when looking at it while shifted in your inventory

### ISSUE THREAD

**Issue by Odysseius** [raoulvdberge/refinedstorage#1494] opened 2017-10-18 21:48 UTC
The Chest texture does not show up for a crafting pattern containing the Chest recipe.
I think a picture may be more descriptive than my broken English: https://i.imgur.com/ROr2TXV.png

- Minecraft: 1.12.2
- Forge: 14.23.0.2512
- Refined Storage: 1.5.20

Occurs on server, though I would not expect a difference in occurence between SP and MP.

And I swear to god, I tried my best to find an already exising ticket for this.

**Comment by way2muchnoise** [comment] 2017-10-19 06:37
Duplicate of #609

**Closed** 2017-10-19 06:48 UTC
Labels: bug, duplicate
