### ISSUE TITLE
Cannot autocraft Bronze Dust

### ISSUE THREAD

**Issue by varukasalt** [raoulvdberge/refinedstorage#152] opened 2016-07-02 19:20 UTC
When requesting bronze dust, system reports that it has crafted, but nothing is produced and no materials (tin and copper) are consumed. Manual crafting from the system works as expected.

**Comment by raoulvdberge** [comment] 2016-07-02 19:34
Which  version are you on?

**Comment by raoulvdberge** [comment] 2016-07-02 19:43
I think it's fixed in the latest version, I cannot reproduce it myself.

**Comment by varukasalt** [comment] 2016-07-03 00:17
0.8.3 and it is still doing the same thing. Must be on my end but I can't figure out what it is.

**Comment by raoulvdberge** [comment] 2016-07-18 22:25
This is fixed, Varuka

**Closed by raoulvdberge** 2016-07-18 22:25 UTC
Labels: bug
