### ISSUE TITLE
[1.9] Massive lag when a refined storage system is active

### ISSUE THREAD

**Issue by kwpugh** [raoulvdberge/refinedstorage#40] opened 2016-05-13 16:27 UTC
We are seeing a weird problem on our server.   Running Forge 1901 and the refinedstorage-0.5.6.jar.  When a refined storage system is activated by receiving power, the TPS drops down to 7-8 and the time between ticks jumps to 70-80 ms.   As soon as the system is deactivated, the TPS and tick times return to normal levels.   Multiple players have tried this and the same results occur.  There is no crash, so no crash report.

Here is a list of the mods being used: http://pastebin.com/raw/jYNK3VjF

Please let me know if there is any additional information you need to troubleshoot the issue.

Regards,

Kevin

**Comment by Harith163** [comment] 2016-05-13 16:43
I tried replicating this issue on a small server with a small network. Could you give more information on the size of the network? are you importing/ exporting multiple items at the same time? is it the server itself?

**Comment by raoulvdberge** [comment] 2016-05-13 17:55
Yes, I'd need to know the complexity of the network.

**Comment by kwpugh** [comment] 2016-05-13 18:35
I working on getting a screenshot from one of the users on their setup.

**Comment by raoulvdberge** [comment] 2016-05-13 18:39
Please do. I'm 99,99% sure this is due to a my inefficient machine searching code, which I am now reworking.

**Comment by kwpugh** [comment] 2016-05-14 14:29
We are in the midst of a move to a fresh map, so he will test build after that.   He indicated, however it was a problem when having an external storage block attached to the system.

**Comment by raoulvdberge** [comment] 2016-05-14 14:47
So when you removed the external storage, the lag went away again?

**Comment by kwpugh** [comment] 2016-05-14 15:42
Yes, that is what he said.   I was online when he removed them, and I saw the TPS go back up and the time between ticks go down.

**Comment by raoulvdberge** [comment] 2016-05-14 22:23
Should be fixed in the next version, with the improvements I made.

**Comment by kwpugh** [comment] 2016-05-16 00:34
Any ETA on the next release?

**Comment by raoulvdberge** [comment] 2016-05-16 09:07
Today, 20 UTC.

**Comment by Harith163** [comment] 2016-05-16 10:09
Could you update the getting started guide or is it like old ae?

**Comment by raoulvdberge** [comment] 2016-05-16 10:58
You mean this https://github.com/raoulvdberge/refinedstorage/wiki/Autocrafting ?

I'll be doing this later.

**Comment by kwpugh** [comment] 2016-05-17 03:13
So, I put the new version in my server running forge 1907, massive lag when any refined system is running.   As soon as someone turns it off, it comes back to normal.   Does someone want to come one the server and look at the setups to get a better idea?

**Comment by raoulvdberge** [comment] 2016-05-17 07:47
Okay, I presume these are the external storages again. Just for testing, can you remove all the external storages? Does it fix the lag then?

**Comment by PlacidK** [comment] 2016-05-18 06:39
I'm having the same problem on my server with 0.6.2 on forge 1898 and 1907. I removed all external storage blocks (was a bit better) removed wireless transmitters (again a bit better) but only with the whole system off the lag was gone.

I had the same lag on 0.5.6. But it was an exporter in that version.

**Comment by raoulvdberge** [comment] 2016-05-18 09:03
I think I found the cause of this issue, will work on fixing this and will try to get a fix out today.

**Comment by raoulvdberge** [comment] 2016-05-18 09:54
@PlacidK While I'm working on it, please try version 0.6.4, it should make it a *bit* better.

**Comment by PlacidK** [comment] 2016-05-18 13:23
@raoulvdberge first reports from 20-30 mins testing 0.6.4 are very good :D 

So far i have added 5 wireless transmitters (fully upgraded) an external storage with chest and a exporter to an RFtools crafter.

NO LAG AT ALL!! everything is smoother than ever before!! Grabbing stuff from wireless grid (over 200 blocks from the controller) is instant, dragging, shift-rightclicking into the grid is instant.

The whole server is running smoother now, the only [Server thread/WARN]: Can't keep up!..... was at server start (is normal i guess).

I'm very happy! great job! :D

**Comment by kwpugh** [comment] 2016-05-18 13:28
I will give 0.6.4 a try as well.

**Comment by raoulvdberge** [comment] 2016-05-18 15:21
@PlacidK I'm very happy to see the update did its job. Just to be absolutely sure: this is the exact same setup you used back when it was laggy? Also, do you have the same amount of players online/ in the area? Thanks.

@kwpugh Thanks for trying it out. Looking forward to hear how it behaves on your server.

**Comment by PlacidK** [comment] 2016-05-18 15:55
Almost the same setup.
Same amount of players (small private server) before it even lagged without players online)

**Comment by kwpugh** [comment] 2016-05-18 17:05
Hey PlacidK,

I run a small 1.9 server as well, perhaps we can trade experiences/share knowledge during these rough times with 1.9.

Regards,

Kevin

**Comment by PlacidK** [comment] 2016-05-18 20:19
Update:

(sidenote: it's not the most powerfull server, only 1 player (me) online, only 1 network active on the server, imported from vanilla chest filled with stone and storage silo filled with cobble and various items)

Lag-spike / tick lag using an importer with 3 and 4 speed upgrades ->

Importer without speed upgrades or 1 or 2 upgrades worked normal.

with 3 upgrades:

[20:02:15] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2034ms behind, skipping 40 tick(s) 
 [20:02:31] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2419ms behind, skipping 48 tick(s) 
 [20:02:47] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2522ms behind, skipping 50 tick(s) 
 [20:03:04] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2716ms behind, skipping 54 tick(s) 
 [20:03:20] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2272ms behind, skipping 45 tick(s) 

With 4 upgrades:

 [20:04:06] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 21799ms behind, skipping 435 tick(s) 
 [20:04:36] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2295ms behind, skipping 45 tick(s) 
 [20:05:14] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 23054ms behind, skipping 461 tick(s) 
 [20:05:19] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4497ms behind, skipping 89 tick(s) 
 [20:05:55] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 22229ms behind, skipping 444 tick(s) 
 [20:06:00] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4491ms behind, skipping 89 tick(s) 
 [20:06:36] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 21722ms behind, skipping 434 tick(s) 
 [20:06:40] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4413ms behind, skipping 88 tick(s)

**Comment by raoulvdberge** [comment] 2016-05-18 20:36
@PlacidK Please retry with this version:  http://minecraft.curseforge.com/projects/refined-storage/files/2301007

Does the issue persist?

**Comment by raoulvdberge** [comment] 2016-05-19 00:45
I'm reworking some stuff now which should fix all performance issues (see #57). The past versions have indeed better performance, but didn't fix the root problem. I suspect this will be fixed by tomorrow.

**Comment by raoulvdberge** [comment] 2016-05-19 16:17
@PlacidK Can you retry with 0.6.7? Thanks

**Comment by PlacidK** [comment] 2016-05-19 18:51
I ran MC's debug profiler for ~1 min while importing with 4 speed upgrades and when the importer was done.
Results --> http://pastebin.com/up19fPPt (importing)
                  http://pastebin.com/x9T8c9eD (idle)

**Comment by raoulvdberge** [comment] 2016-05-19 19:16
@PlacidK Very weird. Retry with 0.6.8 please. If that doesn't work, then I don't know what to do...

**Comment by raoulvdberge** [comment] 2016-05-20 00:12
I'm gonna go ahead and close this issue.

I've tested the importer (on a server with a bunch of players online) with max upgrades importing a *full* chest of cobble and there was no noticeable TPS drop.

To be absolutely sure I asked another player to do the same thing as me **simultaneously**. Still no fps drop.

This issue did exist though, the controllers CPU usage went from 50% to 2-3% in 0.6.8.

**Closed by raoulvdberge** 2016-05-20 00:12 UTC
Labels: bug

**Comment by kwpugh** [comment] 2016-05-20 00:15
I just loading up the test of 0.6.8.   If you don't hear from me, all is good.

Thank you for your patience and perseverance in solving this problem.
