### ISSUE TITLE
External Storage with Quantum Storage causes massive TPS lag

### ISSUE THREAD

**Issue by Diverscope** [raoulvdberge/refinedstorage#1057] opened 2017-03-13 01:22 UTC
#### Issue description:
I moved my main base further away (Around 800 Blocks) and rebuilt my rs-system. It's kinda big with many auto processing and a quite lot of quantum storage Around 40). Anyway, as soon as I teleport to my old base, after a while I get some serious tps lags. It lasts for about one minute, then it goes away for a few seconds and then it's happening again. If I disconnect my external storages from my system, the tps lag doesn't occur.

Oddly enough, in my old base I had the same amount of Quantum Storages, but there it didn't seem to be a problem.

Other things that I've already tried:
- Killing all mobs (I had lots of chicken from the hatchery-Mod)
- Destroying all Ender IO-Facades
- Disconnected my craft-system from the RebornStorage-Mod
- Disconnected Network Transmitters
- Turned off the auto-crafting machines
- Removed all chunk loaders

#### What happens:

Connecting (too many?) Quantum Storages with external Storages causes tps lags.

#### What you expected to happen:

That my old base (Which is disconnected completely from the rs-system) doesn't lag.

#### Steps to reproduce:
1. Set up a rs-system
2. Connect with many Quantum Storages
3. Fill these Quantum Storages with a rather large amount of items (20k+)
4. Move the system further away.

I'm not sure if this can be reproduced by this way...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2215
- Refined Storage: 1.2.23

Does this issue occur on a server? [yes/no]

Dunno, but probably yes (I'm playing in Singlemode)

#### If a (crash)log is relevant for this issue, link it here:

I provided a nps-file just for the case: http://medien.pokemeister.net/tps-lags.nps

**Comment by aearly** [comment] 2017-03-29 05:39
I'm seeing a similar issue with a large number of external storage/quantum storage combos.  It seems 65 externals on a network is the magic number that starts killing TPS on the server.  The client performance is unaffected, just the server performance.

**Comment by raoulvdberge** [comment] 2017-04-01 17:52
This lag issue is caused by the constant turning on/off of the RS network. This causes the network to be rebuilt. Please make sure your RS system keeps running and doesn't turn off due to power issues.

![x](https://raoulvdberge.com/KLnRlY)

This is a duplicate of #566

**Closed by raoulvdberge** 2017-04-01 17:52 UTC
Labels: investigate, performance
