### ISSUE TITLE
World Fails to Load After Creating New Network

### ISSUE THREAD

**Issue by Evan1041** [raoulvdberge/refinedstorage#2388] opened 2019-12-27 22:57 UTC
#### Issue description: 
After creating a new network, world fails to load. Specifically, the world loads to 100% and then stops. No crash and nothing informative in the log (I linked the log below just in case). I am playing All the Mods 4. I am confident that this is an issue with refined storage because the world loads and saves just fine if I delete the two chunks which contain the refined storage network as well as the external storage (storage drawers; the refined storage network connects to a storage drawer controller). I have attempted to delete the network controller. This does not affect the results. I am not, however, very familiar with the mod nor working with save files so I could very well have deleted the controller incorrectly. 

I am hoping that at the very least someone can confirm that this is a Refined Storage issue, and whether or not there are plans to fix the issue in the near future (and if these plans will allow access to affected worlds again).

The refined storage network in question does not include any of the refined storage addon components, though this mod is in the pack. 

#### What happens: 
World fails to load.

#### What you expected to happen: 
Proper world loading or even a crash. 

#### Steps to reproduce:
Currently unknown. I have set up other refined storage networks with very similar components (external storage and same drives) and the world loads just fine. 

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.14.4
- Forge: 28.1.108
- Refined Storage: 1.7.1

#### Does this issue occur on a server? 
Unknown. Only observed in single player world.

#### If a (crash)log is relevant for this issue, link it here: 
Again, the game does not crash. The world loads to 100% and stops. The client is still responsive and the game does not crash. Seems to be caught in a loop.

[latest.log](https://github.com/raoulvdberge/refinedstorage/files/4006399/latest.log)

**Comment by Darkere** [comment] 2019-12-27 23:14
How would you be able to tell its Refined storage and not literally anything else in those 2 chunks????? 

The only time I've encountered similar issues was in creative, testing just how massive an autocraft I might be able to create. This can cause loading to take a very long time. 

You can analyze what Minecraft is doing by sampling the process with [Visual Vm](https://visualvm.github.io/), although that might be a bit complicated. (post a snapshot if you do manage to do it).

For deleting I believe the refinedstorage_network.dat under world/data/ contains the saved crafting tasks. 

Again chances are it's not related to RS at all. Worlds not loading due to corruption or overflowing farms unfortunately not a very rare thing.

**Comment by Evan1041** [comment] 2019-12-28 00:06
Thanks for the response!

I isolated the issue to two chunks (as mentioned before, the world loads and saves just fine when these two chunks are deleted). These two chunks are fairly sparse with only an Xnet network, refined storage network, and storage drawers. The storage drawers are isolated in one of the chunks and the Xnet network powering the system is isolated in the other. The only connection is the refined storage network. Perhaps this evidence is inconsequential.

The refined storage system itself is rather naive with only a few disk drives, a controller, and external storage. No autocrafting. The world itself is similarly naive with no massive farms or storage.  

#### Further Information:
If it's relevant, the issue may have occurred following an incomplete save of the world. If I recall, I forced Minecraft to quit. Perhaps this did not play well with Refined Storage?

**Comment by Uzkul** [comment] 2019-12-28 16:13
I'm basically having the exact same issues.. 100% loading and stuck there.
No crash nor obvious errors.
Only started today, I could play just fine yesterday (even though the external storage would sometimes break on world load, but that was easily fixed).

Unfortunately I am totally not savvy enough to check for actual error codes or do some world editing to check what might be the problem.
I also play ATM4, and have a drawers + xnet + refined storage setup.

**Comment by raoulvdberge** [comment] 2019-12-28 16:15
I'll try to get a new build up later this evening to fix this issue.

**Comment by raoulvdberge** [comment] 2019-12-28 16:18
This is a typical MC 1.14.4 issue with mods. The chunkloading is very prone to deadlocks. It's probably caused by Refined Storage, but if I don't have a world download it's very difficult to reproduce.

**Comment by Uzkul** [comment] 2019-12-28 16:45
Hello there, I play this purely in singleplayer.
IF there is a way me to send you my world, I can do so if it helps you.
I just don't know how to do it :)

**Comment by raoulvdberge** [comment] 2019-12-28 17:01
What modpack are you playing? You can upload a zip of your world on Github.

**Comment by raoulvdberge** [comment] 2019-12-28 17:02
@Evan1041  Can you do the same please. With the 2 bad chunks included.

**Comment by Uzkul** [comment] 2019-12-28 17:33
Hey @raoulvdberge ,
I'm playing All the Mods 4, latest version (0.2.9).

I made a zip of my world that's having the problems. Couldn't figure out how to upload it here on github, but it's a bit big too (630MB).
So I posted it on Google Drive : 
[https://drive.google.com/file/d/1sQCxMLXtr_b1aEQ9aSG_PfJMpn1nVtZH/view?usp=sharing](url)

Hopefully you can download it.

**Comment by Evan1041** [comment] 2019-12-28 20:02
Hi @raoulvdberge! 

Here's the direct download link (~100mb):
https://dl.dropboxusercontent.com/s/ikfj0sban1xtsra/Corkboard.zip?dl=0

This file includes the affected chunks. I have not made any changes to this file since the the issues started. 

Like @Uzkul, I'm playing All the Mods 4 version 0.2.9. I have also included Bounding Box Outline Reloaded version 1.0.14 and Linked Destruction version 0.7.2.9999. As I understand, these two mods are not required to load and play the world, and should not make a difference.

Thank you for your help!

**Comment by raoulvdberge** [comment] 2019-12-28 20:07
@Uzkul  Almost a terabyte is a bit bad on my connection. Are you able to shrink your world down by only including relevant chunks? In MCEdit for example.

**Comment by Darkere** [comment] 2019-12-28 20:23
The problem appears to be with the redstone check. 
![image](https://user-images.githubusercontent.com/4283717/71549078-c63f1b80-29b7-11ea-9952-19b63fa0b48a.png)



Snapshot: 

[redstone thread lock.zip](https://github.com/raoulvdberge/refinedstorage/files/4007418/redstone.thread.lock.zip)



I actually had a case on a server recently where that check was causing significant amounts of lag. I haven't found the time to investigate that yet though.

**Comment by Uzkul** [comment] 2019-12-28 20:25
Wish I could @raoulvdberge , but I have no idea how that thing works.
Don't even know how to load in my world in that program (I'm trying though) :)

**Comment by raoulvdberge** [comment] 2019-12-28 20:28
Is that a stacktrace dump @Darkere? Is it hanging on RedstoneMode#isEnabled?

**Comment by raoulvdberge** [comment] 2019-12-28 20:29
In that case you don't need to shrink it down anymore @Uzkul. I have enough with that information.

**Comment by Darkere** [comment] 2019-12-28 20:40
I was sampling the process. this is all that happened in the 52 seconds I had it running. 
The thread it was waiting on was calculating lighting for some solar panel during the same timespan.

**Comment by Uzkul** [comment] 2019-12-29 08:55
So I promised to do some more testing.
In this modpack (All the Mods 4) I started to try and load backups of the world without 1 specific mod at a time.
Only when I removed Solar Flux Reborn the world loaded up again.
So it seems on my end it's not a Refined Storage problem (as that loaded in fine just now with only Solar Flux Reborn removed).

**Comment by Darkere** [comment] 2019-12-29 14:08
For Evan1041 the Server Thread looks different. However very similarly the Solar Panel light calculation is what is actually working in the background. 

![image](https://user-images.githubusercontent.com/4283717/71557891-d6550a80-2a4c-11ea-9d56-759e8b7e2309.png)
![image](https://user-images.githubusercontent.com/4283717/71557895-e371f980-2a4c-11ea-8820-265d373929a7.png)


Snapshot: 
[lock.zip](https://github.com/raoulvdberge/refinedstorage/files/4008104/lock.zip)

So yes removing solar flux reborn would work for him as well.

**Comment by Zeitheron** [comment] 2019-12-29 18:30
Okay, this issue is definitely on my end. I tried to solve it, pushing a new release. Should resolve current issue.

**Comment by Darkere** [comment] 2019-12-29 18:43
Confirmed fixed. After updating Solar Flux Reborn both worlds now load up fine.

**Comment by raoulvdberge** [comment] 2019-12-29 20:52
Very cool and wholesome, thank you everyone for checking this out! Closing

**Closed by raoulvdberge** 2019-12-29 20:52 UTC
Labels: Bug, Can't Reproduce
