### ISSUE TITLE
1.10.2 Controller having 200MS of lag when crafting Machine is missing.

### ISSUE THREAD

**Issue by Speiger** [raoulvdberge/refinedstorage#1129] opened 2017-04-05 11:09 UTC
#### Issue description:
A RS System was crafting a HV Solar Panesl which needs a insane amount of Iron beeing smelted.
Some of my testers removed the furnace and it caused a huge issue because the controler did land in a lag loop. It killed hte server.

#### What happens:
a HV Solar Panel was requested and someone remvoed a vital component out of the crafting loop.

#### What you expected to happen:
Not to cause 200MS lag.

#### Steps to reproduce:
1. Make Recipes that take at least 8 steps and its so expensive that it takes up to 5-8k things to be smelted.
2: Remove the smelter.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2221
- Refined Storage: 1.2.24

Does this issue occur on a server? [yes/no]
yes.

Fix Suggestion:
Add a Crafting Timeout. If the process is frozen lets say for a minute or something with no item crafting at all it should cancle the crafting.
Because no crafting recipe should wait longer on things then 10000 ticks.
What i mean is not when 1 step is frozen for 10000 ticks because it could be that other steps are still working next to it. I mean then the crafting task did nothing for 10000 ticks. (i mean injected Items or Extracted Items)

**Comment by raoulvdberge** [comment] 2017-04-05 11:26
did you even check previous issues? -.-

duplicate of #838

**Closed by raoulvdberge** 2017-04-05 11:26 UTC

**Comment by Speiger** [comment] 2017-04-05 14:14
Yes but mine is different. Mine is when you remove a CraftingRecipe Provider @raoulvdberge that is a tiny difference but important. It doesnt notice that a crafting machine is missing. (Can only happen with Crafters that try to craft with a different machine)

**Comment by way2muchnoise** [comment] 2017-04-05 14:20
Removing a link in the chain shouldn't be causing extreme lag. The process should just be stuck. But it does boil down to it doing to my tries to insert it, which is exactly what #838 is about. Also the proposed fix to keep track of time is not a good solution as it takes to many resources and what if a task legit takes more time then that threshold we set?
