### ISSUE TITLE
Attempting to cast Refined Storage Class throws exception

### ISSUE THREAD

**Issue by Mr-Pyro** [raoulvdberge/refinedstorage#2278] opened 2019-07-09 22:47 UTC
https://github.com/KnightMiner/Inspirations/issues/128

#### What happens:
Game crashes
#### What you expected to happen:
not crash
#### Steps to reproduce:
1.play game
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:
https://paste.ubuntu.com/p/yhKBTxfMpW/
[pastebin/gist/etc link here]

**Comment by Darkere** [comment] 2019-07-10 04:42
duplicate of #2215

**Closed** 2019-07-20 10:36 UTC
Labels: Bug, CrossMod, Duplicate
