### ISSUE TITLE
Importers and external storage don't stay connected

### ISSUE THREAD

**Issue by darthhubgit** [raoulvdberge/refinedstorage#438] opened 2016-10-08 05:23 UTC
#### Issue description:
Importers and external storage don't stay connected to network.
#### What happens:
I have a crafting grid, solderer and two importers and an external storage connected to a controller. The importers and external storage routinely disconnect, but only seem to do so when chunks are reloaded. 
I have broken and reattached the importers, and lost items.
I have broken and reattached cable, and the external storage will show in the controller, but none of the external items appear in my crafting grid.

#### What you expected to happen:
They remain in my network.

#### Steps to reproduce:
1. Use importer and external network
2. Go to nether, or far enough away to get chunks to reload
3. I can't reproduce every time, so hope that 1+2 worked. But I can reproduce easily enough so I am happy to try somethings to help track this down.
...

#### Version (Make sure you are on the latest version before reporting):
- All The Mods Lite: 1.7
- Minecraft: 1.10.2
- Forge: 12.18.1.2095
- Refined Storage: 1.1.2

Does this issue occur on a server? [yes/no]
don't know
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment] 2016-10-08 19:41
Duplicate of #370

**Closed by raoulvdberge** 2016-10-08 19:41 UTC
