### ISSUE TITLE
Resource leak when autocrafting with missing materials

### ISSUE THREAD

**Issue by flitzpiepe96** [raoulvdberge/refinedstorage#1042] opened 2017-03-07 20:41 UTC
#### Issue description:
When trying to autocraft a recipe that lacks resources, memory usage explodes and won't stop to rise unless I close Minecraft (closing the world, removing the storage controller, ... does not help).

#### What happens:
Memory usage explodes. In f3 menu memory usage in the top right normally slowly climbs and falls back down by garbage collection. As soon as I click start in the crafting dialog this rises increadibly quickly, getting faster and faster for each impossible crafting job I try to trigger. This increases unless garbage collection runs so often, that Minecraft is not responding anymore. If needed I can attach sampler file, but as it seems more like a leak than lag I don't know if it helps.

#### What you expected to happen:
1. Crafting window shows if and why crafting is (im)possible
2. Memory usage should go back to normal or don't explode at all

#### Steps to reproduce:
1. Simply autocraft something without having all the resources needed. In my case it was a growth crystal tier 2 in SF3 with all steps from start to finish.
2. See attached gif. (usage actually rises so fast, that the gif can barely capure it with 15fps)

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2234
- Refined Storage: 1.2.22

Does this issue occur on a server? [yes/no]
It occurs on a client for sure. I have not tested whether it does on a server as well
![autocrafting leak](https://cloud.githubusercontent.com/assets/22731069/23676963/9d57ad48-037e-11e7-8963-546754e02833.gif)

**Comment by raoulvdberge** [comment] 2017-04-01 17:55
Duplicate of #838

**Closed by raoulvdberge** 2017-04-01 17:55 UTC
Labels: autocrafting, investigate, performance
