### ISSUE TITLE
Network Receiver/Transmitters not working with rftools dim

### ISSUE THREAD

**Issue by dovahkiin4991** [raoulvdberge/refinedstorage#1150] opened 2017-04-09 19:27 UTC
#### Issue description:
Network Receiver not working across rftools dimensions
#### What happens:
When using transmitter/receivers across rftools dimensions, even while loaded they don't work most of the time, occasionally it will but leaving and returning to the dimension brings this issue back. This only occurs when the receiver is in the rftools dim, not the other way around
#### Version 
- Minecraft: 1.10.2
- Refined Storage: 1.2.23

Does this issue occur on a server? [yes/no]
yes

**Comment by way2muchnoise** [comment] 2017-04-09 19:28
Are both sides chunkloaded?

**Comment by dovahkiin4991** [comment] 2017-04-09 19:29
yes

**Comment by raoulvdberge** [comment] 2017-04-09 20:05
Duplicate of #370

**Closed by raoulvdberge** 2017-04-09 20:05 UTC
