### ISSUE TITLE
Controller disappearing when leaving area and coming back.

### ISSUE THREAD

**Issue by BootyToast** [raoulvdberge/refinedstorage#239] opened 2016-08-02 05:15 UTC
So far this has happened every time I've left the area and come back. It's happened a few time already.
Here's a screenshot of what it looks like. Light hasn't updated yet at this point: 
![2016-08-02_01 12 01_2](https://cloud.githubusercontent.com/assets/10050188/17317712/9042045e-584e-11e6-8ccd-ee483dacfece.png)

**Comment by BootyToast** [comment] 2016-08-02 05:16
Also I'm hoping this may be a step in the right direction to figuring out why certain parts of the storage network disconnect at random!

**Comment by raoulvdberge** [comment] 2016-08-02 10:02
Do you have any logs?

Also does this happen on the latest version(s), or also on the previous ones?

**Comment by BootyToast** [comment] 2016-08-02 12:15
No logs or anything.. Only happens in 0.8.15. I downgraded to 0.8.12 and it hasn't happened since!

**Comment by raoulvdberge** [comment] 2016-08-02 12:58
Do you have this issue in 0.8.13?

**Comment by raoulvdberge** [comment] 2016-08-02 12:59
I can't reproduce this... what happens if you update Forge?

**Comment by raoulvdberge** [comment] 2016-08-02 13:02
Actually, can you test on Forge 2014 and see if you have the issue?

**Comment by BootyToast** [comment] 2016-08-02 18:45
Yep, I will try this in a bit! Sorry for the late response.

**Comment by raoulvdberge** [comment] 2016-08-03 03:19
@BootyToast 
I just read this on IRC, maybe try update Forge to the latest version...

![img](http://i.imgur.com/LUNLOr1.png)

**Comment by BootyToast** [comment] 2016-08-03 03:24
I will try this, man! I tried testing the issue with an earlier forge but there were some issues downgrading with other mods. Gonna update and will report back in a bit!

**Comment by BootyToast** [comment] 2016-08-05 05:45
I did update Forge to 2046, but it seems anything past Forge 2031 breaks more things than it fixes. A lot of people are reporting crashes with breaking certain blocks in Tinkers Construct among many other mods, so unfortunately I'm not able to use the current version. D:

**Comment by raoulvdberge** [comment] 2016-08-05 08:50
Yes, the network disconnecting is kinda of an unrelated issue. But good to hear it is fixed now!

**Closed by raoulvdberge** 2016-08-05 08:50 UTC
Labels: bug, can't reproduce

**Comment by raoulvdberge** [comment] 2016-08-05 08:56
(Btw, you should be able to use the RS upgrade in an old Forge like 2014 as well, before it was buggy :P)
