### ISSUE TITLE
Storage-Drawers Randomly Throwing Items in free Drawers.

### ISSUE THREAD

**Issue by Gyromax** [raoulvdberge/refinedstorage#1340] opened 2017-07-01 15:16 UTC
#### What happens:
If i connect my Drawer-System with an External-Storage-Controller on high Priority every Item that is send that way will be put into a Random free Drawer, even if the Item is sorted already in another Drawer, there is Space in that specific Drawer and the Drawer is locked. (i usualy keep some free unlocked for any Stuff i forgot to sort in). I also tried clearing all Drawers with a Disk-Manipulator and some Disks pulling all Stuff in. Then sorted all Items i got on my Disk into Drawers again, locked the Drawers and started unloading the Disks with the Manipulator.

#### What you expected to happen:
I expected the Drawers will work the same Way, as they worked, when i put some BC-Pipes to a Slave-Controller and send Items through them. It was be this behaviour:

> 1. Look for any drawers with a void upgrade and contain the same item.
> 2. Look for any drawers that are locked and contain the same item.
> 3. Look for any drawers that are unlocked and contain the same item.
> 4. Look for any drawers that are unlocked and are empty. If an item can't be placed for a given rule because a drawer is full, it will look to the next rule. If more than one valid destination is found at the highest applicable priority, then the slot nearest the controller (by connection length) will generally be 
chosen.
Quoted from: https://github.com/jaquadro/StorageDrawers/wiki/Drawer-Controller

#### Steps to reproduce:
1. Build up a Drawer-System (i use the Maximum-Range of 25x25x25 with a centered Controller) and do all I/O-Actions with Slave-Controllers.
2. Build a Basic-Refined-Storage-System.
3. Sort some Items in the Drawers and lock them (i'm using Drawer without Void-Upgrades).
4. Leave some Drawers unlocked and empty for Stuff u haven't sorted yet.
5. Throw in the Stuff u sorted before and locked to the drawer
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 1.11.2-13.20.1.2388
- Refined Storage: 1.14.18
- Storage Drawers: 1.11.2-4.2.9
- Storage Drawers Extras (Skins): 1.11.2 - 2.0.0

Does this issue occur on a server? [yes/no]
yes

If u need anything more, just tell me and i'll deliver as fast as possible, if it's possible for me.

**Comment by raoulvdberge** [comment] 2017-07-03 11:28
Wontfix. Intended behavior, just sort and lock all your drawers first.

**Closed by raoulvdberge** 2017-07-03 11:28 UTC
