### ISSUE TITLE
Compacting drawer items not inserted into crafting grid properly

### ISSUE THREAD

**Issue by wylderhoads1809** [raoulvdberge/refinedstorage#700] opened 2016-12-02 17:33 UTC
#### Steps to reproduce:
1. Setup compacting drawer with gold ingots attached to network via external storage cable. Set cable to insert and extract mode
2. attempt to craft golden carrot in crafting grid by searching in JEI and hitting plus button
3. no/only a few nuggets will be inserted, despite having enough in the network.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 1.10.2-forge1.10.2-12.18.2.2166
- Refined Storage: 1.2.8

Does this issue occur on a server? [yes/no] no

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by wylderhoads1809** [comment] 2016-12-02 17:40
UPDATE: Removing and replacing all of the external storage cables fixed the problem. Not sure if this is a bug or just a symptom of updating.

**Comment by raoulvdberge** [comment] 2016-12-03 11:17
duplicate of #370

**Comment by xannor** [comment] 2016-12-04 14:02
I ran across this also, two days ago, it has also randomly effected crafting as well. I have a recipe for ender io to create vibrant crystals and with 8 nuggets in a compacting drawer it would not + click via JEI and the crafting monitor would just sit. I had to craft more vibrant ingots, once there was about 18 nuggets worth in the drawer the craft completed.

I had updated for both SD and RS on the 2nd (last Friday) and that is when I started to notice this issue. Did not occur prior to that.

**Comment by wylderhoads1809** [comment] 2016-12-05 16:42
Interesting that when you make more nuggets it works in a compacting drawer. I disconnected mine from the system for the time being but my cobblestone is still in a regular storage drawer and it won't recognize any of it when I hit the "+" button (I have 6k+ cobble).

**Comment by raoulvdberge** [comment] 2016-12-05 17:54
Are you able to retrieve the items from the storage WITHOUT using JEI "+"?

**Comment by xannor** [comment] 2016-12-05 18:58
Yes, I can manually click in and out, only some items, mostly it seems like oredict ones, will not fill on a jei plus. I also have a crafting pattern that uses 8 vibrant nuggets and an emerald, I think it was created as oredict but can't verify right now, that with 8 nuggets in a compacting drawer, would sit in the crafting queue until I added more ingots to the drawer, via another crafting pattern.

-----Original Message-----

**Comment by bubblesayoyo** [comment] 2016-12-06 15:32
I'm having just about the same problem. Things connected a storage drawer Drawer Controller via an external storage just don't seem to want to work properly.  Seems to work once or twice when first logging in (might just SEEM this way, no actual proof) then it won't "+ click" into the crafting grid. I can manually grab them out however.  Also, it hangs on my auto crafting when things from the drawers are needed. No matter how long it sits, they never resolve. 

refinedstorage-1.2.8.jar
StorageDrawers-1.10.2-3.5.6

**Comment by xannor** [comment] 2016-12-06 16:40
I have noticed a pattern that maybe someone else can verify. It seems, to me at least, to only be ore dictionaried items from a drawer, and when 4 or more are needed. I could plus click an immersive engineering hv connector but not the light engineering block. Never had a problem with Redstone dust, which is also in my drawer system.

-----Original Message-----

**Comment by bubblesayoyo** [comment] 2016-12-06 16:46
Mine is just completely hit or miss.  I was just playing and I needed 4 pieces of iron for a recipe and just go 3 of the 4 shift clicked into the grid. I cleared it and tried again, and got 0 of 4, and now it won't get any again. As for 4 or more, I've tried several times to get an EnderIO capacitor (2 gold nuggets, 1 copper, 4 red stone) and it only seems to grab the gold nuggets, although every now and then it will work completely. Again just seems so random...

**Comment by wylderhoads1809** [comment] 2016-12-06 18:31
Idk about the ore-dictionary thing unless stone is in that too because even my cobblestone (which is in just a regular storage drawer with an external storage) won't fill in with the jei +, only when I put it in manually. I have also noticed the pattern where sometimes it will fill 3 out of 4 when I hit the +, but with cobble it won't insert any of the required items.

**Comment by xannor** [comment] 2016-12-10 14:45
Well, I dont know if it was SD 3.5.8+ or RS 1.2.10 but I no longer have this issue it seems.

**Comment by raoulvdberge** [comment] 2016-12-10 15:00
I couldn't reproduce this either (tried the golden carrot thing).

**Comment by wylderhoads1809** [comment] 2016-12-11 15:23
I will update both today and see if it is also fixed on my end!

**Comment by raoulvdberge** [comment] 2016-12-14 06:53
I'm assuming this thing is fixed

**Closed by raoulvdberge** 2016-12-14 06:53 UTC
Labels: bug
