### ISSUE TITLE
Disconnected from server when you try to "move items" from JEI to Refined Storage Crafting grid

### ISSUE THREAD

**Issue by xavizus** [raoulvdberge/refinedstorage#2150] opened 2019-01-01 16:02 UTC
## Bug Report
When the player try use JEI to automatic fill Refined Storage Crafting grid for the specific recipe Greenhouse Glass. The player get disconnected with the following error message:
_**Internal Exception: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes**_

Edit:
It seems to only effect Refined Storage Crafting grid. Nothing happens if I use a crafting table with the ingredients in the inventory.

## Steps to Reproduce (for bugs)

1. Open Refined Storage Crafting grid
2. Search for Greenhouse Glass
3. Left click the Greenhouse Glass
4. Press the +-icon (Move Items)
5. Magic
6. You get disconnected and get the following error message:
Internal Exception: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes

## Logs

* Server Log:
[17:22:41] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Xavizus lost connection: Disconnected
[17:22:41] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Xavizus left the game

*Client Logs
[Link to Client Logs @pastebin](https://pastebin.com/x20Z1a6M)
* Crash Log:

## Client Information

* Modpack Version: StoneBlock 1.0.31
* Minecraft: 1.12.2
* Mod: 1.6.11
* Forge: forge-1.12.2-14.23.5.2768 
* Server/LAN/Single Player: Server (Have not tested this in singelplayer)
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Darkere** [comment] 2019-01-01 16:17
Duplicate of #1790

**Closed** 2019-01-01 16:59 UTC
