### ISSUE TITLE
Importer and Exporter not functioning after returning from the Nether

### ISSUE THREAD

**Issue by AGWeeB** [raoulvdberge/refinedstorage#752] opened 2016-12-14 20:01 UTC
#### What happens: When returning from the Nether an exporter and importer that are configured to export/import to/from a crafting grid do not work. When they are not functioning you are unable to click any of the configuration buttons (redstone mode, type, mode, etc. buttons). By breaking the block and creating it one again the exporter/importer start to function again.

I also have noticed that when they are not functional, I am still able to use the Wrench to pull my exporter configuration. I then break the exporter block, put it back and re-write the configuration it start to function correctly again.

#### Steps to reproduce:
1.Have a exporter exporting from grid to SAG Mill with some white listed ores
2.Have importer importing from Vanilla Chest to Grid
3.Exporter and Importer work properly at this point
3.Go to nether....Return to overlord
4.Put items in chest attached to importer and they do not import
5.Put ores that have been white listed in exporter in grid and they do not export.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.2.2171
- Refined Storage: 1.2.8

Does this issue occur on a server? Not sure

**Comment by raoulvdberge** [comment] 2016-12-14 20:14
Duplicate of #370

Try breaking + replacing your controller as temporary workaround

**Closed by raoulvdberge** 2016-12-14 20:14 UTC
