### ISSUE TITLE
1.11.2 Grid not showing items and not usable

### ISSUE THREAD

**Issue by Shorty9385** [raoulvdberge/refinedstorage#1348] opened 2017-07-08 01:25 UTC
#### Issue description:
     When items are placed into the storage, they will show unless I log off and back on. They then "disappear" and the crafting grid becomes unusable. I did look through issues and did not find any on the version I am using. Just for the 1.12 version of minecraft.
#### What happens:
     Grid becomes unusable, storage block shows items whereas the grid does not. I am using the creative storage block, connected to 2 crafting grids, the creative controller, and the interface. I am using extra utilities transfer pipe to go from the crystal chest from iron chest , to my storage. Removing and putting them back down does nothing. I have used this setup every time I make a base and have never had any issues prior.
#### What you expected to happen:
     My items to appear...
#### Steps to reproduce:
1. Put items in to storage controller
2. Log off and back on
3. Items not showing....
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: forge-1.11.2-13.20.1.2393
- Refined Storage: refinedstorage-1.4.18

Does this issue occur on a server? [yes/no]
     Yes
#### If a (crash)log is relevant for this issue, link it here:
     No crash log because the game does not crash
[pastebin/gist/etc link here]
     http://prntscr.com/ft0zpy (list of mods)
     http://prntscr.com/ft10ta (setup)
     http://prntscr.com/ft116x (controller)
     http://prntscr.com/ft11dw (crafting grid)

**Comment by Shorty9385** [comment] 2017-07-08 05:09
Downgraded to version 1.4.17 and it's working beautifully... No issues

**Comment by raoulvdberge** [comment] 2017-07-08 08:03
Duplicate of #1259 

This fix will come to 1.11 soon

**Closed by raoulvdberge** 2017-07-08 08:03 UTC
