### ISSUE TITLE
Ticking screen crash

### ISSUE THREAD

**Issue by OmniArcher** [raoulvdberge/refinedstorage#1216] opened 2017-05-13 20:13 UTC
#### Issue description:
Having a ticking screen crash occur on a server, it doesn't happen to everyone so must be client side I'm guessing. Running on the Foolcraft pack 1.3.2. The grids have worked previously for me and are still working for some others on the server. Have no idea what initially started the problem. 

#### What happens:
Crash to desktop when opening any grid/wireless grid. Gui appears briefly, doesn't load any of the items
#### What you expected to happen:
The grid gui to open properly
#### Steps to reproduce:
1. Opening any grid

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage: 1.2.25

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:

[https://puu.sh/vOZsY/01b1bb8b09.txt]

**Comment by raoulvdberge** [comment] 2017-05-13 20:16
The crash happens while it's trying to get the display name of an item in your grid.

The problem is at the item side, but unfortunately the crash tells nothing about which mod that causes this.

**Comment by OmniArcher** [comment] 2017-05-13 21:38
Located the disk drive manually, dumping the items into a chest. This seems to be a common issue on our server so I'll post back once I find the item.

**Comment by OmniArcher** [comment] 2017-05-13 22:46
Managed to export the item into a chest, it just doesn't appear so I'm guess the best fix for this at the moment is just voiding the drive.

**Comment by raoulvdberge** [comment] 2017-05-14 08:27
Okay, I'll have to close this issue then, since it isn't RS' fault.

**Closed by raoulvdberge** 2017-05-14 08:27 UTC
Labels: bug, crossmod
