### ISSUE TITLE
Auto Crafting Freezes Server

### ISSUE THREAD

**Issue by Sir-Will** [raoulvdberge/refinedstorage#1225] opened 2017-05-17 17:33 UTC
An auto crafting did freeze the server until the controller was removed.

refinedstorage-1.2.25
forge-1.10.2-12.18.3.2281-universal

Thread Lock:
```
[19:12:15] [Thread Locksmith Watchdog/INFO] - java.util.Collections$UnmodifiableCollection$1.hasNext(Collections.java:1041)
[19:12:15] [Thread Locksmith Watchdog/INFO] - net.minecraftforge.oredict.ShapedOreRecipe.checkMatch(ShapedOreRecipe.java:242)
[19:12:15] [Thread Locksmith Watchdog/INFO] - net.minecraftforge.oredict.ShapedOreRecipe.func_77569_a(ShapedOreRecipe.java:190)
[19:12:15] [Thread Locksmith Watchdog/INFO] - com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingPattern.lambda$new$0(CraftingPattern.java:52)
[19:12:15] [Thread Locksmith Watchdog/INFO] - com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingPattern$$Lambda$2126/2032023970.test(Unknown Source)
[19:12:15] [Thread Locksmith Watchdog/INFO] - java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
[19:12:15] [Thread Locksmith Watchdog/INFO] - java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
[19:12:15] [Thread Locksmith Watchdog/INFO] - java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
[19:12:15] [Thread Locksmith Watchdog/INFO] - java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
[19:12:15] [Thread Locksmith Watchdog/INFO] - java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
[19:12:15] [Thread Locksmith Watchdog/INFO] - java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[19:12:15] [Thread Locksmith Watchdog/INFO] - java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
[19:12:15] [Thread Locksmith Watchdog/INFO] - java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[19:12:15] [Thread Locksmith Watchdog/INFO] - java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
[19:12:15] [Thread Locksmith Watchdog/INFO] - com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingPattern.<init>(CraftingPattern.java:52)
[19:12:15] [Thread Locksmith Watchdog/INFO] - com.raoulvdberge.refinedstorage.item.ItemPattern.create(ItemPattern.java:210)
[19:12:15] [Thread Locksmith Watchdog/INFO] - RebornStorage.multiblocks.MultiBlockCrafter.rebuildPatterns(MultiBlockCrafter.java:206)
[19:12:15] [Thread Locksmith Watchdog/INFO] - RebornStorage.multiblocks.MultiBlockCrafter.onConnectionChange(MultiBlockCrafter.java:225)
[19:12:15] [Thread Locksmith Watchdog/INFO] - RebornStorage.tiles.TileMultiCrafter.onConnected(TileMultiCrafter.java:168)
[19:12:15] [Thread Locksmith Watchdog/INFO] - com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeGraph.rebuild(NetworkNodeGraph.java:140)
[19:12:15] [Thread Locksmith Watchdog/INFO] - com.raoulvdberge.refinedstorage.api.network.INetworkNodeGraph.rebuild(INetworkNodeGraph.java:24)
[19:12:15] [Thread Locksmith Watchdog/INFO] - com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:329)
[19:12:15] [Thread Locksmith Watchdog/INFO] - org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:231)
[19:12:15] [Thread Locksmith Watchdog/INFO] - net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2803)
[19:12:15] [Thread Locksmith Watchdog/INFO] - net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjp000(WorldServer.java:2790)
[19:12:15] [Thread Locksmith Watchdog/INFO] - net.minecraft.world.World.func_72939_s(World.java:6012)
[19:12:15] [Thread Locksmith Watchdog/INFO] - net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2157)
[19:12:15] [Thread Locksmith Watchdog/INFO] - net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
[19:12:15] [Thread Locksmith Watchdog/INFO] - net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
[19:12:15] [Thread Locksmith Watchdog/INFO] - net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[19:12:15] [Thread Locksmith Watchdog/INFO] - net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[19:12:15] [Thread Locksmith Watchdog/INFO] - java.lang.Thread.run(Thread.java:745)
```

**Comment by raoulvdberge** [comment] 2017-05-18 15:30
Please read previous before creating an issue.

Duplicate of #838

**Closed by raoulvdberge** 2017-05-18 15:30 UTC

**Comment by Sir-Will** [comment] 2017-05-21 13:22
@raoulvdberge this issue is not about a large crafting amount order. This was caused by one item request how you can see here:
![](http://i.imgur.com/8bDadNH.jpg)

**Comment by raoulvdberge** [comment] 2017-05-21 13:31
NBT complexity != calculation complexity
