### ISSUE TITLE
I get kicked out of game when I open crafting manager

### ISSUE THREAD

**Issue by MettytheCutiefly** [raoulvdberge/refinedstorage#2202] opened 2019-03-26 11:23 UTC
#### Issue description:
Opening crafting manager causes this issue, playing on the latest version of FTB Revelation

#### What happens:
https://cdn.discordapp.com/attachments/406255387961065485/559859113383952404/unknown.png Picture of what happens

Seems to be a packet issue???

#### What you expected to happen:
For the crafting manager to work and to not get kicked out of the server while doing so. I just wanna put some patterns in it.

#### Steps to reproduce:
1. Click on crafting manager
2. Crash
...

#### Version:

- Minecraft: 1.12.2 (FTB Revelation, latest update)
- Forge: 14.23.5.2815
- Refined Storage: 1.6.12

Does this issue occur on a server? [yes/no] 
Yes.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment] 2020-04-26 08:41
Duplicate of #1790

**Closed by raoulvdberge** 2020-04-26 08:41 UTC
Labels: Bug
