### ISSUE TITLE
Wireless crafting grid + duping items

### ISSUE THREAD

**Issue by Lurthis** [raoulvdberge/refinedstorage#2024] opened 2018-10-05 08:53 UTC
#### Steps to reproduce:
1. Put items in the wireless crafting grid does not matter if they craft into anything 
2. Close the wireless crafting grid
3. open the wireless crafting grid
4. Click the X to clear the grid
5.Check inventory to confirm items were dupped

#### Version  (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 
- Refined Storage: 1.6.5

Does this issue occur on a server? [yes/no]
unsure as I am not on a server
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment] 2018-10-05 12:06
This is likely fixed indev. Would be awesome if you could try with the latest dev build from here [https://jenkins.raoulvdberge.com/job/refinedstorage/](url)

**Comment by ineternet** [comment] 2018-10-05 13:18
Can't seem to reproduce on 1.6.5
https://gfycat.com/SoupyWellgroomedBlackbuck

**Comment by Lurthis** [comment] 2018-10-05 14:15
I am testing a few things seeing if it is a conflict

**Comment by Lurthis** [comment] 2018-10-05 14:28
https://gyazo.com/660d0584febbb567b87b1214bf44a41d 

This is what it looks like I also just found out you don't need to close it to dupe it. 

https://gyazo.com/bf037a7a1f236a40e97d882334460a10

**Comment by raoulvdberge** [comment] 2018-10-05 16:56
OK. Multiple people have reported this by now, but I can't reproduce this with just RS.

Now the task for you: keep removing mods from that pack until you can no longer reproduce it. So we can know what mod causes this, since I can't reproduce it with just RS.

**Comment by raoulvdberge** [comment] 2018-10-05 19:16
no probs, it's not urgent.

**Comment by raoulvdberge** [comment] 2018-10-14 14:44
Any update?

**Comment by krisavi** [comment] 2018-10-14 20:17
I did test and it seems to be Refined Storage Addons issue, it only appears with wireless terminal

Tested with minimal setup
Refined Storage 1.6.5
Refined Storage Addons 0.4.2
Forge 14.23.5.2768
FML 8.0.99.99
MCP 9.42
MC 1.12.2

**Comment by raoulvdberge** [comment] 2018-10-15 12:48
@krisavi Do you have the same issue with Refined Storage 1.6.6 (dev builds from Jenkins)?

**Comment by chspence** [comment] 2018-10-16 00:39
I am having the same issue. RS 1.6.5, RSA 0.4.2, only with wireless crafting terminal small x.

**Comment by raoulvdberge** [comment] 2018-10-16 07:42
Confirmed. Working on a fix now.

**Comment by raoulvdberge** [comment] 2018-10-16 07:54
Fixed for RS 1.6.6

**Closed by raoulvdberge** 2018-10-16 07:54 UTC
Labels: Area: Crossmod, Status: Confirmed, Type: Bug
