### ISSUE TITLE
Crash when adding Controller - java.lang.AbstractMethodError: Method com/raoulvdberge/refinedstorage/tile/TileController.getWorld()Lnet/minecraft/world/World; is abstract

### ISSUE THREAD

**Issue by Pierre-Demessence** [raoulvdberge/refinedstorage#2293] opened 2019-08-06 16:04 UTC
### Issue description:
A user on my server had his RS system bugging, so he destroyed his controller to put it back again, and it made the server crash.

### What happens:
Server crashed when user put back RS controller, and world crash every time is loaded (the chunk is also chunkloaded). World doesn't load in SP either.

### What you expected to happen:
World loading even with a RS Controller.

### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.12.2
- Forge: 14.23.5.2838  
- Refined Storage: 1.6.15

###Does this issue occur on a server? [yes/no]
Yes

### If a (crash)log is relevant for this issue, link it here:
Here's the Forge Crash Log: https://pastebin.com/ERqaLJx3

**Comment by Darkere** [comment] 2019-08-06 16:16
Duplicate of #2241

**Comment by Pierre-Demessence** [comment] 2019-08-06 16:42
Indeed it does seem to be the same issue. I'm not familiar enough with github issues, should I go over there and repost everything or continue here?
While I receive an answer I'll at least post here the new information I have:


I have been able to reproduce it after removing the Controller through MCEdit and then going into the world myself in Creative and adding it again. It then crashed immediately.
I took some pictures of the setup:

Without the Controller:
![unknown (2)](https://user-images.githubusercontent.com/1756398/62558600-adec2a00-b879-11e9-9a5a-2bac1520c3dd.png)
With the Controller:
![unknown (1)](https://user-images.githubusercontent.com/1756398/62558555-9745d300-b879-11e9-835b-c660d0219cf2.png)

**Comment by Pierre-Demessence** [comment] 2019-08-06 16:46
Another update:

It's related to the upper part of the network, so the pictures are meaningless.
I have been able to place the controller around the Importer you can see at the bottom without issue. But as as soon as I put it against the cable you can see at the top, it crashed.

I'll cut part of the network one by one and put the controller and come back when I know what part/block of the RS network is causing the crash.

**Comment by Pierre-Demessence** [comment] 2019-08-06 17:11
So the setup is composed of only Crafting Grids + the Controller. Nothing more as far as we're talking about RS (the rest was disconnected before-hand and it not part of the crash).

Also a very peculiar observation is that it doesn't crash here
![unknown (3)](https://user-images.githubusercontent.com/1756398/62560263-f527ea00-b87c-11e9-9e90-0bd882e22f27.png)
But it does here, one block apart:
![unknown (4)](https://user-images.githubusercontent.com/1756398/62560266-f5c08080-b87c-11e9-9db7-8787d371d47c.png)

**Comment by Pierre-Demessence** [comment] 2019-08-06 17:28
Another update:

I removed the thing at the right of the last picture which are not RS blocks, and I also removed the 6 crafting grids and it still crashes when I put a controller "around the place where it is on the picture above". So in this case it crashed with only 1 Controller and some cables.

I'll try removing all the cables one by one and putting them back.

**Comment by Darkere** [comment] 2019-08-06 17:36
It's probably related to the chunk I imagine there is a chunk border between the two places in your pictures. Anything else in that chunk?

**Comment by Pierre-Demessence** [comment] 2019-08-06 18:12
There is no chunk between the two controller as you can see on this picture where I activated the chunk grid overlay (the blocks of gold indicate the position of the controller on the previous picture).
![unknown (5)](https://user-images.githubusercontent.com/1756398/62564440-1db3e200-b885-11e9-89c9-f79870ca78b2.png)

But as you can see on the left-side of the picture, some parts of the network (network composed of cables only), goes to another chunk. I removed some cable here and then, to try and see long much it can go until it crashes, and with a line of cable going in at least two chunks it works without crashing:
![unknown (6)](https://user-images.githubusercontent.com/1756398/62564824-d8dc7b00-b885-11e9-9ef6-99653452a88d.png)


If that can help, here is the save of the world (as of time of https://github.com/raoulvdberge/refinedstorage/issues/2293#issuecomment-518766868): https://mega.nz/#!2JMEwaAS!AkdIe1yaRfPpmLsM25-vMUndGr3VZr63fc5nYNiuR8U
And the modpack that goes with it (for Twitch Launcher): https://mega.nz/#!2IE22YiB!zmGzges0NuLp1m1b1iYSFAByF1_U_YDL13Q0vvsEaOY
To reproduce the crash, place a controller at position (567,87,-777).

**Comment by raoulvdberge** [comment] 2019-08-25 09:26
Thx for all the info. Will keep your comments in mind. Closing this as it's a duplicate.

**Closed by raoulvdberge** 2019-08-25 09:26 UTC

**Comment by balloman** [comment] 2020-04-13 18:38
Sorry to necro this issue, but if we get this error, what's the recourse? Disabling the mod until there is a fix or?

**Comment by Darkere** [comment] 2020-04-13 19:33
Removing the offending controller in MCedit should work. 
Replacing it may produce the bug again. You might be able to get around by moving the controller. 

Not sure. We've not found out how this bug starts occurring.

**Comment by balloman** [comment] 2020-04-13 20:58
Ok, yeah I have been able to workaround the issue by having forge.cfg remove erroring tile entities, then placing the controller in a different location. However, MCEdit did not work for me
