### ISSUE TITLE
[1.10.2]External Storage - Colossal Chest: shift-crafting TPS-lag

### ISSUE THREAD

**Issue by PWTordenskiold** [raoulvdberge/refinedstorage#852] opened 2017-01-09 21:11 UTC
#### Issue description:
[Attached Sampler]( http://www.filedropper.com/rslagcraft), when shift-crafting about 10 stacks of Base Essence Ingot(Iron, 4 Prosperity Shard).
Using Colossal Chest(12M) as External Storage. When shift-crafting stack(s) it causes [immense TPS lag](http://imgur.com/Q329YO1). It does not matter what is crafted, but the more items in the recipe the worse and longer the TPS lag.
#### What happens:
TPS lag
#### What you expected to happen:
Fluffy bunnies?
#### Steps to reproduce:
1. Craft and set up a colossal chest
2. Fill it with items and attach external storage to interface
3. Shift-craft something with items from the chest
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2202
- Refined Storage: 1.2.16

Does this issue occur on a server? [yes/no]
Unknown, tested SSP.

I believe you briefly mentioned issues with Colossal Chest in Darkosto's stream raoul, but after a quick search here I cannot find any mention of it. So just to be sure, reporting.

**Comment by Time6628** [comment] 2017-01-12 00:19
Occurs on server as well.

**Comment by way2muchnoise** [comment] 2017-01-12 10:51
Related to CyclopsMC/CyclopsCore#35, it is related to a very slow construction of capabilities

**Comment by Time6628** [comment] 2017-01-12 17:08
This also happens with storage drawer controllers and any other kind of large storage system.

**Comment by way2muchnoise** [comment] 2017-01-12 17:10
Without nps files of the issue we can't really do anything. So feel free to profile it and make an issue for it.

**Comment by raoulvdberge** [comment] 2017-01-12 17:11
can you expand the warmroast view a bit more so we can see which item is causing the stack copying lag?

**Comment by way2muchnoise** [comment] 2017-01-12 17:13
Tbh 5% seems rather low @raoulvdberge, I wonder where the other time is going if that is the issue.

**Comment by raoulvdberge** [comment] 2017-01-12 17:14
I need to change the ext storage a bit so it doesn't uses copies of stacks, since it only does comparing in `detectChanges`. I'll look into that later.

**Comment by raoulvdberge** [comment] 2017-01-13 01:39
Duplicate of #325

**Closed by raoulvdberge** 2017-01-13 01:39 UTC
Labels: crossmod, performance
