### ISSUE TITLE
Feature Request: EnderIO Conduit Compatibility

### ISSUE THREAD

**Issue by TristanBomb** [raoulvdberge/refinedstorage#905] opened 2017-01-23 13:54 UTC
I believe in 1.7.10, the AE2 cables could be made into EnderIO conduits, and thus could be used with the conduit facades and occupy the same block as power or other conduits. Admittedly, I don't know if it was implemented by EnderIO or AE2, so perhaps it should be on the EIO Github instead, but similar integration would certainly make cable management less of a hassle.

**Comment by raoulvdberge** [comment] 2017-01-23 14:42
Duplicate of #135

**Closed by raoulvdberge** 2017-01-23 14:42 UTC

**Comment by TristanBomb** [comment] 2017-01-23 18:57
Whoops, my bad! Thought I had checked all the issues and didn't see it. Sorry to waste your time :(
