### ISSUE TITLE
JEI related sorting issue

### ISSUE THREAD

**Issue by flameface11** [raoulvdberge/refinedstorage#2299] opened 2019-08-12 03:54 UTC
#### Issue description:
pressing JEI sort button while in a grid it mixes up the entire inventory including hotbar
#### What happens:
entire player inventory gets jumbled around and "sorted" including the hotbar when normally the hotbar doesnt get sorted
#### What you expected to happen:
i expected it not to sort while typing into the search bar
#### Steps to reproduce:
1.open grid while JEI is installed
2.press the sort button

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:14.23.5.2838
- Refined Storage:latest
- Pack engineer's life

Does this issue occur on a server? no

**Comment by Darkere** [comment] 2019-08-12 19:44
Duplicate of #2014 

latest is not a version
JEI does not have any sort of inventory sorting the mod that does this is Inventory tweaks.

I've only run into this issue with Middleclick, but I've probably just unbound the sort at some point. cpw's inventory sorter does not have this issue.

**Closed** 2019-08-25 09:25 UTC
