### ISSUE TITLE
DiskManipulator "destroyed" all items inside the 64k disks

### ISSUE THREAD

**Issue by Miraak7000** [raoulvdberge/refinedstorage#1146] opened 2017-04-09 10:08 UTC
#### Issue description:
What I've done: 
- did steup some basic drawer and drawer controller and connected them via external storage to the RS-System
- connected a disk manipulator to the RS-System
- did take out all 64k disks manually from the disk drive (disk drive was empty now)
- inserted them into the disk manipulator and he pushed them out right away without doing anything (idea was to move the items from the disks into the drawer - at least some of them)

#### What happens:
nothing happened, the disk still say they are full of items but once inserting them again into the disk drive no items shown up in the grid. It seems the items are still inside the disks but I can't get access to them anymore.

I've braked the controller, placed them again but still can't get access to my items. Also did setup a new seperately system and also there I can't get access to my items on the disks. 

I've done almost the same before in another world but with different (older) forge and RS version and it was working fine. Don't know what happened here now.

#### Version (Make sure you are on the latest version before reporting):
- Minecraft: 1.10.2 
- Forge: 12.18.3.2254
- Refined Storage: 1.2.18

Does this issue occur on a server? 
yes

**Comment by LiEyWe** [comment] 2017-04-11 17:41
I have a similar problem. In one of my 4k storage disks are 3 items (emptied them before with the disk manipulator into another disk) which do not show up in a grid, but the disk says it contains 3 items

**Comment by raoulvdberge** [comment] 2017-04-15 22:25
The disappearing of items is due to a Forge bug that has been reported before. This is not an RS issue.

Duplicate of #821

See https://github.com/MinecraftForge/MinecraftForge/issues/3682

**Closed by raoulvdberge** 2017-04-15 22:25 UTC
