### ISSUE TITLE
Refined Storage Eats Items

### ISSUE THREAD

**Issue by McSassyK** [raoulvdberge/refinedstorage#629] opened 2016-11-13 22:34 UTC
#### Steps to reproduce:
1. Put items directly into the system by hand. Some or all may disappear.
2. Put items into the system via the linked ender bag/chest. Some or all may disappear.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 
- Refined Storage:

Does this issue occur on a server? [yes/no] Not that I know of, I only play single player.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment] 2016-11-13 22:55
*sigh*

Which Refined Storage version are you on? I'm literally asking it in the issue template.

**Comment by McSassyK** [comment] 2016-11-13 23:09
Sigh. Whatever version Hermitpack is using. A little less sarcasm please. Not all of us are as perfect as you. Jeez.

Sent from Yahoo Mail on Android 
 
  On Sun, Nov 13, 2016 at 4:55 PM, Raoul<notifications@github.com> wrote:   
sigh

Which Refined Storage version are you on? I'm literally asking it in the issue template.

**Comment by raoulvdberge** [comment] 2016-11-13 23:34
> Sigh. Whatever version Hermitpack is using. A little less sarcasm please. Not all of us are as perfect as you. Jeez.

You know, I get loads of bugreports on a daily basis. It is really annoying if I have to correct every reporter.

**Comment by raoulvdberge** [comment] 2016-11-13 23:34
To go ontopic, are you sure none of your storages are in *insert-only mode*?

Also, do the "deleted" items appear again if you break + replace the Controller?

**Comment by McSassyK** [comment] 2016-11-13 23:45
I'm sorry I forgot one detail.  When you have kids yelling in the background, dogs barking and a husband jabbering in your ear, it's easy to overlook something.
On topic, nothing is in insert-only mode. I just tried breaking and replacing the controller and that doesn't work. 
The bug seems random and doesn't happen every time. Sometimes it shows the same number of an item I put in, sometimes a few less (put in 30, only see 20), and sometimes the whole stack just vanishes.

Sent from Yahoo Mail on Android 
 
  On Sun, Nov 13, 2016 at 5:34 PM, Raoul<notifications@github.com> wrote:   
To go ontopic, are you sure none of your storages are in insert-only mode?

Also, do the "deleted" items appear again if you break + replace the Controller?

**Comment by KWAASone** [comment] 2016-11-15 14:21
I think I have possible the same issue discovered last Sunday. 
The Setup is:
1 Storage Controller 
1 Crafting Grit
64 External Storage Controller 
64 Quantum storage Units

First I place all external storage Interfaces then set 1 item in the Whitelist per Interface and attach the Quantum storage Unit. 
After filling The System with Items over the Grit some Items not visible.

On the external Storage Interface to the Quantum Storage Units contain the missing Items the Item count is zero in the Quantum Storage the Item count is correct.
On the external Storage Interface to the Quantum Storage Units contain the Items visible over the Grit the Item count is always 64 lover then in the Quantum Storage.

I have tested different ways to place the storage, set the external Storage Interface with filter and without filter.

At shows that if I have fewer or equal 64 Items in the Quantum storage I can`t see no Item in the Grit. If more than 64 Items in the Quantum Storage only the items more than 64 in the Grit.
Examples:
34 Items in Quantum Storage nothing in Grit/External Storage or on the external Storage interface.
34 in Quantum Storage add 16 Items (total 50) nothing in Grit/External Storage an 50 in Quantum Storage
34 in Quantum Storage add 50 Items (total 84) 20 Items in the Grit/External Storage Interface and 80 in Quantum Storage

It shows that’s the external storage Interface can`t detect the first Stack on each Quantum Storage.
The Items routed and stored correct but not visible in the Refined Storage Grit and the External storage interface.
I don’t know the issue is by Quantum Storage or Refined Storage.

Thanks for the very nice and useful mod. 

Hope this Help

Modpack FTB Lite 1.10 
Problem detected on FTBInfinityLite110-1.0.1-1.10.2 release 
Still happens after Update to FTBInfinityLite110-1.1.0-1.10.2 last Beta with the upgraded Refined Storage

Actual Version:
Refined Storage: 1.2.4
Quantum Storage: 1.10.2-3.2.7

**Comment by raoulvdberge** [comment] 2016-11-20 14:39
@McSassyK What kind of storage mediums are you using?

**Comment by McSassyK** [comment] 2016-11-20 23:35
Just the basics for the most part. Two disc drives, 16 4k storage disks, an external storage for bulk items. I also have a linked ender chest/bag hooked in. The bug seems to happen both when I input items directly into the system, and when I use the linked ender chest.

Sent from Yahoo Mail on Android 
 
  On Sun, Nov 20, 2016 at 8:39 AM, Raoul<notifications@github.com> wrote:   
@McSassyK What kind of storage mediums are you using?

**Comment by raoulvdberge** [comment] 2016-11-21 06:15
To what is the ext storage connected to?

**Comment by McSassyK** [comment] 2016-11-21 12:48
Just a couple of the four drawer storage drawers which are set up to only accept wood and cobble.

Sent from Yahoo Mail on Android 
 
  On Mon, Nov 21, 2016 at 12:15 AM, Raoul<notifications@github.com> wrote:   
To what is the ext storage connected to?

**Comment by BrewAndCode** [comment] 2016-11-29 20:38
McSassyK;   First and foremost; without the pertinent information, such as versions, etc. us developers can't tell what code to actually look at in order to help you regardless of whether it's this project, or another project, or hell even your car.  If you call the dealer and want to order tires do you think maybe the model and year of your car is important?  or do you just want them to order up whatever they want first.   And I'm pretty sure the dealer wouldn't be responsible for your kids or dogs in the background making noise.  

With that said I've experienced item deletion/duplication in forge 1.10.2 when just adding items to any sort of inventory be it chests, ender chests, or otherwise.  I narrowed it down to a really weird issue between JEI (Just Enough Items) and Inventory Sorting.  

When I was shift-adding many items from inventory into a chest, then closed/reopened those items were  neither in the chest nor in my inventory.  they were gone.  re-logging did not bring the items back.

On subsequent tests of the problem the items from my second row of player inventory were duplicated into  the first row of my inventory thus overwriting the contents there.  

I have since removed Inventory Tweaks and use the NEI version (which still relies on JEI) and no longer have these issues.

**Comment by McSassyK** [comment] 2016-11-29 23:05
Thank you for the explanation and for looking into the issue.
A little advice. I am an adult who has been in the workforce for over 35 years. When you choose a profession, as you have, that requires troubleshooting, you must conduct yourself with professionalism. That includes not responding rudely when someone reaches out to you for help. 
I understand it is frustrating. However, if you experience as many issues with having your form properly filled out as you previously indicated, perhaps you might consider making those fields required. This will eliminate frustration on both sides.
Otherwise, you should expect that people will omit information, and deal with it gracefully, courteously, and professionally.
Rudeness often begets rudeness. 
Just my two cents. Again, thank you for your hard work.
p.s. If my mechanic treated me rudely instead of simply asking the make and model of my car, I would certainly take my money elsewhere :)

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 29, 2016 at 2:38 PM, BrewAndCode<notifications@github.com> wrote:   
McSassyK; First and foremost; without the pertinent information, such as versions, etc. us developers can't tell what code to actually look at in order to help you regardless of whether it's this project, or another project, or hell even your car. If you call the dealer and want to order tires do you think maybe the model and year of your car is important? or do you just want them to order up whatever they want first. And I'm pretty sure the dealer wouldn't be responsible for your kids or dogs in the background making noise.

With that said I've experienced item deletion/duplication in forge 1.10.2 when just adding items to any sort of inventory be it chests, ender chests, or otherwise. I narrowed it down to a really weird issue between JEI (Just Enough Items) and Inventory Sorting.

When I was shift-adding many items from inventory into a chest, then closed/reopened those items were neither in the chest nor in my inventory. they were gone. re-logging did not bring the items back.

On subsequent tests of the problem the items from my second row of player inventory were duplicated into the first row of my inventory thus overwriting the contents there.

I have since removed Inventory Tweaks and use the NEI version (which still relies on JEI) and no longer have these issues.

**Comment by raoulvdberge** [comment] 2016-11-29 23:16
There is one thing you seem to be forgetting here: this is *NOT* my job or profession. This is a project I do in my free time and I don't get paid for any of this.

> you must conduct yourself with professionalism. That includes not responding rudely when someone reaches out to you for help. 

I must nothing. Like I said, you're making use of a mod entirely provided for free. I have no obligations to you.

>  However, if you experience as many issues with having your form properly filled out as you previously indicated, perhaps you might consider making those fields required. This will eliminate frustration on both sides.

These fields *are* required. That's why they are there. To fill them in.

**Comment by McSassyK** [comment] 2016-11-30 00:37
Thank you for explaining that it's okay to be rude if you're not getting paid. 
In that case, I will NOT be using the "donate" button on the website for the mod. 
Though I WILL continue to support content creators who understand the value of courtesy. 

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 29, 2016 at 5:16 PM, Raoul<notifications@github.com> wrote:   
There is one thing you seem to be forgetting here: this is NOT my job or profession. This is a project I do in my free time and I don't get paid for any of this.


you must conduct yourself with professionalism. That includes not responding rudely when someone reaches out to you for help.


I must nothing. Like I said, you're making use of a mod entirely provided for free. I have no obligations to you.


However, if you experience as many issues with having your form properly filled out as you previously indicated, perhaps you might consider making those fields required. This will eliminate frustration on both sides.


These fields are required. That's why they are there. To fill them in.

**Comment by Mason11987** [comment] 2016-12-09 16:51
"Though I WILL continue to support content creators who understand the value of courtesy. "

And you should be courteous that someone made a free mod for you to enjoy, and take a second to read the template so you aren't wasting their time.  Be less self-entitled.

**Comment by InThayne** [comment] 2016-12-10 01:34
Similar problem here with Infinity lite 1.10  using version 1.2.8 of RS.   Noticed Ei/o clear glass was disappearing when when placed in the grid.  Should route to storage drawers set on insert/extract with a higher priority of 1.  Controller break/place not a remedy.  Items are not appearing in any other inventory or upon  relog.

**Comment by ChaosTherum** [comment] 2016-12-14 15:36
I can also confirm the issue using version 1.2.11 I just noticed I have lost quite a few things hopefully this can be resolved luckily I'm in single player so I can respawn the items keep up the good work man.

**Comment by ExDomino** [comment] 2016-12-19 02:01
It could be a kind of rollback. We noticed on our server that Refined Storage did a rollback of its content yesterday. We lost a lot of redstone and some diamonds, and a lot of coal has been duplicated.

**Comment by PWTordenskiold** [comment] 2016-12-20 03:38
I have a suggestion that Refined Storage pokes holes in a bug that is caused by either Minecraft itself in regards to chunks or something that affects this(FTBU? Seen a lot of wierd behaviour from it). 
Reason I say this is because I see something similar with Ender IO and IC2. On built out worlds I see cables that span multiple chunks stop transferring power or items after unloading a chunk and entering it again. Fixing it requires breaking and replacing the cable. Seen the same with exporters that lets say transfers glowstone. Amount in system does not go up when items enter exporter, but breaking and replacing it makes item-count go up in the system.
This behavior is not consistent/easily replicated, but it gets worse as GC starts struggling after an hour or two. Restarting fixes it.

Is it possible that for instance an export bus is accepting the items and sending them into a void, while lets say Ender IO has a more thorough check that destination is accepting the items it wants to send beforehand?

**Comment by raoulvdberge** [comment] 2016-12-22 02:41
@PWTordenskiold That is what was happening I think... I changed the code to *always* get the tile when inserting or extraction, then we're sure it still exists in the form we think it is.

**Closed** 2016-12-22 02:40 UTC
Labels: bug

**Comment by JBBW** [comment] 2017-01-16 22:02
"In that case, I will NOT be using the "donate" button on the website for the mod. "
My suggestion if you do not appreciate the mod or the culture in which it was developed is that you stop using it altogether.  Biting the hand that's extended when you ask for help is rude.

Thank you raoulvdberge for your donations of time and skill.

**Comment by forrester-marc** [comment] 2017-02-20 18:12
Like Sassy was ever in danger of pressing a donate button.

**Comment by Horyo** [comment] 2020-05-02 16:32
my 2 cents is there was fouls on both sides here as much as i love wat you done with this mod you were a bit sarcastic but she should have responded back with sarcasm i as well am dealing with this same issue people are bring it to your attention to help you make a better mod as a mod dev not excatly fair to be pissed off with us when something goes bad in your code and you a bit annoyed with it anyways have fun all :)
