### ISSUE TITLE
Massive Recipe Crash

### ISSUE THREAD

**Issue by joelaw9** [raoulvdberge/refinedstorage#1096] opened 2017-03-26 19:59 UTC
#### Issue description:
When trying to calculate the requirements of a massive enough recipe, Refined Storage will use all the remaining RAM a server has to offer and crash the server. This happens after pressing cancel.

The specific interaction that caused this was calculating a tier 16 blood tank from Blood Magic 2 which requires 30^16 stone, 30^16 cobble, 10^16 blank slates, and a few other ^16 piecemeal items and recipes. But it's likely to happen for any sufficiently large recipes. 

I had already cancelled the calculation due to the amount of time it was taking, but it didn't respond to that and went through with filling up the RAM anyway. 

I expected the cancel to go through or for the RS system to catch such a runaway recipe before it crashed the server.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Refined Storage: 1.2.22

Does this issue occur on a server? Y

**Comment by SubsterNL** [comment] 2017-03-29 07:47
I +1 that. For 1.10.2. Latest version .25, Customized FTB Beyond 1.21

I have found that any larger crafting job will not only increase TPS dramatically on both client and/or server or just become almost unplayable. It is so bad I'm getting to the point again where I'm probably going to totally switch to AE2 again.

Unless refined storage shouldn't be used to craft 40 capacitor banks or anything larger.

**Comment by raoulvdberge** [comment] 2017-03-29 16:14
@SubsterNL I'm very close to banning you from the tracker. You don't have to go to 10 unrelated autocrafting issues to complain about your lag issue.

**Comment by raoulvdberge** [comment] 2017-03-30 17:55
Thanks for the report. I'll close this for now, since this is a duplicate of #838.

**Closed by raoulvdberge** 2017-03-30 17:55 UTC
