### ISSUE TITLE
excessive block updates caused by ExternalStorage

### ISSUE THREAD

**Issue by tomevoll** [raoulvdberge/refinedstorage#14] opened 2016-03-28 08:54 UTC
May want to change the code a bit so if no inventory can accept the item dont pull it out of the storage.
Im getting massive amount of blockupdates and excessive network trafic caused by items being pulled out then inserted back again when all targets are full

**Comment by tomevoll** [comment] 2016-03-28 13:35
it may be the exporter doing it as well

**Comment by raoulvdberge** [comment] 2016-04-03 22:37
I won't fix the root cause of this issue, but I will do another fix that should compensate this.

Will fix this by NOT sending GUI-only data when not needed.

**Comment by raoulvdberge** [comment] 2016-04-04 14:12
Fixed

**Closed by raoulvdberge** 2016-04-04 14:12 UTC
Labels: bug, feature request
