### ISSUE TITLE
Pattern rendering crash with GT wires

### ISSUE THREAD

**Issue by AGithub457** [raoulvdberge/refinedstorage#2271] opened 2019-06-25 00:43 UTC
#### Issue description:
Any pattern that has a GregTechCE wire in it crashes the game when pressing shift to render (or putting it in a crafter which also renders the item).
#### What happens:
Crash
#### What you expected to happen:
Expect to render properly?
#### Steps to reproduce:
1. Make any pattern with wires
2. Press shift to render the output (or put it in a crafter)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Refined Storage: 1.6.14

Does this issue occur on a server? Yes

#### If a (crash)log is relevant for this issue, link it here:
[Crash report 1](https://pastebin.com/hapLkp6G)
[Crash report 2](https://pastebin.com/PpeMN2zP)
[Crash image from VanillaFix](https://imgur.com/a/7gp1AqX)

It says its a GTCE issue with an incorrect CCL hook but I can't see how it can be that. If you can help me isolate the issue at least, or help me provide specifics if it's not an RS issue, that would be great!

**Comment by AGithub457** [comment] 2019-06-25 02:25
Update: I did some more testing, it happens with any kind of wire or cable being in the output. It works fine if it's in the input since its not the final item that renders.

**Comment by Tntdruid** [comment] 2019-07-01 13:29
Getting that crash too now.

Minecraft: 1.12.2
Forge: 14.23.5.2838
Refined Storage: 1.6.14

**Comment by Darkere** [comment] 2019-07-02 08:25
Duplicate of #2227

**Comment by Tntdruid** [comment] 2019-07-02 10:58
Did a test whit AE does not crash.

**Closed** 2019-07-02 17:16 UTC

**Comment by AGithub457** [comment] 2019-07-02 17:59
Hey @raoulvdberge can you explain why this isn't an RS issue? It looks like it is, especially a rendering issue on RS's end. I'm happy to be proven wrong.

**Comment by raoulvdberge** [comment] 2019-07-02 18:06
I'm not sure if it is or it is not. I don't have time at the moment to look into this.

**Comment by raoulvdberge** [comment] 2019-07-20 09:05
Discussion continues in #2227
