### ISSUE TITLE
Client performance issue with crafter.

### ISSUE THREAD

**Issue by CyaNox** [raoulvdberge/refinedstorage#340] opened 2016-09-14 22:27 UTC
http://cyanox.nl/refinedstorage_performancebug.png

The performance issue appears to be happening after opening and closing the Crafter GUI. The screenshot was taken after opening and closing just the 4 crafters in the screenshot. The performance issue goes away when relogging or when teleporting (or moving) away far enough for them to unload.

This issue appears to happen in everyone's bases so it is not localized to that specific setup.

- Minecraft: 1.10.2
- Forge: 12.18.1.2086
- Refined Storage: 1.0.2

**Comment by raoulvdberge** [comment] 2016-09-14 22:36
Are you able to provide a .nps file for me? If not, no problem because I think I know where the issue is but it would help.

**Comment by CyaNox** [comment] 2016-09-14 23:07
I currently do not know how to generate said .nps file. If it involves installing a JDK and running the already slow to start up client with a profiler attached ... I'm inclined to not want to do that. However if you can give me some simple steps to follow on how to "easily" generate said file I might be able to oblige.

**Comment by way2muchnoise** [comment] 2016-09-15 07:25
If you can share you mods, config and world. Then at least someone could generate it for you.

**Comment by raoulvdberge** [comment] 2016-09-16 07:15
Actually, can you downgrade to v1.0.0 and tell me if the issue is present there. If it isn't, I know immediatally whats going on.

**Comment by ilordnightmarei** [comment] 2016-09-17 01:49
yes it  is in 1.0.0

**Comment by raoulvdberge** [comment] 2016-09-17 10:45
@CyaNox If you want a fix for this, you'll need to give me a NPS file. I can't reproduce this. Start VisualVM when MC is already running and while the FPS lag is there, start a profiling session.

**Comment by CyaNox** [comment] 2016-09-17 11:48
Thank you for "teaching" me how I could generate a .nps file. I've had some major issues getting the "profiler" to actually run however the "sampler" seemed to work and here is a snapshot of the cpu sampling during the performance loss caused by the Crafter:

http://cyanox.nl/refinedstorage_sampler-cpu-snapshot.nps

I hope this is enough else I'd love to be taught instructions on how to not crash,lockup or otherwise incapacitate my JVM when trying to profile a memory hog of a minecraft instance.

**Closed** 2016-09-17 11:57 UTC
Labels: bug, performance

**Comment by raoulvdberge** [comment] 2016-09-17 12:01
Thanks for providing the NPS file, helped me fix the bug. A fix will be in the next version, to be released in a few minutes.

**Comment by CyaNox** [comment] 2016-09-17 12:04
Awesome!
