### ISSUE TITLE
Lost Items?!

### ISSUE THREAD

**Issue by ClockworkAnalog** [raoulvdberge/refinedstorage#1132] opened 2017-04-06 13:18 UTC
#### Steps to reproduce:
1.Have 8 full disks of items in a disk drive.
2.Add a Disk Manipulator to the network without the disks installed.
3.Install 1 new 64K disk
4. Use disk manipulator... 

That's all i did and now my sky-factory 3 game is on hold while i try to use chunk loaders to get all my resources back.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 8.99.99
- Refined Storage:1.2.22

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment] 2017-04-06 18:03
Unfortunately this is a Forge bug, see https://github.com/MinecraftForge/MinecraftForge/issues/3682

Duplicate of #821

**Closed by raoulvdberge** 2017-04-06 18:03 UTC
