### ISSUE TITLE
Crash with latest version  1.12

### ISSUE THREAD

**Issue by Madcock83** [raoulvdberge/refinedstorage#1506] opened 2017-10-27 14:10 UTC
#### Issue description:
Crash when entering any other dimension.
#### What happens:
I set up a small system.  I went to the nether and the end.  After 10 seconds or so game crashes.  And crashes again when relaunched. Unless you can Teleporte out before the 10 seconds.  Crash log points to refined storage.  I'm sorry I'm on my phone and don't have the log.  Will post in a few. I did however find a fix.  Chunk loading the area the system is in stopped the crash
#### What you expected to happen:
Not crash.
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge:
- Refined Storage: latest

Does this issue occur on a server? [yes/no]
haven't tried. Client only at this point
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
Again will post the rest of the info soon

**Comment by raoulvdberge** [comment] 2017-10-27 18:25
Please post your crash report

**Comment by Madcock83** [comment] 2017-10-27 18:33
My bad,  got busy at work

https://pastebin.com/W3xkScUb

**Comment by raoulvdberge** [comment] 2017-10-29 21:11
The problem is with an importer connected to a inventory. Said inventory has a "null" item assigned to it, which is not allowed and mods shouldn't handle that. So the implementor if that inventory or chest or whatever the importer is connected to has done it wrong.

**Closed by raoulvdberge** 2017-10-29 21:11 UTC
Labels: awaiting, bug
