### ISSUE TITLE
Issues with autocrafting an NBT sensitive items

### ISSUE THREAD

**Issue by KAHTOP** [raoulvdberge/refinedstorage#555] opened 2016-10-30 17:19 UTC
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.2.2111
- Refined Storage: **refinedstorage-1.2-beta4**

Autocraft still does not work with chargeable items, for example, with Energy Tablet, Energy Cubes from Mekanism.

@raoulvdberge , i wonder, whether it should have worked in this beta-release?
[My previous issue](https://github.com/raoulvdberge/refinedstorage/issues/455)

![image](https://cloud.githubusercontent.com/assets/22776271/19838324/c2314922-9edd-11e6-8af7-648b38023d92.png) => 
![image](https://cloud.githubusercontent.com/assets/22776271/19838329/df116cca-9edd-11e6-94ad-31c185ae46e9.png)

**Comment by InusualZ** [comment] 2016-10-30 17:22
You need to create the pattern manually, not from JEI

**Comment by way2muchnoise** [comment] 2016-10-30 17:23
Related to #509 and #532 . Autocrafting still has some issues with NBT sensitive items. It is in the works but not a high priority as you can either craft it step by step or manually (after requesting the parts). But it we will look at it for sure (might be for 1.2.1 though)

**Comment by KAHTOP** [comment] 2016-10-30 17:29
@InusualZ thank you, i'll try it.

@way2muchnoise ok, got it, thank you.

**Comment by raoulvdberge** [comment] 2016-10-30 19:40
This is a duplicate of #509

**Closed by raoulvdberge** 2016-10-30 19:40 UTC
Labels: autocrafting, bug
