### ISSUE TITLE
Crash attempting to autocraft IC2 Auto Pulling upgrade

### ISSUE THREAD

**Issue by varukasalt** [raoulvdberge/refinedstorage#580] opened 2016-11-05 00:22 UTC
#### Issue description:  
Game crashes when starting autocrafing of IC2 Autopulling upgrade

#### What happens:  
Game crashes

#### What you expected to happen:  
Expected autocrafting system to cough up an IC2 pulling upgrade

#### Steps to reproduce:  
1. Request IC2 Autopulling upgrade
2. Hit start
3. Game crashes
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage: 1.2

Does this issue occur on a server? [yes/no] unknown

#### If a (crash)log is relevant for this issue, link it here:

http://pastebin.com/NmaNbbgA

**Comment by watersunsink** [comment] 2016-11-05 07:35
I made an account to report a bug for the first time, so I don't know what I'm doing and I'm not sure if I'm supposed to comment here or to post my own separate thread, but I'm similarly having issues with my game crashing when attempting to autocraft various IC2 recipes in Refined Storage.

For example I just attempted to autocraft a treetap and it forced my game to crash - here's the log for it:
https://paste.ee/p/k7XpD

Sorry if this comment doesn't belong here.

**Comment by way2muchnoise** [comment] 2016-11-05 08:02
Duplicate of #578 will be included in 1.2.1. Best way to fix it right now is to remove the controller with some program like [MCEdit](http://www.mcedit.net/)

**Closed** 2016-11-05 08:02 UTC
Labels: autocrafting, bug, duplicate, fixed indev
