### ISSUE TITLE
[1.15.2] crafting monitor crash while viewing crafting recipes that make use of crafting cards

### ISSUE THREAD

**Issue by koalalord9999** [raoulvdberge/refinedstorage#2530] opened 2020-05-23 16:14 UTC
#### Steps to reproduce:
1. Will post a video of what happens
2. And how to set it up yourself
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: not sure, will update later
- Refined Storage: 1.8.3

Does this issue occur on a server? Yes

#### If a (crash)log is relevant for this issue, link it here: server crash I don’t have access to the logs

[pastebin/gist/etc link here]

**Comment by Darkere** [comment] 2020-05-23 16:26
Duplicate of #2508

Fixed in dev

**Closed** 2020-05-23 22:46 UTC
