### ISSUE TITLE
Autocrafting works once then breaks

### ISSUE THREAD

**Issue by NicosaurusRex99** [raoulvdberge/refinedstorage#1442] opened 2017-09-02 07:13 UTC
#### Issue description:
I automated the crafting of crafters  in a normal way but it can only craft one item and then i have to remove all patterns for it to fix.
#### What happens:
Auto-crafting just stops
#### What you expected to happen:
Auto-crafting to continue
#### Steps to reproduce:
1. Place crafter
2. Added multi stage recipes
3. Clicked craft more than one
Watch video 
https://youtu.be/NlT4vNr4yIA

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 14.21.1.2443
- Refined Storage: 1.5.17

Does this issue occur on a server? [yes/no]
Unsure

###Game log
https://gist.github.com/NicosaurusRex99/9aee6333c901c98b56eacf3ecc62e1a4

**Comment by raoulvdberge** [comment] 2017-09-02 12:22
Duplicate of #1357

**Closed by raoulvdberge** 2017-09-02 12:22 UTC

**Comment by NicosaurusRex99** [comment] 2017-09-03 07:48
oh soz i didnt see 1357
