### ISSUE TITLE
Multistep crafting recipes not working.

### ISSUE THREAD

**Issue by dovahkiin4991** [raoulvdberge/refinedstorage#971] opened 2017-02-08 23:49 UTC
#### Issue description:
When I request a Herculean or Gargantuan Flux Storage from FluxNetworks, the crafting process will only show the individual recipe for each item even though I have the ability to auto craft all the part, for example to craft the Gargantuan you need 6 Herculean Flux Storage's, and to craft the Herculean you need 6 Basic Flux Storage's, but it wont show any further than it needed 6 Herculean. The crafters are connected and I have all the resources but It still wont show the full crafting process needed.
#### What happens:
When force requested it cant proceed, even after canceling and trying again.
#### What you expected to happen:
The system to show the full crafting process because I have the patterns in the crafters and its a basic crafting recipe.

#### Version (Make sure you are on the latest version before reporting):
Skyfactory 3, by FTB Team
- Minecraft: 1.10.2
- Forge:
- Refined Storage: 1.2.18

Does this issue occur on a server? [yes/no]
No
#### If a (crash)log is relevant for this issue, link it here:
None
[pastebin/gist/etc link here]

**Comment by dovahkiin4991** [comment] 2017-02-09 00:02
Ive found a temporary way around this by changing them to processing patterns and putting it into a crafter from rf tools but I don't want to keep that setup long term

**Comment by nathreed** [comment] 2017-02-11 13:40
I experience this issue on a server as well. Same MC and mod versions.

**Comment by way2muchnoise** [comment] 2017-02-12 15:59
Duplicate of #895, fixed in 5348393a1dbc93dfacafad55c41b8ac982385815. All you need to do is update RS.

**Closed by way2muchnoise** 2017-02-12 15:59 UTC
