### ISSUE TITLE
Server hard lock on Refined storage- net.minecraft.util.math.Vec3i.equals

### ISSUE THREAD

**Issue by ProsperCraft** [raoulvdberge/refinedstorage#2068] opened 2018-10-31 15:49 UTC
#### Issue description:
My FTB Sky Adventures server locked hard, warmroast and sampler stall reports show refined storage.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2770
- Refined Storage:  refinedstorage-1.6.5.jar

Does this issue occur on a server? YES

#### If a (crash)log is relevant for this issue, link it here:
Warmroast image
![refinedstorage](https://user-images.githubusercontent.com/4427684/47800263-9338c380-dcf1-11e8-9b46-6959a9426427.png)

Stall report from sampler-
https://gist.github.com/ProsperCraft/9ab04dd6c73fd45f45d1b1733d8b9ae5

Latest logs-
https://gist.github.com/ProsperCraft/e59055322620d89b175890bb005a702b

Debug log, and more stall logs- 
[refinedstorage.zip](https://github.com/raoulvdberge/refinedstorage/files/2535193/refinedstorage.zip)

**Comment by raoulvdberge** [comment] 2018-10-31 16:02
No idea what's causing that. Server stalls also aren't really helpful. Perhaps, a system is constantly turning on and off? Did you check that?

**Comment by ProsperCraft** [comment] 2018-10-31 17:18
Another server lockup-
Warmroast
![5645d157d5097119aec66daa91d02809](https://user-images.githubusercontent.com/4427684/47806129-9d14f380-dcfe-11e8-873a-23093d869f09.png)

**Comment by raoulvdberge** [comment] 2018-10-31 17:34
could you check if an RS system is constantly turning on and off please

**Comment by KingDan27** [comment] 2018-11-02 18:38
This also happened on my servers. Had to remove the mod from the pack until it’s fixed. Not sure how you’d like us to see if it’s a system turning on and off when it’s locked up. Any suggestions.

**Comment by raoulvdberge** [comment] 2018-11-02 20:11
Can you try uninstalling reborn storage

**Comment by ProsperCraft** [comment] 2018-11-02 22:40
I zipped the server that was doing it on boot if you want me to send it to you so you can run tests with it.

**Comment by ProsperCraft** [comment] 2018-11-02 22:41
I resolved it on my server by doing this- whitelisted the server, turn it on without refined storage and its dependant mods, then shut down, and started back up with them re-enabled, it wiped the problematic systems from my map that were illegally chunklloaded somehow.

**Comment by raoulvdberge** [comment] 2018-11-02 22:59
I just wish you could answer my questions.

**Comment by ProsperCraft** [comment] 2018-11-03 02:43
could you check if an RS system is constantly turning on and off please- 
No, we have 330 users, I have no idea what system was causing the problem, I am unable to comply I am sorry.

Can you try uninstalling reborn storage- I fired up the instance I zipped up for you on a new port without Reborn Storage.
These blocks were removed -
 
Missing minecraft:blocks:
    rebornstorage:multicrafter
Missing minecraft:items:
    rebornstorage:storagepart
    rebornstorage:storagecell
    rebornstorage:multicrafter
    rebornstorage:storagecellfluid

more then 1800 lines of - 
[14:38:25] [Server thread/WARN] [minecraft/TileEntity]: Skipping BlockEntity with id minecraft:reborn storagetilemulticrafter

With all of those removed, it doesn't seem to be locking up, and running at 20 tps.

**Comment by raoulvdberge** [comment] 2018-11-03 09:55
So with reborn storage removed, the problem is gone?

**Comment by Magesw** [comment] 2018-11-20 05:47
> So with reborn storage removed, the problem is gone?

I would say yes and no, removing Reborn storage stopped the lockup upon server start and the random lockups during play but the soft lockups were still going on even with only 1-2 online, I have now removed Refined Storage completely since removing Reborn Storage wiped by Refined Storage inventory anyways. Will update later as to if that solves it or not.

**Comment by raoulvdberge** [comment] 2019-07-21 17:57
Closing this issue as it's really old and with RebornStorage being updated a few times, the issue might be gone. If it still persists feel free to create a new issue.

**Closed** 2019-07-21 17:57 UTC
Labels: Performance

**Comment by LemADEC** [comment] 2019-07-22 00:06
Issue was still live a couple months ago, it's visible on large crafting multi-blocks, especially when overlapping chunk borders.

**Comment by Darkere** [comment] 2019-07-22 08:07
It should have gotten better. I made that call happen much less often about 2 months ago.

**Comment by LemADEC** [comment] 2019-07-22 09:05
Have we confirmed the fix on ProsperCraft backup world?

**Comment by ProsperCraft** [comment] 2019-07-23 22:44
We quit hosting this pack ages ago.  But would be super happy to test it on my 1.14.4 modpack 
https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk
