### ISSUE TITLE
Stackable Item dupe with interface import and extract only storage available

### ISSUE THREAD

**Issue by ChickenDuck** [raoulvdberge/refinedstorage#1068] opened 2017-03-17 11:06 UTC
#### Issue description:
When ALL the storage is in extract only mode, stackable items in the interface import slot will delicate itself. 
It does not happen when item quantity = 1 OR stack upgrade is present.

#### What happens:
Items with quantity >= 2 will keep duplicating itself until reaching a negative integer

#### Steps to reproduce:
1. Setup show in pic (1 controller, 1 item interface, 1 storage block AND/OR other equivalent storage)
![2017-03-17_17 51 47](https://cloud.githubusercontent.com/assets/8293704/24038588/05401196-0b3d-11e7-8611-3744059b93e4.png)
2. Set all the storage to Extract Only mode
3. Put any stackable items with quantity >= 2 into the interface import slot
4. Harvest your eggs
![2017-03-17_18 52 23](https://cloud.githubusercontent.com/assets/8293704/24040135/e4fab386-0b42-11e7-9dbe-fd1a043b86eb.png)

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2185
- Refined Storage: 1.2.23

Does this issue occur on a server? 
unknown, tested on single player only

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment] 2017-03-17 16:02
Duplicate of #892

**Closed by raoulvdberge** 2017-03-17 16:02 UTC
