### ISSUE TITLE
Disk drives disappear 1.11.2

### ISSUE THREAD

**Issue by seba84** [raoulvdberge/refinedstorage#1194] opened 2017-04-30 14:24 UTC
#### Issue description:
Disk drives disappear i think its connected to issue #986 

#### What happens
I dont know if its a crash or server restart but after one of those the disks are gone from the disk drive.
this is the second time it happend , I was thinking that first time was a random bug, but after second time in 2 weeks, its a problem.
edit : 
after more checking its not only the disk drives that disapear but also the crafting patterns, speed upgrades. network cards...
#### What you expected to happen:
disks don't disappear
#### Steps to reproduce:
i cant tell how to reproduce since i don't know the precise time , i can only guess that it had something to do with a server restart or a crash.

...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 1.11.2-13.20.0.2265-universal
- Refined Storage:  refinedstorage-1.4.2

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:

i dont know if it can help but this is the last  crash log  before the disks went missing
i can provide the server log if it can help.

[crash-2017-04-30_15.28.23-server.txt](https://github.com/raoulvdberge/refinedstorage/files/966782/crash-2017-04-30_15.28.23-server.txt)

Also the server log when the bug happened:

[log.zip](https://github.com/raoulvdberge/refinedstorage/files/966800/log.zip)

**Comment by raoulvdberge** [comment] 2017-05-05 16:08
Duplicate of #986
Please check previous issue and contribute there before making new ones

**Closed by raoulvdberge** 2017-05-05 16:08 UTC
