### ISSUE TITLE
[1.12.2] Grids has stopped working, no way to get them working back again!

### ISSUE THREAD

**Issue by ExDomino** [raoulvdberge/refinedstorage#2338] opened 2019-10-30 20:06 UTC
#### Issue description:

Grids stop working and not showing any items. It occurs randomly and there is no way to fix that. Replacing the core, the disk drive or the disks, etc, are not effective to solve the problem. The first time the bug occured, the only way is has to fix that is to restart the whole server. But now, even with a restart, there is no way to restore the access of my items. It's dead!

**Edit:** You have to restart the server AND the client in order to fix that bug!

#### What happens:

The grid appear empty exactly like no disk are present or all of them are empty.

#### What you expected to happen:

See the inventory as usual.

#### Steps to reproduce:

Unknown. Maybe breaking a cable or change the network setup can help to reproduce the bug.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.14.2
- Forge: 2847
- Refined Storage: 1.6.15

Does this issue occur on a server? Yes

#### If a (crash)log is relevant for this issue, link it here:

There is no crash log available.

**Comment by ExDomino** [comment] 2019-10-30 20:11
Same issue of this one, except 1.6.15 is also bugged:
https://github.com/raoulvdberge/refinedstorage/issues/2279

**Comment by Darkere** [comment] 2019-10-30 20:13
Check through #2327 and  #2326

**Comment by raoulvdberge** [comment] 2019-11-11 21:23
Are you actually on MC 1.14.2? You mention RS 1.6.15.

**Comment by raoulvdberge** [comment] 2019-11-11 21:23
If you are on MC 1.12.2, this is a duplicate of the other issues mentioned.

**Closed by raoulvdberge** 2019-11-11 21:23 UTC

**Comment by NisusAlcanta** [comment] 2022-11-13 02:01
I had the same problem. Really wishing I used AE2 like I always do. 🤦
