### ISSUE TITLE
Refined storage odd behavior (Chunkloading issue)

### ISSUE THREAD

**Issue by bsaksida** [raoulvdberge/refinedstorage#681] opened 2016-11-26 14:25 UTC
#### Issue description:
Sometimes i have to break controler or any other machine and place it again to work. This happens' because i do not have any means to create item to chunk load. From extra utilitites 2 i could create chunk loader wand, but its verry anoying to create.

#### What happens:
When going too far out or going to the nether, so that my base gets chunk unloaded. After getting back, some machines doesn't work, untill i break them and replace them.

#### What you expected to happen:
When getting back into a base, the system should be ready to use

#### Steps to reproduce:
1. Build RS system
2. Go To Nether. RS system need to be chunk unloaded
3. get back
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2124
- Refined Storage: 1.2.6

Does this issue occur on a server? [yes/no]
yes

**Comment by raoulvdberge** [comment] 2016-11-26 22:57
This is a duplicate of #370

**Closed by raoulvdberge** 2016-11-26 22:57 UTC
