### ISSUE TITLE
[Suggestion] Ignore NBT switch for patterns

### ISSUE THREAD

**Issue by TheK0tYaRa** [raoulvdberge/refinedstorage#2526] opened 2020-05-18 22:19 UTC
How about that? It solves a lot of issues with recipes that have charge-able items or similar.
Switch could be placed in the Pattern Grid with two others.

**Comment by Darkere** [comment] 2020-05-18 23:36
Duplicate of #565

This is unfortunately not as easy as it sounds. Mainly because NBT is a lot more than just metadata about an item. 2 items with different NBT values could have completely different uses.

**Closed** 2020-05-19 00:42 UTC
