### ISSUE TITLE
Full RS storage system cause item and stack(s) overflow

### ISSUE THREAD

**Issue by soerenkk** [raoulvdberge/refinedstorage#1018] opened 2017-02-25 21:18 UTC
#### Issue description:
This seems like a bug, and yet it doesn't (see the screenshots).

#### What happens:
Well my storage drives and other storage have been full for a while now, but I can kep inserting and extracting stuff to and from the system. It seems the SAG Mill push the processed materials out, but the RS system rejects it, and puts it back into the SAG Mill's output slot, which tricks the setup to keep pushing more materials to process.

#### What you expected to happen:
The system to hold, since the output slot is full, when the RS storage have no where to store the items.

#### Steps to reproduce:
I am using Ender IO's SAG Mill's that is pushing their output to a RS Interface.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2234
- Refined Storage: 1.2.22
- Sky Factory 3: 3.0.7

#### Does this issue occur on a server? [yes/no]
No.

#### Screenshots:

Interface:
[imgur.com](https://imgur.com/a/GNmzg)

* The SAG Mill output slots was similar, but the screenshot is gone and now it have cleared up, so cant take a new one.

**Comment by soerenkk** [comment] 2017-02-26 09:49
Just noticed this as well when I look in the Disk Drive.

[imgur.com](https://imgur.com/a/oY269)

**Comment by soerenkk** [comment] 2017-02-26 10:20
Tried to empty the drives. The result of that is that after a bit of time, my FPS drops to below 0, and the game is almost unplayable.  Tried to break the RS Controller as you suggested on another issue. That only made it worse and now it is completely unplayable, I cannot open GUI or interact at all, properly because of the delay :'(

**Comment by raoulvdberge** [comment] 2017-02-26 12:12
That crash is a JourneyMap crash. I will look into the interface issue

**Comment by raoulvdberge** [comment] 2017-02-26 12:12
But this is a duplicate of #1012

**Closed by raoulvdberge** 2017-02-26 12:12 UTC
