### ISSUE TITLE
Crash On The Pattern Grid

### ISSUE THREAD

**Issue by enderking470** [raoulvdberge/refinedstorage#2448] opened 2020-03-06 16:47 UTC
Mini Crash When Scrolling On Items In The Pattern Grid

Game Crashes

The Inventory To Scroll

It Occured When Mouse Tweaks Was Installed. Scrolling On Any Item In The Crafting Table Part Of The Grid.

1.6.15

- Minecraft:
- Forge:
- Refined Storage:
- Mouse Tweaks

Does this issue occur on a server?  Unsure

**Comment by Darkere** [comment] 2020-03-06 16:58
Duplicate of #2436

**Closed** 2020-03-06 21:03 UTC
