### ISSUE TITLE
RS External Storage and ExU2 Porcupines Too Much Tick Time Consumed

### ISSUE THREAD

**Issue by everseeking** [raoulvdberge/refinedstorage#2144] opened 2018-12-25 01:24 UTC
#### Issue description:
2 Ender Porcupine blocks are eating up a **_huge_** amount of tick time causing a large amount of ticks being continuously skipped. [Thread dump appears to be](https://i.imgur.com/b4EHfNX.png) between them and Refined Storage (reporting here also - don't know which mod needs fixed)

#### What happens:
Combination of mods is eating up *way* too much tick time ([simple entity profiling](https://i.imgur.com/40lEl2W.png)) without a large flow of items.

#### What you expected to happen:
Be more efficient (again, don't know if this is ExU, RS, or both).

#### Steps to reproduce:
1. Connect RS External Storage to ExU2 Porcupine machine/interface
2. Profit?

#### Version (make sure you are on the latest version before reporting):

- Minecraft: **1.12.2** Direwolf20 v. 2.4.0
- Forge: `forge-1.12.2-14.23.5.2772-universal.jar`
- Refined Storage: `refinedstorage-1.6.9.jar`
- ExU2 (if needed): `extrautils2-1.12-1.9.8.jar` ([latest released](https://minecraft.curseforge.com/projects/extra-utilities/files))

Does this issue occur on a server? [yes/no]
Yes

#### If a (crash)log is relevant for this issue, link it here:

* [Thread dump](https://i.imgur.com/b4EHfNX.png)
* Relevant [ExU Github issue cross-link](https://github.com/rwtema/Extra-Utilities-2-Source/issues/251)

#### Things to note:
* This *may* be relevant to an improvement in RS 1.6.10
`Slightly increased performance of the External Storage (raoulvdberge)`

_If fixed by just updating mod, I apologize for wasting your time._

May also be related to https://github.com/raoulvdberge/refinedstorage/issues/773

**Comment by raoulvdberge** [comment] 2019-07-21 17:59
Duplicate of #2093

**Closed by raoulvdberge** 2019-07-21 17:59 UTC
Labels: Performance
