### ISSUE TITLE
[1.12.2] Autocrafting tasks stop when switching dimensions

### ISSUE THREAD

**Issue by Paril** [raoulvdberge/refinedstorage#1662] opened 2018-02-09 03:15 UTC
If I switch dimensions, any autocrafting tasks seem to stop where they were, even if I'm moving to a dimension where the controller is reaching it (Compact Machines, for instance, which are connected via Cables and are still doing their jobs inside there). The main controller block is chunkloaded & still providing power, etc to the rest of the world.

**Comment by ineternet** [comment] 2018-02-09 12:22
Tried this in 1.5.31 and 1.5.32, on a server and not, both times with a chunkloaded system. Can not reproduce. What version/s are you using?

**Comment by Paril** [comment] 2018-02-09 15:56
1.5.31 currently. I'm really not sure what's causing this one. Generally it seems to happen if I'm the only one on the server and I go into a Compact Machine; when I come back out, my large autocrafting tasks are just gone.

**Comment by Paril** [comment] 2018-02-09 17:07
This isn't something I can reproduce 100% of the time either, there seems to be a very specific catalyst to this happening. Is there any way to turn on verbose info for crafting? That'd be handy for cases like this.

https://streamable.com/04t3w

I had to do this a few times, finally caught it on recording though. The first few times it didn't happen, then when I stopped recording and went to The End it happened again.

**Comment by Paril** [comment] 2018-02-10 06:31
So, I thought as an experiment I'd bring a Crafting Monitor into another dimension to see what happens. I started a long crafting task (a bit of a simpler one, but basically doing Cauldrons; each require 5 Steel Plates, so Iron and Coal Dust is sent to Induction Smelter to make the steel and then sent to two Compactors to do parallel Steel Plates, and then finally my large collection of Crafters in another CM handles regular crafting recipes) and wandered into a Compact Machine.

I watched the task go, and for about a minute it was working fine, I could see steel being inserted. It was down to 200-some Steel left, then it jumped up to 381 remaining, stood for a second on "Machine in Use", then the entire task just disappeared. No message, nothing.

**Comment by raoulvdberge** [comment] 2018-02-17 21:55
@Paril  Does this only happen with Compact Machines for you?

**Comment by Paril** [comment] 2018-02-18 14:41
No, it happens if I go to The End as well as the video shows.

**Comment by raoulvdberge** [comment] 2018-05-26 13:26
I cannot reproduce this. Closing

**Closed by raoulvdberge** 2018-05-26 13:26 UTC
Labels: bug, can't reproduce, investigate
