### ISSUE TITLE
[1.12.2] Import Bus Crash

### ISSUE THREAD

**Issue by YOYOK9** [raoulvdberge/refinedstorage#1589] opened 2017-12-24 19:15 UTC
#### Issue description:
Placing an import bus seems to crash client on multiplayer
#### What happens:
One of my players was placing an import bus connected to a create (i believe) from Actually additions for the first crash and a Mystical Agriculture furnace for the second
#### What you expected to happen:
Suck items out of the adjacent block
#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.1.2573-universal  (not latest do to mod issues)
- Refined Storage: 1.5.29

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:
1) https://pastebin.com/md5QDbJR
2) https://pastebin.com/xVTwpP9t

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment] 2017-12-24 19:33
Oh shit, that shouldn't happen. A temporary workaround is to install mcmultipart. I will look into it tomorrow, I'm at a Christmas party now.

**Comment by YOYOK9** [comment] 2017-12-24 19:38
Sounds good. Honestly didn't even expect a response till after christmas XD Happy holidays

**Comment by raoulvdberge** [comment] 2017-12-24 22:08
Duplicate of #1587

**Closed by raoulvdberge** 2017-12-24 22:08 UTC
Labels: bug

**Comment by raoulvdberge** [comment] 2017-12-25 00:11
Fixed in 1.5.30! You too have a good one!
