### ISSUE TITLE
Delay when opening system

### ISSUE THREAD

**Issue by mika1369** [raoulvdberge/refinedstorage#1041] opened 2017-03-07 15:26 UTC
#### Issue description: 
Delay / "Lag" when opening system

@way2muchnoise mentioned in #641 that some profiling information could be useful, is this also the case here?

#### What happens: 
when I right click any of the grids (Fluid and wireless not tested as I do not have them yet)

#### What you expected to happen:
Early game they opened instantly, I have 120k items in the system, so could easily simply be that it loses performance as the number of items increase.

#### Steps to reproduce:
1. right click a grid
2. move the mouse, screen will still move around a second or two
3. GUI opens
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2234
- Refined Storage:1.2.22

Does this issue occur on a server? [yes/no]
I would assume so, though i have only used the mod in singleplayer

#### If a (crash)log is relevant for this issue, link it here:
I am not sure any logs would help, please do let me know if any are wanted

**Comment by raoulvdberge** [comment] 2017-03-07 15:54
Can you make a video of this?

**Comment by mika1369** [comment] 2017-03-07 17:05
I should be able to.

Ill let you know in just a bit if i can get my software to cooperate

**Comment by raoulvdberge** [comment] 2017-03-07 17:07
Cool. Do you have any other lag issues in your world? Or is it just the grid opening slowly?

**Comment by raoulvdberge** [comment] 2017-03-07 17:07
It shouldn't lose perf with more items, since it's just an item count increase. Nothing special. What external storages do you have connected to RS?

**Comment by mika1369** [comment] 2017-03-07 17:10
I have some issues with actually crashing due to (I believe anyhow) lag when i fly around fast in RFtools dimensions.

And sometimes every minute or so theres a strange "Stutter" like a lagspike but quite short

This is in the latest skyfactory 3 release by the way.

Also, no external storage, only a disk block with 8 64k disks, 5 of them were added just before i stopped playing yesterday, so only the first 3 are in use.

**Comment by mika1369** [comment] 2017-03-07 17:16
Nvidia showdowplay is acting up, ill grab some dinner and come fiddle with it afterwards, should have a video done in an hour or so.

**Comment by raoulvdberge** [comment] 2017-03-07 17:38
Cool, thanks. Is the stutter you're having a lag stutter (server not responding) or FPS stutter?

**Comment by mika1369** [comment] 2017-03-07 17:42
Im not sure, how would i tell?

**Comment by raoulvdberge** [comment] 2017-03-07 17:43
Does Minecraft hang for a few seconds or is there lag when placing blocks or opening GUIs?

**Comment by mika1369** [comment] 2017-03-07 17:51
More like just a instant screen freeze, not really enough to annoy me, but enough so that i notice.


Aparently shadowplay makes very big files, so just put it on youtube
https://youtu.be/lA3ACRxR_X8

**Comment by raoulvdberge** [comment] 2017-03-07 17:59
That screen freeze seems like another issue. But the grid issue is interesting. Which pack is this, and can you send me a world download? I'll have to investigate this locally in a dev environment.

**Comment by mika1369** [comment] 2017-03-07 18:11
Latest skyfactory 3 from the curse launcer, the beta version .7 i think it is.

World download was around 160 mb, and zipping only got it down to 16, so had to put it on dropbox, as githup only accepts 10
https://www.dropbox.com/s/2nw8ins0sgy56tv/Low%20Stress.zip?dl=0

**Comment by raoulvdberge** [comment] 2017-03-07 19:18
Thanks. I'll take a look at it tomorrow.

**Comment by mika1369** [comment] 2017-03-07 20:13
Thanks. Do let me know if you end up needing anything else.

**Comment by mika1369** [comment] 2017-03-09 14:54
Sorry for prodding, just wanted to ask if you had a chance to look around in the save?

**Comment by raoulvdberge** [comment] 2017-03-09 16:41
Not yet.

**Comment by rYanGap** [comment] 2017-03-20 21:42
I'm having the same exact issue with my Refined Storage system. I had no issues with older versions of RS, but the new versions cause extreme lag when opening a grid. Here's a video to demonstrate the issue. https://www.youtube.com/watch?v=VUnEgZCzfTg

**Comment by L0laapk3** [comment] 2017-03-28 17:35
I don't want to be annoying, but this issue renders the recent updates of the mod completely unplayable. Had a chance to look at this yet? :(

**Comment by raoulvdberge** [comment] 2017-03-28 17:45
Sorry, but you're being annoying. I'm on a vacation.

**Comment by KaneHart** [comment] 2017-04-20 09:13
Wish I got that much vacation time. May I ask where I sign up?

**Comment by raoulvdberge** [comment] 2017-04-20 14:06
Nowhere. Perhaps show some respect.

**Comment by KaneHart** [comment] 2017-04-20 18:27
Well damn I was looking forward to my new job. Either way I give people who earned respect the respect they deserve. I was for sure no disrespecting you. I don't have RS I'm considering it right now for me pack. I was just checking this out and I saw this vacation thing and I thought what a perfect time to lighten the mood.

**Comment by rYanGap** [comment] 2017-05-01 19:41
Is there any update on this issue? Probable causes, workarounds?

**Comment by raoulvdberge** [comment] 2017-05-01 20:03
No updates on this one.

Probable cause: item with too complex NBT in the system.
Workaround: remove the item with too complex NBT in the system.

**Comment by rYanGap** [comment] 2017-05-02 02:16
I'll try removing all armor and weapons that have a damage value attached. What other items would have complex NBT?

**Comment by LemADEC** [comment] 2017-05-02 07:28
All highly customized items like enchanted ones, portable containers, tinker's tools, etc.

**Comment by masshuru** [comment] 2017-05-05 13:54
I had this same issue over the past few days, until I ended up seeing over 12000ms lag spikes whenever I opened a grid.  After seeing this thread, I exported all of the bows, weapons, and armor (many enchanted) my mob farm had collected into a trash can and now my grid access is quite responsive.  Thanks for the tip about complex NBT items creating issues with RS, and thanks for a great mod!

**Comment by rYanGap** [comment] 2017-05-09 01:29
I had hundreds of pieces of leather armor and stone swords from a mob farm in my system. The weirdest thing happened--the damaged stone swords can no longer be removed from the system. They seem stuck in the drives. I can't even use an exporter to get rid of them. Anyone face this issue?

**Comment by rYanGap** [comment] 2017-05-09 03:59
I've found out some more info about this issue--I destroyed nearly all complex NBT items from my inventory, but still had about 4-5 seconds of lag upon opening the grid. I disconnected all of my crafters with patterns, and that further reduced lag to less than 1 second upon grid opening. I have about 1200 patterns stored in my Refined Storage system, so that might help diagnose the problem.

**Comment by raoulvdberge** [comment] 2017-05-09 08:42
@rYanGap Is this 1.11?

**Comment by masshuru** [comment] 2017-05-09 13:52
Also, I had to power cycle my grid to clear out a number of items that had been exported but still were showing up in the grid, which cleared a lot of lag.  This is still in SF3, so 1.10.

**Comment by rYanGap** [comment] 2017-05-09 22:24
> @rYanGap Is this 1.11?

I'm in a 1.10.2 modpack which is running the latest release version, Refined Storage 1.2.25. I haven't tried it with any of the beta versions.

**Comment by raoulvdberge** [comment] 2017-05-24 20:22
The cause of this has been identified as #1041.

Closing because that issue is more relevant.

**Closed by raoulvdberge** 2017-05-24 20:22 UTC
Labels: performance
