### ISSUE TITLE
[1.12.2] Compatability issue with Storage Drawers

### ISSUE THREAD

**Issue by wlsnbilyb** [raoulvdberge/refinedstorage#2358] opened 2019-11-25 20:45 UTC
#### Issue description:
Using an external storage bus on a drawer controller from Storage Drawers works until relogging into the game, upon which the items disappear from the system and require the connection between the storage bus and the refined storage controller to be reset, upon which it returns to normal. (Modpack is FTB Revelations)

#### What happens:
Items disappear from system upon logging out and then back into the game

#### What you expected to happen:
Not that

#### Steps to reproduce:
1. Connect refined storage system to a drawer controller with an external storage item (currently set to priority 10, not sure if that matters)
2. Log out of game and back in
3. Break and replace cable between controller and external storage item to reset connection and temporarily fix issue

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: forge-14.23.5.2846
- Refined Storage: 1.6.15

Does this issue occur on a server? [yes/no]
No

#### If a (crash)log is relevant for this issue, link it here:

Does not cause a crash

**Comment by wlsnbilyb** [comment] 2019-11-25 21:04
Also not sure if this is relevant but the external storage bus is displaying that it is storing about 115k items out of a "max" 1.1k and that it is 9983% full. Possible this is causing/caused by the issue.

**Comment by Darkere** [comment] 2019-11-25 21:35
This is caused by FTBU chunkloading try another chunkloader or force a blockupdate for the drawercontroller on worldload.

The display is completely unrelated and can be safely ignored. It is only visual and has no impact on any functionality. It happens because the drawer controller doesn't properly report what it is storing. 

Duplicate of #2120

**Closed** 2019-11-25 21:46 UTC
