### ISSUE TITLE
Ticking block entity NullPointerException server crash

### ISSUE THREAD

**Issue by joelaw9** [raoulvdberge/refinedstorage#1125] opened 2017-04-02 20:45 UTC
#### Issue description:
The server crashed while no one was online and then crashed on startup due to "NullPointerException: Ticking block entity". The solution was to use NBTEditor to directly access the relevant entity and delete it from the world. The entity was a controller.

#### Version (Make sure you are on the latest version before reporting):

Minecraft: 1.10.2
Forge: forge-1.10.2-12.18.3.22.54
Refined Storage: 1.2.22

Does this issue occur on a server?  Y

#### If a (crash)log is relevant for this issue, link it here:
[crash-2017-04-02_15.03.23-server.txt](https://github.com/raoulvdberge/refinedstorage/files/888656/crash-2017-04-02_15.03.23-server.txt)

**Comment by raoulvdberge** [comment] 2017-04-04 13:12
Duplicate of #1016

**Closed by raoulvdberge** 2017-04-04 13:12 UTC
Labels: autocrafting, bug, duplicate
