### ISSUE TITLE
Unable to see or extract items from a disk

### ISSUE THREAD

**Issue by DinckelMan** [raoulvdberge/refinedstorage#1093] opened 2017-03-26 09:05 UTC
#### Issue description:
While migrating from 1k to 4k drives, I noticed that one of the drives refuses to have data extracted from it and immediately pops from the IN to the OUT section of the Disk Manipulator. Number of items on the drive is shown correctly. Putting the drive back into a Disk Drive adds the numbers correctly. Putting the drive back into the disk drive does NOT allow me to see any items on that disk from a grid.

#### Steps to reproduce:
Cannot reproduce. Server restart does not fix the issue

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Refined Storage: 1.2.23

#### Does this issue occur on a server? [yes/no] 
Yes

**Comment by xannor** [comment] 2017-03-26 13:44
I have this issue as well, the disk says it has 4 items on it but is blank when installed and the manipulator does not pull anything. I am assuming it is because it has invalid items on it possibly due to mod removal/upgrade/disabling.

**Comment by DinckelMan** [comment] 2017-03-27 05:35
I haven't changed anything in my setup when the issue appeared so I'm not sure what happened. I think my RS might have lost power while transferring items but I don't think that could have caused it. The power outages happened before with no consequences

**Comment by way2muchnoise** [comment] 2017-03-27 09:40
This is usually just a desync of the number of items on the disk between client and server. Annoying, but you shouldn't have lost anything.

**Comment by DinckelMan** [comment] 2017-03-27 19:20
Is there any way to recover the disk?

**Comment by Bamcrab** [comment] 2017-03-29 10:13
I am also experiencing this issue. Was caused (to me) from a creeper exploding all over my Refined Storage setup. Upon putting the disks in a new drive, they're not visible in the system. Adding extra items works, and shows up on the disk.

The disk manipulator also does not do anything with the items. Please help, I lost everything. :'(

**Comment by Morpheus1101** [comment] 2017-03-29 10:52
I am having a similar issue, I moved all my items form my base into my RS system to move to another location, when re-setting up at the new location, Despite having 1 disk full an another half full of the 64k, when viewing in the crafting grid, it shows 0 items

**Comment by raoulvdberge** [comment] 2017-03-29 16:11
That is a different issue and its a Forge one.

**Comment by Morpheus1101** [comment] 2017-03-29 22:33
Good ol Forge, You've done it again

**Comment by raoulvdberge** [comment] 2017-03-30 18:03
So:
1) The "items disappearing" issue is a Forge one, there is a PR for it but it needs to be tested more
2) This issue about the incorrect disk drive quantities is a duplicate of #520

**Closed by raoulvdberge** 2017-03-30 18:03 UTC

**Comment by DinckelMan** [comment] 2017-03-30 20:00
The last comment sort of defeats the purpose of the original issue, since it's not what the last few guys commented about. Still relevant or am I missing something?

**Comment by way2muchnoise** [comment] 2017-03-30 20:02
@DinckelMan I don't think there is a way to recover the disk, but to just cheat in a new one. Normally if the manipulator or grid shows no items in it, then it should be safe to assume there is no items left on it and it is just desync.

**Comment by BrianEdmonds** [comment] 2017-03-30 20:18
If you're worried about losing your stuff in digital storage, which I entirely sympathize with, you might want to check out the [Impractical Storage](https://minecraft.curseforge.com/projects/impractical-storage) mod. I was quite amused when I saw it the other day. I've not played with it yet, but definitely plan to.
