### ISSUE TITLE
Refined storage stops working after server restart

### ISSUE THREAD

**Issue by dmb1881** [raoulvdberge/refinedstorage#1117] opened 2017-04-01 20:52 UTC
#### Issue description:
When the server I play in restarts, my rs system stops working. But my controller is still on filled with power.

#### What happens:
When server restarts, it stops everything from running

#### What you expected to happen:
Everything to work after server restart
#### Steps to reproduce:
1. Be on server.
2. Have it restart
3. Badabing badaboom
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2 - Playing All the mods (Latest release)
- Forge: 12.18.3.2254
- Refined Storage: 1.2.24

Does this issue occur on a server? [yes/no]
Yes, happened on a server and I have no idea if its replicable.

![2017-04-01_16 46 44](https://cloud.githubusercontent.com/assets/10456033/24582339/9569a150-16fb-11e7-9d84-4f5b0b5d9145.png)

**Comment by dmb1881** [comment] 2017-04-01 20:53
Forgot to mention. In order to fix this I have to go through and break and replace every block involved in the rs system (Not including the cables.

**Comment by dmb1881** [comment] 2017-04-01 20:57
Update: Just noticed when I look in the actual controller it shows, that everything is using power even though they don't actually work.

**Comment by dmb1881** [comment] 2017-04-01 21:01
Another update: Giving the controller a signal to turn the system on and off doesn't fix the system, (But the ones I broke and replace work again) Also it might be worth mentioning that we do have sponge on the server. But not sure why that'd be the issue.

**Comment by raoulvdberge** [comment] 2017-04-01 21:01
Duplicate of #370

**Closed by raoulvdberge** 2017-04-01 21:01 UTC

**Comment by dmb1881** [comment] 2017-04-01 21:21
Another update, it seems to just be when the chunks are unloaded in general. This wasn't happening yesterday so I really don't know why this would be happening.

**Comment by dmb1881** [comment] 2017-04-02 23:47
@raoulvdberge This might interest you, for my friend the rs system is offline, but for me the rs system is online. I feel like this may have something to do with a desync with the server.

Friends Pov:https://cdn.discordapp.com/attachments/280228889530204161/298240458402824202/2017-04-02_18.35.31.png

https://cdn.discordapp.com/attachments/280228889530204161/298240759688069120/2017-04-02_18.41.48.png


My Pov: 
![2017-04-02_19 35 22](https://cloud.githubusercontent.com/assets/10456033/24592046/2df61228-17dd-11e7-9c98-ab86601e8145.png)

![2017-04-02_19 41 23](https://cloud.githubusercontent.com/assets/10456033/24592047/322f6786-17dd-11e7-9ae3-8c4420a0a7fb.png)
