### ISSUE TITLE
Incorrect item count in storage after autocrafting processing recipe

### ISSUE THREAD

**Issue by LuciusV** [raoulvdberge/refinedstorage#2037] opened 2018-10-15 13:55 UTC
#### Issue description:
Incorrect item count in storage after autocrafting processing recipe
#### What happens:
When I use pattern of smelting in Thermal Expansion autocrafting, for example, 1 iron ingot from 1 pulverized ingot and order some amount (like 5 or so) of iron ingots, incorrect amount is shown in storage (much larger than it should be, I still can only retrieve that ordered amount of them, but 'ghost' items remain and I cannot order more bebcause mod thinks there are some in storage. These 'ghost' items remain in storage network, making further autocrafting completely unusable, until one restarts game (after reloading item count is back to what it should be.
#### What you expected to happen:
Exact items appear in storage
#### Steps to reproduce:
1. Create crafting grid, pattern grid, add thermal expansion redstone furnace connected to crafter and link it with grid with interface or importer, use rftools modular storage as external storage
2. add recipe for some smelted ingots and order some amount like 5-10
3. doesn't work as it should
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2 
- Forge: 1.12.2-14.23.5.2768
- Refined Storage: 1.6.5
- RFTools: 1.12-7.56
- mcjtylib: 1.12-3.0.6.
- ThermalExpansion 1.12.2-5.5.2.39
Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment] 2018-10-15 13:57
Duplicate of #2021 
IIRC it only happens with external storages. So you can avoid it by using storage disks.
Already fixed indev.

**Comment by raoulvdberge** [comment] 2018-10-15 13:59
Hey, can you try the latest dev build from our Jenkins? https://jenkins.raoulvdberge.com/job/refinedstorage/

Should be fixed by #2021

Can you try and report back?

**Comment by LuciusV** [comment] 2018-10-17 08:53
Dear raoulvdberge, I think I still have same issue with external storage, could you please investigate?

(thermal expansion) making blazing pyrotheum Magma crucible + (industrial foregoing) black hole tank as external storage

**Comment by raoulvdberge** [comment] 2018-10-17 09:06
Good catch!

**Comment by raoulvdberge** [comment] 2018-10-17 19:30
Fixed! Thx.

**Closed** 2018-10-17 19:30 UTC
Labels: Area: Autocrafting, Status: Fixed indev, Type: Bug, Type: Duplicate
