### ISSUE TITLE
TPS issue with controller

### ISSUE THREAD

**Issue by knubbis93** [raoulvdberge/refinedstorage#812] opened 2017-01-02 16:33 UTC
#### Steps to reproduce:
1.put controller
2.add too little power to run the controller
3.controller starts blinking and causing bad tps (too high) skips i believe
...

#### Version (Make sure you are on the latest version before reporting):yes

- Minecraft: 1.10.2
- Forge:forge 12.18.3.2185
- Refined Storage:Refined Storage 1.2.14

Does this issue occur on a server? [yes/no] Yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here] theres no log only visual thing?

**Comment by raoulvdberge** [comment] 2017-01-02 17:32
duplicate of #566

**Closed by raoulvdberge** 2017-01-02 17:32 UTC

**Comment by knubbis93** [comment] 2017-01-02 17:38
oh okay is it something you are working on fixing in some way or will it be there?
