### ISSUE TITLE
Inventory Tweaks middle-click sorts like the player's inventory is one big container (in the Grid)

### ISSUE THREAD

**Issue by liquid600pgm** [raoulvdberge/refinedstorage#2014] opened 2018-09-29 15:59 UTC
### Issue description:
When middle-clicking on my inventory to sort it (in the Grid), the sorting treats the hotbar and "backpack" portions as one.

### What happens:
![What happens](https://i.imgur.com/deuJVYl.png)

### What you expected to happen:
![What I expect](https://i.imgur.com/VxZD6bg.png)

#### Proper sorting
1. Open your inventory
2. Middle-click on your inventory to sort

#### Broken sorting
1. Open a (Crafting) Grid
2. Middle-click on your inventory to sort

### Versions:

- Minecraft: 1.12.2
- Forge: 14.23.4.2759
- Refined Storage: 1.6.5
- Inventory Tweaks: 1.63

Does this issue occur on a server? - No

**Comment by DarkHelmet433** [comment] 2018-10-01 01:32
Sadly this is a duplicate of #1542 and #1933 - I think Raoul is expecting the Inventory Tweaks author to look into this, but it's not clear that anything is happening.

Personally, I delete Inventory Tweaks and replace it with Inventory Sorter by cpw.  That mod actually works.

**Comment by raoulvdberge** [comment] 2018-10-01 20:44
Yes, I've had enough reports about this. Now it's time for  the InventoryTweaks author to step in and guide me further, as I don't believe this is an RS problem.

**Closed by raoulvdberge** 2018-10-01 20:44 UTC
Labels: Area: Crossmod, Status: Need to investigate, Type: Bug
