### ISSUE TITLE
Problem with autocrafting Mekanism Energy Cube/Induction Cells

### ISSUE THREAD

**Issue by TractoBoy** [raoulvdberge/refinedstorage#570] opened 2016-11-01 20:18 UTC
#### Issue description:
I wanted to automate Mekanism Energy Cube/Induction Cells to upgrade my energy storage.
But it seems some Mekanism items/crafts aren't recognized.

#### What happens:
It looks like Mekanism crafting recipe aren't break down to the bottom tier.
Here are some images : [http://imgur.com/a/tMdtB](http://imgur.com/a/tMdtB)
As you can see, I did all the recipes leading up to the Advanced Induction Cell.
Yet, when I try to craft one Advanced, it says the Basic Induction Cells and the Advanced Energy cube aren't available, rather than trying to craft it. 

#### What you expected to happen:
Correct detection of recipes and lower-tier of items, so it get automated.

#### Steps to reproduce:
You can download my test world, created using Hermitpack 1.2.1 updated with lastest versions of forge & RefinedStorage (as stated below) : https://we.tl/RDmXWDvG10 and skip to step 4.
1. Get an automated crafting system
2. Create recipes for Mekanism (1 for Basic Energy Cube and 1 for Energy Tablet is enough).
3. Put gold, redstone and enriched alloy in the storage (a stack is enough).
4. Request the automatic craft for the Basic Energy Cube. It will say no Energy Tablet are available.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.2.2116-universal.jar
- Refined Storage: 1.2 beta 5
- Mekanism 9.2.0 (+ modules Generators and Tools, but probably not relevant)

Does this issue occur on a server? [yes/no]
Yes

**Comment by raoulvdberge** [comment] 2016-11-01 20:22
Don't use JEI transfering to create those patterns, make patterns for them with items from your storage system as you'd craft them yourself. The JEI recipe doesn't match with the actual items in your storage.

**Comment by TractoBoy** [comment] 2016-11-01 20:31
OK, tried and verified. I was happy that Refined Storage let me create patterns using intermediate items I didn't crafted before :( 

So this is more an issue between what Mekanism use as recipes and what it declares to JEI ?

Good to know, sorry for the inconvenience ! (and awesome rework of the autocrafting, much faster ! 👍 )

**Comment by way2muchnoise** [comment] 2016-11-01 20:33
The issue is with the NBT data stored on the cells. It is on the list of things.

**Comment by raoulvdberge** [comment] 2016-11-01 20:33
I'll close this now, as it's reported already. :)

**Closed by raoulvdberge** 2016-11-01 20:33 UTC
