### ISSUE TITLE
Adding just blocks to a compacting drawer which is connected via external storage only shows the blocks but not ingots or nuggets in grid

### ISSUE THREAD

**Issue by mrtopf** [raoulvdberge/refinedstorage#605] opened 2016-11-08 20:29 UTC
#### Issue description:

I connected a compacting drawer to a network via external storage. I then put 6 diamond blocks in. 

#### What happens:

In the grid I can see the 6 blocks, in the compacting drawer I can see blocks, diamonds and nuggets.

#### What you expected to happen:

I can see the 6 blocks, 54 diamonds and 486 nuggets in the grid. I would expect the block number getting lower when I remove diamonds or nuggets. 

#### Steps to reproduce:
1. Connect a compacting drawer to a basic network with controller and grid via external storage
2. Put 6 diamond blocks into the compacting drawer or the grid
3. Verify via shift-right click on the compacting drawer how many diamonds and nuggets are there
4. Check in the grid how many diamonds and nuggets are there (0 but 6 blocks).

In general I assume some sync support with compacting drawers is needed. 

...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2116 
- Refined Storage: 1.2.3

Does this issue occur on a server? [yes/no]

playing single player so no idea but I would guess so.

This might also be related to #591

**Comment by raoulvdberge** [comment] 2016-11-09 12:44
Duplicate of #591

**Closed by raoulvdberge** 2016-11-09 12:44 UTC
Labels: bug, duplicate
