### ISSUE TITLE
Crafter freezes server when shift clicking stack of speed upgrades

### ISSUE THREAD

**Issue by roboderpy** [raoulvdberge/refinedstorage#1430] opened 2017-08-19 13:26 UTC
Happens on very large networks with large amount of crafters
Snapshot: [rscrafter.zip](https://github.com/raoulvdberge/refinedstorage/files/1236373/rscrafter.zip)

**Comment by raoulvdberge** [comment] 2017-10-03 22:31
This is a duplicate of #1245.

**Closed by raoulvdberge** 2017-10-03 22:31 UTC
Labels: performance
