### ISSUE TITLE
Interface with unsatisfiable export causes chunk updates and fps drop

### ISSUE THREAD

**Issue by kinnison** [raoulvdberge/refinedstorage#1082] opened 2017-03-20 22:16 UTC
#### Issue description:

As per summary, if an interface has an unsatisfiable (but not crafting) export, then things go crazy

#### What happens:

chunk updates skyrocket, fps drops

#### What you expected to happen:

No problems

#### Steps to reproduce:
1. populate a system with some number of an item
2. pop down an interface, exporting more than that number of the item
3. watch fps drop
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2255
- Refined Storage: 1.2.22

Does this issue occur on a server? yes, though the issue is client-side

#### If a (crash)log is relevant for this issue, link it here:

https://www.youtube.com/watch?v=NGXhslgAqDA&feature=youtu.be illustrates the issue

**Comment by raoulvdberge** [comment] 2017-03-22 06:56
https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by raoulvdberge** [comment] 2017-03-22 14:24
Duplicate of #732

**Closed** 2017-03-22 14:24 UTC
Labels: awaiting

**Comment by kinnison** [comment] 2017-03-22 14:35
@raoulvdberge Do you need a profile from my server, or is the above enough to determine / reproduce the issue?

**Comment by raoulvdberge** [comment] 2017-03-22 14:50
Your profiling report is still welcome! You can post it here, if you want.

**Comment by kinnison** [comment] 2017-03-22 14:52
Is it better on #732 or here?  I'll try and generate a report tonight or tomorrow night.

**Comment by raoulvdberge** [comment] 2017-03-22 14:53
Here is fine.
