### ISSUE TITLE
Solderer stops working after relog

### ISSUE THREAD

**Issue by kvgeorge1** [raoulvdberge/refinedstorage#536] opened 2016-10-27 19:40 UTC
#### Steps to reproduce:
1. Create Solderer
2. Create recipe (anything)
3. Logout
4. Log back-in
5. Create recipe (anything).  At this point it will not work.
6. Break solderer
7. Place solderer
8. Create recipe (anything).  Back to working normally

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.1.2095-universal
- Refined Storage:  1.1.2

Does this issue occur on a server? [yes]

#### If a (crash)log is relevant for this issue, link it here:

[n/a]

**Comment by raoulvdberge** [comment] 2016-10-27 19:42
duplicate of #370

**Closed by raoulvdberge** 2016-10-27 19:42 UTC
