### ISSUE TITLE
Auto crafting octupled compressed cobblestone world freezing

### ISSUE THREAD

**Issue by jayykawai** [raoulvdberge/refinedstorage#935] opened 2017-01-28 18:16 UTC
#### Issue description: 
auto crafting octupled compressed cobblestone corrupts world (playing on skyfactory 3.0.6)

#### What happens: 
after flicking the lever to start autocrafting server skips a couple of ticks then crashes corrupting the world in the process.

#### What you expected to happen: 
no crashing and no corruption. a bit of lag is expected due to a high order even though the server has 16gb dedicated

#### Steps to reproduce:
1. Have an external storage plugged into a double chest full of cobble with cables going back into the system
2. Have a crafter set to autocraft on redstone input with 8 patterns (compressed, double compressed... octuple compressed)
3.  Flick the lever and voilà, crashes server and corrupts the world forever. (make sure to have a world backup before you test this.)
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 1.2.0
- Refined Storage: 1.2.18

Does this issue occur on a server? Yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment] 2017-01-28 18:38
Who still makes issues without crashlogs in 2017?

**Comment by jayykawai** [comment] 2017-01-28 18:48
lol autplayed let me give you it

**Comment by jayykawai** [comment] 2017-01-28 18:51
http://pastebin.com/aerDKMXM

**Comment by raoulvdberge** [comment] 2017-01-28 18:53
My homie @way2muchnoise will check out this issue.

**Comment by jayykawai** [comment] 2017-01-28 18:59
cool

**Comment by davelien** [comment] 2017-01-31 21:07
I believe I am experiencing the same issue, but with no crash log produced.  I manually start a large crafting job (create 27 Supremium Essence) and MC dies, world is apparently corrupted, I have to go to a backup copy.  Sometimes I see a "Disconnecting from server" message instead of a lockup of MC.  I can recreate it just by restoring to a previous save and then starting the same large crafting job again.  Though, without a crash log I'm not sure if this report is helpful at all.

**Comment by raoulvdberge** [comment] 2017-02-01 14:30
your world isn't corrupted, it's all still there, but MC just freezes because the crafting calculation is too complicated

**Comment by jayykawai** [comment] 2017-02-01 19:02
For me the world does corrupt. The server doesn't finish launching, and in sp it doesn't let me in.

**Comment by raoulvdberge** [comment] 2017-02-01 19:07
That isn't corruption.

**Comment by way2muchnoise** [comment] 2017-02-01 19:08
@jayykawai it is just figuring out the crafting, which takes way to long so you can't join in. Not really corrupted, if you could make sure it doesn't start the calculation with redstone (might need some world editing)

**Comment by davelien** [comment] 2017-02-01 19:11
> That isn't corruption.

You know, I agree.  I have had a couple of occasions where I start a large crafting job and ...boom...  MC locks up.  But I have been able to load the world and immediately cancel all crafting jobs and the world continues running just fine.  It doesn't work that way every time, but sometimes I get lucky.  And yes, I am learning to keep my crafting jobs on the smaller/manageable level now.

**Comment by way2muchnoise** [comment] 2017-02-01 19:20
I can say onces my finals are over (just one more on Friday Feb 3) and then I'll have time to change the autocrafting calculations to be more performant

**Comment by luizdgarcia** [comment] 2017-02-04 00:42
I have the same issue with any large craft it also does not generate any crash log it makes my CPU go way 100% e freezes, and you can log in the game because it freezes again when you try to log in, but its easy to fix the world by just opening MCedit2, loading the world,  use the inspect block tool, select the Refined Storage Controller and click on Remove Tile Entity, save the world and that should cancel the previous autocraft making your world loadable again.

**Comment by nathreed** [comment] 2017-02-11 13:42
I've also had issues requesting large crafts. For me, the game doesn't freeze or corrupt the world, but it does kick me off the server (usually with "A fatal error has occurred, this connection is terminated" or just "Connection reset by peer"). I am able to get back in for a few seconds, usually long enough to cancel the job from the crafting monitor if I'm standing right next to it. Canceling the job stops the constant disconnects.

**Comment by raoulvdberge** [comment] 2017-02-13 16:27
Duplicate of #902.

**Closed by raoulvdberge** 2017-02-13 16:27 UTC
Labels: autocrafting, bug
