### ISSUE TITLE
Fluid autocrafting not working with energized glowstone

### ISSUE THREAD

**Issue by K-4U** [raoulvdberge/refinedstorage#1976] opened 2018-09-05 20:48 UTC
#### Issue description:
RS cannot find my bucket of energized glowstone eventhough it's in the system and the system knows how to craft it, while crafting some lumium blend.
All of my crafting patterns are stored in a reborn storage crafter, except for the bucket filling, that is a Refined Storage crafter on a fluid transposer from TE
#### What happens:
I get a notification it can't find the bucket when autocrafting lumium blend.

#### What you expected to happen:
Lumium blend to be autocrafted

#### Steps to reproduce:
1. Create all the required patterns for the energized glowstone and lumium blend
2. Hit craft
3. ???
4. Get told it's not there.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2739
- Refined Storage: 1.6.4
- RebornCore: 3.10.0.332
- RebornStorage: 3.2.2.65

Does this issue occur on a server? yes

**Comment by K-4U** [comment] 2018-09-05 20:55
Update: I can manually ask for the glowstone bucket to be crafted. Just when i use it in the lumium blend, it won't detect it

**Comment by raoulvdberge** [comment] 2018-09-05 22:26
Is the lumium blend recipe an oredict one?

**Comment by raoulvdberge** [comment] 2018-09-07 13:06
Then I think this is a duplicate of #1954.

**Closed by raoulvdberge** 2018-09-07 13:07 UTC
