### ISSUE TITLE
Bug - Trying to craft 4095 Ultimate Induction Coils freezes Minecraft

### ISSUE THREAD

**Issue by llloyd4** [raoulvdberge/refinedstorage#902] opened 2017-01-23 08:35 UTC
#### Issue description:

Trying to build a max size Induction Matrix from Mekanism (18x18x18), trying to make the 4095 (4096 minus one for the Provider) and it locks up before giving me the Crafting Preview window, wait several minutes and Minecraft locks up. Even at half of that number, 2048, it still locks up everything. 

#### What happens:

Minecraft locks up while waiting for the Autocrafter to pull up the Crafting Preview window.

#### What you expected to happen:

It to pull up Crafting Preview window for making the 4095 Ultimate Induction Coils and give me the option to Start or Cancel.

#### Steps to reproduce:
1. Make all the patterns for the Ultimate Induction Coils part of the multi block Induction Matrix, build up the crafting infrastructure with Crafters.
2. Go into the Grid and select the Ultimate Induction Coil, click +64 enough times to get to 4096, click -1 once,
3. Click Start
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.17

Does this issue occur on a server? [yes/no] No idea, I am playing in a local world.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

#### Oh, and before anyone asks, I have the client configured to give Minecraft 4gb of memory out of the 16gb total system memory and my processor is a Phenom X6 1045T. So it's not a system issue, it has the grunt to do it. >.<

**Comment by Joshwoo70** [comment] 2017-01-23 08:40
*sigh* not even a crash log...and it occured on a single player. so it is not on a server.(in non technical terms)

**Comment by llloyd4** [comment] 2017-01-23 08:46
Nope, it froze Minecraft forcing me to kill it (the Java instance) in the Task Manager.

**Comment by Joshwoo70** [comment] 2017-01-23 08:57
@llloyd4 it will be VERY helpful if you posted your fml latest log. in pastebin or gist.github.com

**Comment by llloyd4** [comment] 2017-01-23 17:08
Uh... *looks at the size of the file* Thank God I took the Christmas special opportunity and went Pro on Pastebin. O.o 3.6mb, so be warned. - http://pastebin.com/SPy840qC

**Comment by way2muchnoise** [comment] 2017-01-23 17:49
How deep is this recipe? As in how many steps does it have to make for just one?

**Comment by llloyd4** [comment] 2017-01-23 18:42
Honestly? No idea, never made one manually, I spent an hour setting up the infrastructure, mostly trying to work out why the Metalurgic Infuser wasn't working (user error) and why the Transfer Nodes / Pipes / Transfer Filters / Retrieval Nodes wasn't working (put in two bug reports with them on it, the retrieval nodes were ignoring the filter and the transfer nodes weren't connecting to the pipes). But once I got them together it was a matter of minutes to put up two more Crafters and make all the patterns. Let me see... Have to load up Minecraft again. Reminds me, need to put in a Feature Request, a dedicated crafter block with a lot more pattern storage than the Crafter. I have an entire wall of Crafters just for all the crafting patterns. 9 slots isn't enough for the Direwolf20s of the Minecraft world. :dagger: 

Alright, Ultimate requires 4 energy tablets, an Ultimate energy cell and 4 Elites, Elite requires 4 tablets, an Elite energy cell, and 4 Advanced, an Advanced requires 4 energy tablets, an Advanced energy cell, and 4 Basics, a Basic requires 4 energy tablets, a Basic energy cube, and 4 lithium. The tablets *might* be an issue, they don't stack in inventory which makes them a real bug bear to work with manually. Like the cooling cells from IC2, if I remember right. But that's why we have autocrafting.

**Comment by way2muchnoise** [comment] 2017-01-23 18:48
So it is a depth issue, I know what I can do to fix it. But I don't have the time right now. I guess you'll have to order smaller amounts for now.

**Comment by llloyd4** [comment] 2017-01-23 18:50
Ok. I've wound it down to 512 with no luck. O.o I might have to do each component once I work out the math on exactly how much of each item I need.

**Comment by Rudolpher** [comment] 2017-01-23 19:50
For now I suggest using for instance an RF Tools Crafter and Detector for the smaller parts of complex recipes that require insane amounts(Like the energy tablets, control circuits and so on). Also more kind to your TPS when auto-crafting it :)

**Comment by llloyd4** [comment] 2017-01-23 19:54
*hmms* You mean use a processing pattern, not crafting pattern, and Crafter on a RF Tools Crafter, put in 3 gold, 2 enriched alloy, 4 redstone and get out an energy tablet?

**Comment by Rudolpher** [comment] 2017-01-23 20:07
Output necessary items to chest(or better, drawers, so it doesn't fill up with one item), output to an RF Tools Crafter and have it make the energy tablets depending on redstone signal. Attach a detector with redstone/conduit and configure it to either send or stop sending a redstone signal when your RS system has over X amount of energy tablets and thereby stopping the crafter from making more.
It's going to be a little while until way2muchnoise can properly fix this issue, so look for alternative ways of doing massive recipes for now ;)

**Comment by raoulvdberge** [comment] 2017-04-01 17:54
Duplicate of #838

**Closed by raoulvdberge** 2017-04-01 17:54 UTC
Labels: autocrafting, performance
