### ISSUE TITLE
Refined Storage + EnderIO Crash

### ISSUE THREAD

**Issue by DarkDon** [raoulvdberge/refinedstorage#2382] opened 2019-12-19 23:44 UTC
Package: All the mods 3 remix 1.5.2

Issue:

Crafting a little big batch (220 big reactor casings) , recipes for alloys in Alloy Smelter , cause Server to crash after a few minutes. Issue can only be resolved if the craft gets canceled.

Will post this in EnderIO too.

Crash report:
[crash-2019-12-19_15.57.36-server.txt](https://github.com/raoulvdberge/refinedstorage/files/3986071/crash-2019-12-19_15.57.36-server.txt)

Any hint how to solve this?

**Comment by Darkere** [comment] 2019-12-20 11:58
The server was taken down by the watchdog due to lag. You can change the threshold at which this happens by editing max-tick-time in server.properties.

That doesn't solve the lag issue though. You can reduce lag introduced by auto crafting by using large (sufficient) buffers between crafter and machine. 
In the end, it's still a good idea to keep crafting requests smaller in order to avoid lag issues.

 The issue is being worked on.

**Comment by raoulvdberge** [comment] 2019-12-28 16:19
This is a performance problem in RS and will be fixed later. Closing as it's a duplicate.

**Closed** 2019-12-28 16:19 UTC
