### ISSUE TITLE
Poss Memory leak caused by autocraft complicated items

### ISSUE THREAD

**Issue by shivachirr** [raoulvdberge/refinedstorage#1081] opened 2017-03-20 21:51 UTC
#### Issue description:
autocrafting certain things cause a memoryleak as minecraft qucikly maxes out at 10 GB and lags heavily
#### What happens:

so i go to autocraft an item one is the fuel staion from Advance rocketry and i hit the start and it dose not go any father not even to show me what is needed to be made. and when i hit cancel is dose not work

#### What you expected to happen:

autocrafting works normaly

#### Steps to reproduce:
1. want to make something that takes alot to make like the fuel station via Advance Rocketry
2. go to autocraft it 
3. after choosing amount hit start

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Refined Storage: 1.2.24

Does this issue occur on a server? no

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment] 2017-03-22 06:59
Not much we can do without a profiling report

https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by shivachirr** [comment] 2017-03-26 06:23
here you go sorry for the wait

https://drive.google.com/file/d/0B4ZNJDO5qt8Iakl0SmlGSS03bjg/view?usp=sharing

**Comment by raoulvdberge** [comment] 2017-03-30 17:55
Thanks for the report. I'll close this for now, since this is a duplicate of #838.

But, since this issue and #838  are linked now thanks to this comment we'll obviously still look at your profiling report.

**Closed by raoulvdberge** 2017-03-30 17:55 UTC
Labels: investigate, performance

**Comment by shivachirr** [comment] 2017-03-30 18:00
i dont think this is linked because the other one is Major lag this a
crippling non-recoverable memoery leak becasuse the moment you try craft
simething and run into the bug you have no choice but to restart the game
otherwise the game will Max out Ram space and lock up fully and cobstanly
hitch and last till it runs out of memory and you will never be able to
even start auto crafting the item

**Comment by raoulvdberge** [comment] 2017-03-30 18:01
Internally, memory and TPS lag go hand in hand. But your issue appears now in the main "autocrafting performance" issue, so we can always still look at it.

**Comment by Thrull1** [comment] 2017-11-10 19:22
I am having the same issue as @shivachirr.  This is an intermittent issue for me that has become worse as the world has become older and more complex.  I am using refined storage as the core of my inventory.  This problem with the game consuming all available memory and basically freezing used to occur only if I crafted (for example) 4 64k storage disks but now will happen if I craft something simple like 10x inverted lamps.  
I have attached an nps file that will hopefully help.  As I am sure you are aware, it is challenging to run the sampler commands while the game is lagging and trying to freeze up.  

[ChrisTest2.zip](https://github.com/raoulvdberge/refinedstorage/files/1462464/ChrisTest2.zip)

I have read the #838 post and I find that my behaviour is more similar to the one discribed here rather than there.

Thanks,
