### ISSUE TITLE
(BUG) All Refined Storage Drive Bays empty after server restart

### ISSUE THREAD

**Issue by Vaygrim** [raoulvdberge/refinedstorage#1846] opened 2018-07-03 17:11 UTC
#### Issue description:
We perform scheduled restarts of our servers twice a day, just to keep performance 'fresh'. After this morning's scheduled restart, the server came back online with all RS Drive Bay blocks being empty of drives.

#### What you expected to happen:
Not this.

#### Steps to reproduce:
1. Literally no clue what caused it.

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.12.2
- Forge: 2705
- Refined Storage: 1.5.34
- Refined Storage Addons: 0.3
- Reborn Storage: 1.12.2-3.1.0.50

Does this issue occur on a server? YES

#### If a (crash)log is relevant for this issue, link it here:
No crash log, but we are trying to pull the server logs from this time period. It's going to be a metric butt-ton of data to go thru tho. Want 'em ?

**Comment by raoulvdberge** [comment] 2018-07-03 18:40
Are all the other blocks reconfigured as well?

**Comment by Vaygrim** [comment] 2018-07-03 21:16
Yup, all Import / Export Buses, External Storage Buses, everything reset back to factory defaults.

**Comment by raoulvdberge** [comment] 2018-07-03 21:21
Do you have a backup?

**Comment by raoulvdberge** [comment] 2018-07-03 21:22
You can restore by copying refinedstorage_nodes.dat.

**Comment by Vaygrim** [comment] 2018-07-03 21:24
The greater worry is what caused it to happen, and will it happen again?

**Comment by raoulvdberge** [comment] 2018-07-03 22:07
I don't know, there are no reproduction steps. I'm just trying to help you get it back to running as it was, as a temporary solution.

**Comment by raoulvdberge** [comment] 2018-07-03 22:48
I know, no worries ;-)

**Comment by DarkHelmet433** [comment] 2018-09-09 21:07
I had the exact same thing in a FTB Revelations server running RS-1.5.34.  I do not have access to that server for backups or logs.  I had: all drive bays emptied, all upgrades gone, all configuration reset, all patterns gone (both in processing crafters and the Reborn Storage multiblock).  

I would normally consider a Me Too! report (with no logs) to be not particularly useful but there's an additional data point. Nobody else's RS systems on the server were affected. Mine was the only one of the five that was reset.  

The key difference between theirs and mine was that mine was active continuously active.  It was receiving some items from ore processing and requesting on demand crafting periodically.  The other systems were dormant when nobody was using them.

There is a distinct possibility that I may have crashed the server with an incident with an uncontrolled draconic evolution stabilized mob spawner.  My RS system would have been trying to keep up with processing the drops after I'd logged out.

**Comment by williambacteria** [comment] 2019-05-13 09:07
I have the same problem. Is there any other way to fix it?I guess this ia a data loss of nbt.When my server has restarted,every RS Block will change its face direction and Disc drive/Network Transmitter will be cleard
.Hope this problem will be fixed and I like this mod very much...

**Comment by timeherald** [comment] 2019-05-23 08:29
I had disk corruption, showing 0%, and a string of letters and numbers (instead of 5000/16000k or something like that) after a server mod update. I found that it was because the mod altered a few of its item files, thereby corrupting the whole disk (since it couldn't match the old item IDs). This may be what is happening to you, too.

The backup file didn't seem to fix it... It's rather difficult to update any mods when all player's disks get corrupted, and they lose their items.

**Comment by williambacteria** [comment] 2019-05-23 08:39
I didn't update this mod . I just restart my server and this bug caused.

**Comment by Darkere** [comment] 2019-08-30 20:24
Alright found a way to reproduce the bug in my dev environment.

1. Run in debug mode
2. Fill the diskfile somehow.
3. Put a breakpoint in StorageDiskManager.java Line 138
4. Change the disk and force it to save. 
5. after hitting the breakpoint add another breakpoint in MapStorage.java Line 135 and continue to that
6. Crash the game using task manager (pressing stop in Intellij finishes the write).
7. Marvel at your new 0 byte sized file

Solution: Overwrite the vanilla save mechanism. They are using FileOutputStreams maybe something else doesn't overwrite the file until it's actually complete?

**Comment by raoulvdberge** [comment] 2020-04-26 08:30
Closing as this is a vanilla issue.

**Closed** 2020-04-26 08:30 UTC
Labels: Bug, Can't Reproduce, Help Wanted
