### ISSUE TITLE
Update 1.2.18 breaks autocrafting and ext. storage

### ISSUE THREAD

**Issue by homemmakako** [raoulvdberge/refinedstorage#901] opened 2017-01-23 01:01 UTC
#### Issue description:
After updating to 1.2.18 the external storage isn't able to insert items even if in "insert & extract" mode (this was tested with the drawer controller from storage drawers). Also autocrafting isn't working at all for me. I did try to break and replace the blocks, but that din't solve the problem.

#### Steps to reproduce:
1. Just create a new system and try one of the features mentioned above.
2. Profit!...or something like that

#### Versions:

- Minecraft: 1.10.2
- Forge: 12.18.3.2215
- Refined Storage: 1.2.18

**Comment by raoulvdberge** [comment] 2017-01-23 14:43
Did you try to break and replace the controller? Nothing really changed in 1.2.18 with external storages, so the version number is irrelevant.

**Comment by llloyd4** [comment] 2017-01-23 20:11
I'm noticing the same thing in .17, I have a Compacting Drawer with tin in it, plenty of space for more, yet one of my 64k disks filled up. Taking a peek at it on another network it has over 4k tin on the disk. O.o

**Comment by raoulvdberge** [comment] 2017-01-23 20:11
You didn't set the priority right!

**Comment by raoulvdberge** [comment] 2017-01-23 20:15
This is a duplicate of #370

**Comment by llloyd4** [comment] 2017-01-23 21:10
On mine the external storage is priority 1 and the disk drives are 0 so...

**Comment by raoulvdberge** [comment] 2017-01-23 21:11
Are you 100% sure the CompactingDrawer was not full? And still, can still be caused by #370.

**Comment by llloyd4** [comment] 2017-01-23 21:17
Yeap, checked the external storage gui and it isn't anywhere near 100%

**Comment by homemmakako** [comment] 2017-01-24 00:59
I just downgraded from .18 to .17 and seems to be working fine again

**Comment by raoulvdberge** [comment] 2017-01-25 01:09
Still #370, I think the world reload by downgrading made everything work again. But nothing changed in the external storage code so it isn't possible.

**Closed by raoulvdberge** 2017-01-25 01:09 UTC
Labels: bug, duplicate
