### ISSUE TITLE
Crash on placing grid

### ISSUE THREAD

**Issue by hoohax** [raoulvdberge/refinedstorage#28] opened 2016-04-08 12:49 UTC
Minecraft: 1.9
Forge: 1854
JEI: jei_1.9-3.2.8.182
RefinedStorage: refinedstorage-0.5.4

placed controller, disk drive (placed 1k storage disk in drive), and grid. Once the grid was placed server threw a bunch of errors, tried breaking the grid it went into my inventory but a machine block remained where it was once i tried replacing the grid the server died and will not come back up unless i remove refinedstorage and blocks from the world.

logs:
http://pastebin.com/nAkrr2DR

this is my first time posting an issue so please let me know if there's any other info you might need or things you want me to test?

**Comment by raoulvdberge** [comment] 2016-04-08 23:16
Thanks for reporting. I know the cause and will fix for next release.

**Comment by raoulvdberge** [comment] 2016-04-08 23:17
You don't have this issue on singleplayer, right?

**Comment by hoohax** [comment] 2016-04-08 23:19
I did, but it didn't seem to kill the client as fast. the world problem was also there. would you like me to try and get some logs?

**Comment by raoulvdberge** [comment] 2016-04-09 12:28
Can you try following patch (in a new world) and see if it works? Replace it with your current installation.

[refinedstorage-patched.zip](https://github.com/raoulvdberge/refinedstorage/files/211221/refinedstorage-patched.zip)

(rename .zip to .jar)

**Comment by hoohax** [comment] 2016-04-09 15:09
Everything was going great, I was able to place,break, replace the grids! After that test i added neotech for power: neotech-1.9-3.0.5 bookshelfapi-1.9.3.0.4

everything worked until I tried to craft something and pull it out of the crafting grid.
http://pastebin.com/Dq4FMM6U

I also tried it on a single player world and everything worked fine!

**Comment by raoulvdberge** [comment] 2016-04-09 15:42
Ok, thanks again for reporting, should be fixed in 7fe2a89f561339d7fd614a7c7e8e3ae36ee9390c.

Could you retry again with this:

[refinedstorage-patch.zip](https://github.com/raoulvdberge/refinedstorage/files/211322/refinedstorage-patch.zip)

**Comment by hoohax** [comment] 2016-04-09 16:08
Works great on single and multiplayer!

**Comment by raoulvdberge** [comment] 2016-04-09 16:09
Great, will release all these fixes as 0.5.5 in ~2 hrs on Curse.

**Closed by raoulvdberge** 2016-04-09 16:09 UTC
Labels: bug
