### ISSUE TITLE
Cannot read from 64k Storage Disk

### ISSUE THREAD

**Issue by mcsag** [raoulvdberge/refinedstorage#710] opened 2016-12-05 02:41 UTC
#### Issue description:
After removing my 64k Storage Disk from the Disk Drive, I tore down my setup and moved it to the basement, for easier wiring access. When it was all setup once again, I was no longer able to read from the 64k Storage Disk, although I can still write to it.

#### What happens:
The 64k Storage Disk has 32,987 written.  Upon inserting it into the disk drive, and using a crafting grid, my entire system is empty.  I can, however, insert items, and after inserting a stack of stone brick, the 64k Storage Disk claims 33,051 written.  But again, only that stack of stone brick is available when using the crafting grid.

These images demonstrate the issue:
![2016-12-04_21 06 27](https://cloud.githubusercontent.com/assets/3598438/20871702/5caff7de-ba66-11e6-8921-28126cdd0ed1.png)
![2016-12-04_21 06 52](https://cloud.githubusercontent.com/assets/3598438/20871707/6286c0b6-ba66-11e6-9c00-65c34b0230e1.png)

#### What you expected to happen:
Insert a 64k Disk Drive with 32,987 written items, and have all items available via a crafting grid or regular grid.

#### Steps to reproduce:
1. Write items to a disk.
2. Remove the disk, tear down the setup.
3. Recreate the setup, reinsert the disk.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: forge-12.18.2.2171
- Refined Storage: 1.2.8

This error originally occurred on "FTB Presents Direwolf20 1.10," pack version 1.1.1.  Having updated the server to 1.1.2, the bug persists.

Does this issue occur on a server? Yes

**Comment by raoulvdberge** [comment] 2016-12-05 17:53
I have a feeling that your disk has corrupted and all your items are gone from it, but the count stayed (which is stored seperately).

Do you have any logs when this happened (e.g. from when you destroyed the Disk Drive)?

Can you reproduce this 100% of the time?

**Comment by mcsag** [comment] 2016-12-05 18:25
I am checking for logs now, but I'm not optimistic as to finding the correct one.  I have also been unable to reproduce the issue.  Corruption makes sense now that I know the count is not calculated every time the disk is loaded (HashMap.size() for instance).

**Comment by raoulvdberge** [comment] 2016-12-05 18:30
I suspect something went wrong during saving the disk, and it aborted causing item loss. You can do a quicksearch for "exception" in the logs.

**Comment by raoulvdberge** [comment] 2016-12-05 18:37
Can you also check the NBT data of the disk stack that has gone corrupted? You can see it with tools like NBTExplorer and opening your player save file.

**Comment by mcsag** [comment] 2016-12-05 20:33
The only exceptions that took place are MissingPrerequisiteException for Thaumcraft, and IllegalArgumentException from Railcraft, and I'm relatively certain those are unrelated.  I will check for player data as soon as I find a free moment.

**Comment by aelfwyne** [comment] 2016-12-07 00:50
Throwing off a "can't reproduce" on the MANY reports of the same bug is not helping matters any. You might not be able to reproduce, but many other people are.

This is a show-stopper bug.

**Comment by raoulvdberge** [comment] 2016-12-07 12:24
Duplicate of #712

**Closed by raoulvdberge** 2016-12-07 12:24 UTC
Labels: bug, can't reproduce
