### ISSUE TITLE
Multiple patterns for the same item will conflicts with each other

### ISSUE THREAD

**Issue by ExplodingONC** [raoulvdberge/refinedstorage#2263] opened 2019-06-13 18:56 UTC
#### Issue description:
If there are multiple patterns crafting the same product, the autocrafting system will only choose the first one of them, no matter whether there is enough resource to craft that.
#### What happens:
For example, iron dust can be crafted by crushing iron ores, or by powdering iron ingots. Create 2 processing patterns containing these 2 methods separately, then put them in the corresponding crafters. 
If you put the pattern using iron ores in the first slot, than the autocrafting system will only looking for iron ores when you want to craft some iron dust, even when you only have ingots but no ores in the storage system (which is always the case, since most recipes use ingots, and starting from ores will take a long time). Similarly, if you put the pattern using iron ingots in the first slot, then the system will never handle those ores any more.
#### What you expected to happen:
I hope that the system can accept multiple patterns for the same item, and auto choosing the one that is able to be carried out. It can be even better if we are allowed to give different priorities to different patterns, thus making the system auto choosing the best way to get something crafted.
#### Steps to reproduce:
As described above.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Refined Storage: 1.6.14

Does this issue occur on a server? [yes/no]
Yes.
#### If a (crash)log is relevant for this issue, link it here:
Not a crash.

**Comment by Darkere** [comment] 2019-06-13 19:11
Duplicate of #2192

**Comment by ExplodingONC** [comment] 2019-06-13 19:16
> Duplicate of #2192

In that issue, the mod creator said that "For processing patterns, it uses multiple to spread the processing", but it seems that this is not the case... at least not for different patterns.

**Comment by Darkere** [comment] 2019-06-14 14:11
It does so only if the patterns are exactly the same.

So you can set up multiple furnaces + crafter and both with the cobble -> stone recipe. Then it will spread out the resources.

**Closed** 2019-07-20 10:40 UTC
