### ISSUE TITLE
1.11.2-1.4.3 Grid Null Pointer Exception Render Screen Crash

### ISSUE THREAD

**Issue by TwitchtvCarbs** [raoulvdberge/refinedstorage#1188] opened 2017-04-25 16:58 UTC
#### Issue description:
Sometimes there are slots in the grid that show 0 (Must be air?) When hover over them or scrolling in the inventory it seems to crash to desktop.

#### What happens:
Crash to desktop when rendering a null stack (null pointer exception renderscreen)
#### What you expected to happen:
Not to crash/ have empty item stacks rendered
#### Steps to reproduce:
1.Open grid
2.Shift-click items into the system.
3.When looking at the items in your system notice a slot with 0 and nothing in it.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 13.20.0.2282
- Refined Storage: 1.4.3

Does this issue occur on a server? [yes/no]
Yes and single player also
#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/sSAtuWpC

This is what the issue looks like :)
https://gyazo.com/bc051332bf0959ba7c0a62533c733a04

**Comment by raoulvdberge** [comment] 2017-04-25 17:39
I can't reproduce this issue with your provided reproduction steps. Please provide better reproduction steps.

**Comment by TwitchtvCarbs** [comment] 2017-04-25 17:45
Interesting :/ but it happens and I have the image showing what is happening. Maybe its because I am using the external storage with drawers?

**Comment by raoulvdberge** [comment] 2017-04-25 17:45
I need exact reproduction steps

**Comment by TwitchtvCarbs** [comment] 2017-04-25 18:26
Okay I think I have it now.
With using an external storage hooked to a drawer controller
1.Open crafting grid (things look fine)
2.Place down another drawer next to your drawer controller
3.Check crafting grid
4.Repeat a few times and this 0 item appears in the list when hovered over it crashes the game.
Simply breaking the external storage and replacing gets rid of this 0 item but it will occur every few extra drawers you add on AFTER the external storage is already hooked into the drawers set up.
Hopefully this will help :3

**Comment by raoulvdberge** [comment] 2017-04-25 18:27
Interesting, let me look into this

**Comment by raoulvdberge** [comment] 2017-04-25 18:29
Duplicate of #1183

**Closed by raoulvdberge** 2017-04-25 18:29 UTC
Labels: bug
