### ISSUE TITLE
More sorting options

### ISSUE THREAD

**Issue by jesmores** [raoulvdberge/refinedstorage#620] opened 2016-11-12 16:03 UTC
Kinda similar to the filtering options requests, but it would be great to be able to sort by

- **oredictionary tag**: so ores are grouped together, woods are grouped together, ingots are grouped together, etc. For things that don't have a tag, revert to normal sorting by name (or maybe the next option below)
- **mod name**: this way vanilla items get grouped together, then each mod's blocks and items

**Comment by raoulvdberge** [comment] 2016-11-12 16:06
duplicate of #359

**Closed by raoulvdberge** 2016-11-12 16:06 UTC
