### ISSUE TITLE
[1.12] Autocrafting Breaks After Mod Portal Use

### ISSUE THREAD

**Issue by nightcipher** [raoulvdberge/refinedstorage#1382] opened 2017-07-24 01:45 UTC
#### Issue description: 
This is an interaction between Aroma1997's Dimensional World and Refined Storage. Automatic crafters stop working after going to the dimensional world, then return to the overworld. Does not always occur, currently working on reproducing the problem consistently.

#### What happens: 
After being in the dimensional world for over a minute and then returning tot he overworld, automatic crafters that are placed will not function. Placing an order for any item (tested with quartz-enriched iron) will send you through the menus, but not craft anything. No entry appears in the Crafting Monitor.

#### What you expected to happen: 
Leaving the overworld and returning to the Refined Storage Crafting Grid will allow you to auto-craft items.

#### Steps to reproduce:
1. Have a basic Refined Storage system consisting of at least a power source, a controller, a crafter, a disk drive with at least one 1k storage drive, and a crafting grid.
2. Enter a portal to Aroma1997's Dimensional World.
3. Remain there for at least 1 minute. 
4. Return to the Overworld.
5. Attempt to craft an item through the autocrafting system.
6. Crafting fails, no items are consumed or produced. Items cannot be crafted with autocrafting until the world is re-loaded from the title screen.

#### Version:

- Minecraft: 1.12
- Forge: 14.21.1.2423
- Refined Storage: 1.5.13

Untested on servers. Custom mod pack in use.

No crash, and thus no crash log. I will post any updates related to this bug as soon as I discover them, or if I find a way to reproduce the problem 100% of the time. If there are other logs to upload, let me know, and I will upload them.

**Comment by roboderpy** [comment] 2017-08-04 00:17
This is a dupe of #1386 because when #1386 bug occurs, all queued crafting tasks erases because controller breaks.

**Closed** 2017-08-04 00:25 UTC
Labels: bug, investigate

**Comment by nightcipher** [comment] 2017-08-04 00:27
I'm glad that the root of the problem was found, because I was having trouble reliably reproducing the bug. Hope that it gets fixed soon, and that this might have been of some usefulness.
