### ISSUE TITLE
Non-fatal error. Connected cable that has 8 item importers, 4 fluid importers, 4 exporters, and 4 detectors.

### ISSUE THREAD

**Issue by Sakata-MC** [raoulvdberge/refinedstorage#2366] opened 2019-12-07 20:07 UTC
MC 1.12.2, Forge 2844, ATM3:R based pack, Non fatal error when player placed cable that joined his build to his RS network.
Player built a farm with Industrial forgoing, pre-configured item and fluid import and export, has his machines turn off when product > some amount (yay i find one guy that can shut his crap off when not needed!)
It's not a wall of text, so figure I'll just paste it.
````
[14:58:00] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Method com/raoulvdberge/refinedstorage/tile/TileController.getWorld()Lnet/minecraft/world/World; is abstract
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_232]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_232]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.AbstractMethodError: Method com/raoulvdberge/refinedstorage/tile/TileController.getWorld()Lnet/minecraft/world/World; is abstract
	at com.raoulvdberge.refinedstorage.tile.TileController.getWorld(TileController.java) ~[TileController.class:?]
	at com.raoulvdberge.refinedstorage.apiimpl.API.isNetworkNodeEqual(API.java:366) ~[API.class:?]
	at com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNode.equals(NetworkNode.java:293) ~[NetworkNode.class:?]
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1035) ~[?:1.8.0_232]
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:1.8.0_232]
	at java.util.Collections$SetFromMap.add(Collections.java:5515) ~[?:1.8.0_232]
	at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeGraph$Operator.apply(NetworkNodeGraph.java:171) ~[NetworkNodeGraph$Operator.class:?]
	at com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNode.visit(NetworkNode.java:233) ~[NetworkNode.class:?]
	at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeGraph$Visitor.visit(NetworkNodeGraph.java:210) ~[NetworkNodeGraph$Visitor.class:?]
	at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeGraph.invalidate(NetworkNodeGraph.java:62) ~[NetworkNodeGraph.class:?]
	at com.raoulvdberge.refinedstorage.apiimpl.API.discoverNode(API.java:286) ~[API.class:?]
	at com.raoulvdberge.refinedstorage.block.BlockNode.func_180633_a(BlockNode.java:38) ~[BlockNode.class:?]
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:186) ~[ahb.class:?]
	at com.raoulvdberge.refinedstorage.item.itemblock.ItemBlockBase.placeBlockAt(ItemBlockBase.java:46) ~[ItemBlockBase.class:?]
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54) ~[ahb.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:889) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:492) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_232]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_232]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
````

**Comment by Darkere** [comment] 2019-12-07 21:10
Duplicate of #2241

Please also see #2293 for potential solutions.

**Closed** 2019-12-07 22:19 UTC
