### ISSUE TITLE
DiskManipulator emptied a disk but items were lost

### ISSUE THREAD

**Issue by croftyraider** [raoulvdberge/refinedstorage#631] opened 2016-11-14 06:39 UTC
#### What you expected to happen:
All the items to transfer.

I'm wondering if there is some file I can go fiddle with in my world folder to recover my stuff...

#### Steps to reproduce:
Not sure, but what I described is what I did. Looking at the list of items that remained, it seems like those are the items that were transferred after I started up minecraft again to finish the transfer. Not 100% sure, but it seems like that. So possibly starting a transfer, stopping minecraft, starting again may reproduce the issue.

Also, I had added 4 speed upgrades to the disk manipulator.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2092
- Refined Storage: 1.1.3

Does this issue occur on a server? [yes/no] no idea

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment] 2016-11-20 14:40
This is a duplicate of #520

**Closed by raoulvdberge** 2016-11-20 14:40 UTC
