### ISSUE TITLE
disk bug

### ISSUE THREAD

**Issue by harmjan94** [raoulvdberge/refinedstorage#738] opened 2016-12-11 12:53 UTC
#### What happens:
Im playing with some friends on a private server 
We were moving stuff over to our new build house when this happened:
We put the refined storage system down with only a grid, a disk drive and a controller (basic storage).
System is working and well. Now when we put the storage disks in, it won't show the items which are in the disks. We can put new items in the disk tho and get them out no problem.

Sorry for my English, its not native.

#### What you expected to happen:

disks showing items and not bugging out

#### Steps to reproduce:
1. Moved our storage over to a new system.
2. Put power to the system.
3. Items not showing on the disks, item on other storage blocks do show.
4. Seperate storage system build.
5. Checked if we can see the items there, we can't

#### Version (Make sure you are on the latest version before reporting):

we're playing on ftb infinity lite for 1.10 modpack version 1.3.3.

- Minecraft: 1.10.2
- Forge: ?
- Refined Storage: ?

**Does this issue occur on a server?** 
yes

**Comment by raoulvdberge** [comment] 2016-12-11 21:33
This is a duplicate of #712

**Closed by raoulvdberge** 2016-12-11 21:33 UTC
