### ISSUE TITLE
Storage Blocks have items that cannot be seen on Grid.

### ISSUE THREAD

**Issue by calloatti** [raoulvdberge/refinedstorage#1155] opened 2017-04-11 11:20 UTC
#### Issue description:

Storage Blocks GUI reports items, Grid shows no items.

#### What happens:

No items on Grid.

#### What you expected to happen:

The items on the Storage Blocks should be seen on the Grid.

#### Steps to reproduce:

Check imgur album:

http://imgur.com/a/qhSSw

#### Version (Make sure you are on the latest version before reporting):

Java is version 1.8.0_121, using 64-bit architecture.
Minecraft 1.10.2
refinedstorage-1.2.25

Mods:
  Aroma1997Core-1.9.4-1.1.1.2
  AromaBackup-1.9.4-1.0.1.1
  AutoRegLib-1.0-2
  BetterFps-1.4.3-1.10
  BigDoors-1.10.2-1.3.0
  BlacksmithTrashcan-1.10.2_0.5.2
  ceanimals-1.10.2-1.3.0
  Chameleon-1.10-2.2.2
  clarity-1.0
  ClayWorldGen-1.1.0-1.10.2
  ClientTweaks_1.10.2-1.1.16
  compatlayer-1.10-0.2.5
  CraftTweaker-1.10.2-3.0.24
  dualhotbar-1.1x-1.7.2
  ElevatorMod[V.1.3.0][MC.1.10.2]
  EnderCore-1.10.2-0.4.1.65-beta
  EnderIO-1.10.2-3.1.179
  Excore-1.6.2-1.10.2
  FastLeafDecay-v11
  FinderCompass-1.10.2
  foamfix-0.6.2-beta2-anarchy
  GiacomosFishingNet1.10.2-1.4.4
  iChunUtil-1.10.2-6.2.0
  IGW-Mod-1.9.4-1.3.0-5-universal
  ImmersiveEngineering-0.10-57
  InventoryTweaks-1.62-dev-66
  jei_1.10.2-3.14.7.417
  journeymap-1.10.2-5.4.6
  JustEnoughResources-1.10.2-0.5.9.3
  limelib-1.10.2-1.5.3
  LLOverlayReloaded-1.1.1-mc[1.9-1.11]
  malisisblocks-1.10.2-4.2.0
  malisiscore-1.10.2-4.4.0
  malisisdoors-1.10.2-5.2.0
  mcjtylib-1.1x-2.3.11
  MCMultiPart-1.4.0-universal
  MineTweakerRecipeMaker-1.10.2-1.2.1.26
  MoarSigns-1.10.2-4.2.2.8
  NaturesCompass-1.10.2-1.3.0
  netherportalfix-mc1.9.4-4.0.1
  OpenGlider-1.10.2-0.2.3
  PersistentBits-1.10.2-1.0.6
  platforms-1.10.0-1.2.9
  ReapMod 1.3.3
  RebornCore-1.10.2-2.13.5.136-universal
  RebornStorage-1.10.2-1.0.2.29
  rflux-0.1.0
  RTG-1.10.2-4.1.2.4
  SeedCopy-1.9-3.0.2
  shetiphiancore-1.10.0-3.3.8
  Signals-1.10.2-0.5.1-universal
  SimplyCaterpillar-Forge-6.0.1.22
  SimplyJetpacks2-1.10.2-2.1.0.39
  StorageDrawers-1.10.2-3.7.0
  theoneprobe-1.1x-1.4.5
  Torched-1.10.2-6.0.0
  UniDict-1.10.2-2.8
  usefulrecipes-2.1.0.0-HOTFIX-1
  ViesCraft-1.10.X-4.26.13
  VillageInfoMod-1.10.2-8
  WanionLib-1.10.2-1.3

Does this issue occur on a server? [yes/no]

N/A Using single player

**Comment by raoulvdberge** [comment] 2017-04-15 22:24
If you broke the storage block and had it in your inventory, the disappearing of items is due to a Forge bug that has been reported before. This is not an RS issue.

Duplicate of #821

See https://github.com/MinecraftForge/MinecraftForge/issues/3682

**Closed by raoulvdberge** 2017-04-15 22:24 UTC
