### ISSUE TITLE
cant put the detector number above 28

### ISSUE THREAD

**Issue by DnTheMn** [raoulvdberge/refinedstorage#211] opened 2016-07-20 04:09 UTC
the detector isnt working too well it was fine and then i moved it and now it wont go above 28 and even if its set to emit if less than 28 in the system it will still emit signal im on all the mods (1.10.2 v1.4) and the refined storage version is 0.8.10

**Comment by raoulvdberge** [comment] 2016-07-26 01:40
Probably a duplicate of #199

**Closed by raoulvdberge** 2016-07-26 01:40 UTC
