### ISSUE TITLE
Autocrafting a RS interface fails while running with the latest (beta 1.10-1.10.2-1.2.1) DW20 mod pack.

### ISSUE THREAD

**Issue by Theodosis** [raoulvdberge/refinedstorage#793] opened 2016-12-27 23:39 UTC
#### Issue description:
The autocrafting system is getting stuck into the "Machine in use" phase while trying to craft the RS interface on a Crafter+Solderer. 

#### What happens:
The crafting monitor says: Machine in use.

#### What you expected to happen:
The autocrafting should go through and create the interface.

#### Steps to reproduce:
1. Setup a basic RS storage configuration (controller, grid, disk storage+disk, crafting monitor).
2. Connect a Crafter+solderer and add an interface pattern into the crafter.
3. Provide the RS system with an importer, and exporter and a basic processor.
4. Request an interface.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.14
- DW20 mod pack: 1.10-1.2.1-1.10.2 (beta)

Does this issue occur on a server? no

It should be noted that this issue only occurs in the DW20 pack. The crafting is working fine in a MC+RS build.

**Comment by raoulvdberge** [comment] 2016-12-28 03:51
Having the same issue on 1.11. It can insert to an empty chest, but not to a vanilla furnace, then it just says "machine in use".

**Comment by Joshwoo70** [comment] 2016-12-28 03:53
maybe it is side orientated?

**Comment by Theodosis** [comment] 2016-12-28 07:54
@Joshwoo70, I tried it with the top and one of the sides. If you think it might be related I can try the rest of the sides and the bottom. Also, I should mention that this only happens with the interface, everything else that I autocraft works as expected. I will try to pinpoint the exact mod(s), if any, that are introducing this behavior and get back to you.

**Comment by way2muchnoise** [comment] 2016-12-31 21:29
I can't reproduce it any more. It might be fixed in one of the other commits I made today.

**Closed** 2017-01-03 12:40 UTC
Labels: autocrafting, bug, can't reproduce
