### ISSUE TITLE
Filter item doesnt work anymore

### ISSUE THREAD

**Issue by bufu1337** [raoulvdberge/refinedstorage#2244] opened 2019-05-17 21:18 UTC
hi, i have updated to the newest version 1.6.14 and now the filter item doesnt work correctly... he recognizes the filter item as a normal item and not as a filter. so when i have the filter item in a whitelist in an importer he only sucks in the a filter item and not whats in the filter... in the previous versions when i put in the filter then the filter was not in my inventory anymore... now it is still in my inventory... 
breaks many things in my world this bug... :(

**Comment by Darkere** [comment] 2019-05-18 09:12
duplicate of #2177 and #2116 and #1939
please search for existing issues before reporting.

**Comment by bufu1337** [comment] 2019-05-20 08:43
Ah ok sorry... i searched only in open issues...

But the issues was for im/exporter and alsonot solved... my problem is that they dont work in disk drives too... so overall the filter item has no function anymore and i can only whitelist 9items for a diskdrive... thats bad... so delete the filter item in the next version... it has no funtion

**Comment by raoulvdberge** [comment] 2019-05-20 09:17
It can be used to filter grid views.

**Closed** 2019-05-20 09:17 UTC
