### ISSUE TITLE
Auto craft crash

### ISSUE THREAD

**Issue by phantom1151** [raoulvdberge/refinedstorage#2188] opened 2019-03-02 16:57 UTC
#### Issue description:
as soon as i start an auto craft the server lags till it crashes
#### What happens:
the server ping takes 60 sec and then shutsdown
#### What you expected to happen:
auto craft work
#### Steps to reproduce:
1. 
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2808
- Refined Storage: 1.6.12

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:
Time: 3/2/19 11:46 AM
Description: Watching Server

java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.getCraftingMonitorElements(CraftingTask.java:1074)
	at com.raoulvdberge.refinedstorage.network.MessageCraftingMonitorElements.toBytes(MessageCraftingMonitorElements.java:80)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26)
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:81)
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250)
	at com.raoulvdberge.refinedstorage.container.ContainerCraftingMonitor.onChanged(ContainerCraftingMonitor.java:96)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingManager$$Lambda$2036/215086555.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingManager.onTaskChanged(CraftingManager.java:226)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.updateProcessing(CraftingTask.java:779)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.update(CraftingTask.java:882)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingManager.update(CraftingManager.java:172)
	at com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:211)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.getCraftingMonitorElements(CraftingTask.java:1074)
	at com.raoulvdberge.refinedstorage.network.MessageCraftingMonitorElements.toBytes(MessageCraftingMonitorElements.java:80)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26)
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:81)
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250)
	at com.raoulvdberge.refinedstorage.container.ContainerCraftingMonitor.onChanged(ContainerCraftingMonitor.java:96)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingManager$$Lambda$2036/215086555.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingManager.onTaskChanged(CraftingManager.java:226)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.updateProcessing(CraftingTask.java:779)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.update(CraftingTask.java:882)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingManager.update(CraftingManager.java:172)
	at com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:211)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[pastebin/gist/etc link here]

**Comment by phantom1151** [comment] 2019-03-03 02:12
found out that the crash was caused by refined storage crafter not liking the mystical agriculture furnaces. it is still a bug but not totally with the mod just mod compatibility

**Comment by raoulvdberge** [comment] 2019-03-04 13:15
Duplicate of #2132

**Closed by raoulvdberge** 2019-03-04 13:15 UTC
