### ISSUE TITLE
Autocrafting making a mess with cutting tool creating too many of them

### ISSUE THREAD

**Issue by LuciusV** [raoulvdberge/refinedstorage#1965] opened 2018-08-26 02:59 UTC
#### What happens:
Autocrafting of several processors makes many cutting tools 

#### What you expected to happen:
Only one crafting tool is produced and used until end of its durability

#### Steps to reproduce:
1. Make crafting and patterns enough to autocraft any RS processors and try to autocreate several
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2705
- Refined Storage: 1.6.3

**Comment by LuciusV** [comment] 2018-08-26 03:00
IMHO using a solderer was way better way, this cutting tool is annoying as hell

**Comment by DarkKostas** [comment] 2018-08-26 15:34
It's about time to support damaged tools on auto crafting...

**Comment by raoulvdberge** [comment] 2018-08-26 16:46
The autocrafting does support damaged tools, only not in a good way. If it didn't support it at all, it would make a new tool for every processor it wants, which currently, it doesn't.

**Comment by raoulvdberge** [comment] 2018-08-27 19:40
This is essentially a duplicate of #1961.

**Closed by raoulvdberge** 2018-08-27 19:40 UTC
