### ISSUE TITLE
Controller causing issues

### ISSUE THREAD

**Issue by KappaKiddie** [raoulvdberge/refinedstorage#1195] opened 2017-04-30 19:36 UTC
Description: When the controller receives and loses RF, when energy produce isn't enough, server lags a lot
Steps to reproduce: 
1. Do a controller
2. Produce less energy than you need
3. https://media.giphy.com/media/TVWHseWbLKjte/giphy.gif
4. http://prntscr.com/f2n253

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Refined Storage: 1.2.25

Does this issue occur on a server? Yes

**Comment by raoulvdberge** [comment] 2017-04-30 19:51
http://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by KappaKiddie** [comment] 2017-04-30 20:12
[controller.zip](https://github.com/raoulvdberge/refinedstorage/files/966979/controller.zip)

**Comment by Eufranio** [comment] 2017-05-01 15:02
Same issue as https://github.com/raoulvdberge/refinedstorage/issues/1187

**Comment by coderecess** [comment] 2017-05-10 08:46
I have been having lag issues also.

I have a [timings report](<https://timings.aikar.co/?id=b5477c2c58dd438c90402baa14447694>) and a [sampler file][a].

My server is hosted by CubedHost.  I submitted a support ticket about lag, and they said the source was my RS Controller.  The lag clears up when I break the controller and returns when I place it again.

In addition, I have noticed that the lag disappears when I break the cables to my autocrafters (4-3x3) - separating them from the rest of the RS system.  

![image](<https://cloud.githubusercontent.com/assets/17791090/25889797/1b5eee68-3539-11e7-8c2c-0a93b9233549.png>)
##### (Building is WIP; I am not a good builder! 😃  ) #

[a]: <https://github.com/raoulvdberge/refinedstorage/files/989154/server_lag.zip>

**Comment by coderecess** [comment] 2017-05-10 09:30
Here are some stall reports.  I didn't have Sampler started, but maybe these can help.

<https://pastebin.com/NLdmwfXY>
<https://pastebin.com/92qHdQWV>
<https://pastebin.com/WFPn5wdv>

**Comment by coderecess** [comment] 2017-05-11 04:56
I have the most problems when I'm in an area away from from main RS system.  I use a Network Transmitter and Network Receiver to link the two locations.  The distance is 201 blocks as reported by the Network Transmitter.

Below is a screenshot of the remote location.  The only RS components at this location are the Receiver, Crafting Grid, cable, and Wireless Transmitter with 4 Range Upgrades.  I carry in my inventory a Wireless Grid, Wireless Crafting Monitor, and extra cables.  Yet, this remote location is the only place that actually crashes the server.  Extreme lag is usually the worst case scenario in all other locations.

The server has crashed 3 or 4 times tonight; the first two times I was using Sampler.  I haven't tried again to get another Sampler report.  Let me know if you want another one and I will try again.

![image](https://cloud.githubusercontent.com/assets/17791090/25933344/f8107a5c-35e3-11e7-8d0f-31b93da5b0ae.png)

**Comment by raoulvdberge** [comment] 2017-05-15 19:21
Duplicate of #1187

**Closed by raoulvdberge** 2017-05-15 19:21 UTC
Labels: investigate, performance
