### ISSUE TITLE
Can't fill up inventory crash

### ISSUE THREAD

**Issue by ibdoomed** [raoulvdberge/refinedstorage#1985] opened 2018-09-11 19:54 UTC
#### Issue description:
I was deploying an EnderIO smelter with an RS crafter. The system was all setup, connected to RS, had an importer on the smelter with power and cap. I put the recipe for pulsating iron in the crafter and the game crashed. It now crashes before loading is complete. The recipe was valid as it was working before moving it from one crafter to the new one.

#### What happens:
The game crashes at loading (freezing/not responding).
#### What you expected to happen:
n/a
#### Steps to reproduce:
Not sure how to fix it so I can get the world running to try and reproduce.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge:2755
- Refined Storage: 1.6.4

Does this issue occur on a server? [yes/no]
no

#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/WmJiFrnD

This is the crash report file, let me know if you need any other logs.

**Comment by raoulvdberge** [comment] 2018-09-11 20:45
Duplicate of #1983

**Closed by raoulvdberge** 2018-09-11 20:45 UTC
