### ISSUE TITLE
ItemID support?

### ISSUE THREAD

**Issue by ray73864** [raoulvdberge/refinedstorage#2371] opened 2019-12-11 01:18 UTC
Not sure if it already supports this or not, but playing Dungeons, Dragons and Space Shuttles (1.12), one of the recipes is Tech Reborn gems into Liquid Crystaltine.

Currently my pattern is set up to go from Tech Reborn Ruby Gems to Liquid Crystaltine, when I run out of rubies the system won't let me make more LC, but I still have plenty of Sapphires and Peridots in my network, both of which can be used to make LC.

Looking at their information (F3+H), all 3 gems have the ItemID of 'TechReborn:gem', and oreDict of 'gemRuby', 'gemSapphire', and 'gemPeridot'.

As far as I know, when I create a pattern, all I can do is tell it 'ore dictionary', would be nice if I could tell it 'Item ID', then it'll use all 3 gems to make the liquid.

**Comment by Darkere** [comment] 2019-12-11 12:51
Duplicate of #2335

**Closed** 2019-12-11 17:12 UTC
