### ISSUE TITLE
Local Hosted Server Stopped Responding From A RS Issue?

### ISSUE THREAD

**Issue by Genesteeler** [raoulvdberge/refinedstorage#1161] opened 2017-04-13 17:38 UTC
#### Issue description: 
Locally hosted server is not responding to commands or login requests. I was placing a crafter down attached to my refined storage system via a long cable and then the server stopped responding. Looking at Task Manager the server used, before this issue, about 5GB of ram which is what I had allocated. Now it slowly climbs to the new allocation set at 16GB and still no response. I did notice after updating modpack version from v2.52 to v2.53 (current) a second delay, sometimes longer, was added to grid interaction with crafting and removing/adding items to the system.

Removing Refined Storage from the modpack allows you to enter the world. Tried updating to 1.2.25 but it didn't change anything. Backdating to 1.2.22 didn't help either. Removed FTBUtils to remove chunkloading and that allows me to finishing loading the server and join it. After joining and loading chunks it stalls out instantly. Getting onto the server shows that the crafter didn't save.

#### What happens: 
Trying to log onto the server gives me a timed out message. Server is not responding to commands in the cmd window. It does see the UUID request but doesn't do anything with it.

#### Steps to reproduce:
Can't reproduce but might be able to see if a backup world with a similar addition to the refined storage system will give me this issue.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Refined Storage: 1.2.24

Modpack
- All the Mods v2.53

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:
Can't do /sample start for the nps file.

Stall report
https://pastebin.com/X5kRBqHe

There are multiple stall reports at different intervals. I can post them if needed.

I can get you a nps file without any chunks loaded. Unable to do start the sampler while chunks are loaded.

**Comment by raoulvdberge** [comment] 2017-04-14 11:10
A crafting task initiated by the crafting upgrade is stalling your world

**Comment by sfPlayer1** [comment] 2017-05-20 15:21
FC1 (RS 1.4.6 / MC 1.11) ran across a similar issue yesterday, no idea what the crafting task was since I only have the Sampler reports.

```
Stall report from 2017-05-20 01:34:29 +0000, 54 threads, stalled for at least 240000 ms.
Heap memory usage: 4881 / 6187 MB (max. 7635 MB).
Created by sampler 1.70 (MC 1.11.2).

"Server thread" #17 prio=5
RUNNABLE
        at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.validateIterator(AbstractMapBasedMultimap.java:471)
        at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.hasNext(AbstractMapBasedMultimap.java:479)
        at com.raoulvdberge.refinedstorage.apiimpl.util.StackListItem.add(StackListItem.java:25)
        at com.raoulvdberge.refinedstorage.apiimpl.util.StackListItem.add(StackListItem.java:17)
        at com.raoulvdberge.refinedstorage.api.util.IStackList.add(IStackList.java:26)
        at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:266)
        at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:99)
        at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingManager.schedule(CraftingManager.java:244)
        at com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNodeExporter.doExport(NetworkNodeExporter.java:142)
        at com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNodeExporter.update(NetworkNodeExporter.java:79)
        at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeListener.onWorldTick(NetworkNodeListener.java:24)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_358_NetworkNodeListener_onWorldTick_WorldTickEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:269)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:729)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
        at java.lang.Thread.run(Thread.java:745)
```

We have 5 reports for this stall instance (> 8 minutes), the lowest common stack frame is CraftingTask.calculate(CraftingTask.java:99).

**Comment by raoulvdberge** [comment] 2017-05-28 21:06
Duplicate of #838

**Closed by raoulvdberge** 2017-05-28 21:06 UTC
Labels: autocrafting, performance
