### ISSUE TITLE
Solderer sometimes not reacting to redstone

### ISSUE THREAD

**Issue by taleteller** [raoulvdberge/refinedstorage#583] opened 2016-11-05 20:12 UTC
This is a bug i noticed at least since 1.20 early versions. As seen on the screenshot I am using a combination of solderer and detector to precraft certain items like processors and printed silicon. The configuration is like this
Detector: item count < 64 --> go on high
Solderer: high signal -> process

![2016-11-05_20 55 12](https://cloud.githubusercontent.com/assets/1484333/20033166/2d0616d0-a39b-11e6-94d0-e2b69c70329b.png)

However sometimes, like when entering a game, this mechanic is stuck as seen on the screenshot as well. The detector is giving a redstone signal, but the solderer keep holding. I have to manually remove the redstone signal to get the system working as well. It looks like solderer is not reacting to the signal but only to its raising flank. 
As a workaround i inverted the signaling, to make the solderer only working on low, that way it seems to work fine. However it should as well work the other way.

**Comment by raoulvdberge** [comment] 2016-11-05 20:21
duplicate of #370

**Closed by raoulvdberge** 2016-11-05 20:21 UTC
