### ISSUE TITLE
Crash when a lot of destructors are destroyed at once.

### ISSUE THREAD

**Issue by xxMattewxx** [raoulvdberge/refinedstorage#2221] opened 2019-04-17 15:20 UTC
#### Issue description:
When breaking a lot of destructors at once (in my case, w/ Ore Excavation mod), the game crashes. Tested only on single-player, but happens in 100% of the cases when I break more than 10 destructors at once.
Note: The crash happens after loading the game too. My world is stuck :/
#### What happens:
Breaking a lot of connected destructors make the game crash.
#### What you expected to happen:
It not to crash.
#### Steps to reproduce:
1. Make a RS network
2. Place 10 or more destructors linked together.
3. Break all of the destructors at once using Ore Excavation or similar.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2815
- Refined Storage: 1.6.12

Does this issue occur on a server? [yes/no] Ain't able to test it right now. If I get the time, I'll download the server files and test it. Happens on LAN server tho.

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/X08zSguQ

**Comment by raoulvdberge** [comment] 2019-05-20 19:14
Duplicate of #2241

**Closed** 2019-05-20 19:13 UTC
