### ISSUE TITLE
Interface Grid filter requests

### ISSUE THREAD

**Issue by ariosos** [raoulvdberge/refinedstorage#688] opened 2016-11-28 16:42 UTC
For the Grid Filter, there should be a checkbox optoin to filter by mod. So, since of filtering individual items, the item would represent the mod it is from.

**Comment by raoulvdberge** [comment] 2016-11-28 16:45
duplicate of #359

**Closed by raoulvdberge** 2016-11-28 16:45 UTC

**Comment by ariosos** [comment] 2016-11-28 16:47
You're too quick. :p Was just checking changelogs (we're using an old version in a modpack...).
