### ISSUE TITLE
[1.11.2] Pattern don't show certain blocks (with sneak)

### ISSUE THREAD

**Issue by BrisingrAerowing** [raoulvdberge/refinedstorage#1360] opened 2017-07-11 23:52 UTC
#### Issue description:

When sneaking, patterns usually show the what they create. Some things don't show (noticed with Chests and Shulker Boxes).

#### What happens:

The items aren't shown.

#### What you expected to happen:

To see a chest and shulker box.

#### Steps to reproduce:
1. Create a pattern for a chest / shulker box
2. Put it in your inventory
3. Sneak
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 13.20.1.2393
- Refined Storage: 1.4.18

Does this issue occur on a server? [yes/no] Not tested

**Comment by raoulvdberge** [comment] 2017-07-12 00:05
Duplicate of #609

**Closed by raoulvdberge** 2017-07-12 00:05 UTC
