### ISSUE TITLE
[Feature Request] Crafter settings

### ISSUE THREAD

**Issue by bsaksida** [raoulvdberge/refinedstorage#682] opened 2016-11-26 20:16 UTC
I am automating empowerer from actually addition. Impowerer is complicated crafting mechanic, where i collect items. Currently i would need to create for every empoweer crafting its own setup, due to item handling.

Is it possible to add a setting to a crafter, that atemps to craft 1 item and wait till finish, then contiune next.

I had item mixup because 2 diffrent recepies.

**Comment by raoulvdberge** [comment] 2016-11-26 22:56
This is a duplicate of #485

**Closed by raoulvdberge** 2016-11-26 22:56 UTC
