### ISSUE TITLE
[0.8.19] Config entry for I:wirelessTransmitter energy does not affect Wireless Grid using energy

### ISSUE THREAD

**Issue by PrinceOfAmber** [raoulvdberge/refinedstorage#268] opened 2016-08-14 21:16 UTC
Version: refinedstorage-0.8.19.jar

In the config file, i set 

 I:wirelessTransmitter=0

(actually in my case, i am testing it out with every single energy level at zero, for a modpack that has no RF or energy)

Then i craft a wireless grid.  It has zero energy, but thats okay, and it wont open.  In creative mode, if i grab a fully charged Wireless Grid, using it does drain its energy. (i have no way to charge it anyway)

So my guess is either this config entry has a bug, or maybe this config entry means something else?

Or perhaps is there no config entry for the energy level used by the Wireless Grid?  Can you please either add a config for the wireless grid energy use, or tie it to this entry?  Or maybe it makes sense to bind it to the config entry "I:grid=0"

**Comment by raoulvdberge** [comment] 2016-08-14 23:05
duplicate of #263

**Closed by raoulvdberge** 2016-08-14 23:05 UTC
