### ISSUE TITLE
Storage disk getting rejected from drive?

### ISSUE THREAD

**Issue by SomewhatOfAGuy** [raoulvdberge/refinedstorage#702] opened 2016-12-03 05:39 UTC
#### Steps to reproduce:
1. Have creepers blow up your drive with disks, then put disks back into a new drive
2. Repeat process until disks get rejected
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2 (all the mods lite, with updated Refined Storage)
- Forge: 12.18.2.2151
- Refined Storage:1.2.8

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment] 2016-12-03 12:14
I can't reproduce this on the latest version. Are you sure you updated correctly? Check in the Forge modlist ingame if you're actually running 1.2.8.

**Comment by SomewhatOfAGuy** [comment] 2016-12-03 18:55
Yeah, I checked and it's version 1.2.8 on my client and server. The drives were fully stocked if that helps you.

**Comment by raoulvdberge** [comment] 2016-12-03 19:05
Any logs when this happened?

**Comment by SomewhatOfAGuy** [comment] 2016-12-03 19:07
It doesn't seem so, if you want to you can do some stuff on the server, and help out.

**Comment by aelfwyne** [comment] 2016-12-07 00:53
Updating doesn't help if it erases the existing disks. You need to figure out WHY this is happening and offer an update that actually works with the broken disks to recover items, or at least admit it's broken.

**Comment by raoulvdberge** [comment] 2016-12-07 12:24
Duplicate of #712

**Closed by raoulvdberge** 2016-12-07 12:24 UTC
Labels: bug, can't reproduce
