### ISSUE TITLE
Dynamic JEI synchronization

### ISSUE THREAD

**Issue by Towdium** [raoulvdberge/refinedstorage#483] opened 2016-10-18 16:52 UTC
Since I wrote a little mod to tweak the filtering behavior of JEI (you can find it [here][1]), I find the item filtering behavior is not synchronized with JEI any more. I think it would be better if RS can do JEI synchronized search using interface provided by JEI to improve the compatibility.

As far as I know, you can use `new ItemFilter(registry.getItemRegistry()).getItemList()` to get the filtered item list, in which `registry` is the `IModRegistry` passed to your `IModPlugin` in method `register`. It seems work fine, but it's not widely tested. Otherwise maybe you can reflect the itemFilter in ItemListOverlay to do this for better performance.

[1]: https://minecraft.curseforge.com/projects/just-enough-characters

**Comment by raoulvdberge** [comment] 2016-10-20 17:14
RS uses the JEI API `IItemListOverlay#setFilterText` method. Shouldn't your mod work on that?

**Comment by Towdium** [comment] 2016-10-20 18:55
I mean it's not the text that is not synchornized, but the stacks displayed. When my mod is installed, JEI could display different stacks for the same string compared to the original behavior. But when I am in JEI synchornized mode, the searching string is synchornized but the stacks displayed is not filtered the same as JEI do. If you want to know more, that mod only has effect when language is set to Chinese.

Got some pictures for demonstration. Firstly, I put some crafting table to the system:
![2016-10-20_19 51 54](https://cloud.githubusercontent.com/assets/10866568/19573606/dd03faec-96fe-11e6-9a51-e8666f2b64e0.png)

And edit the string. Crafting cable is still in JEI' list, but not displayed in the grid.
![2016-10-20_19 52 02](https://cloud.githubusercontent.com/assets/10866568/19573660/159eb8ce-96ff-11e6-981b-9301e7a7e454.png)

**Comment by raoulvdberge** [comment] 2016-10-20 18:57
You confused me, because RS doesn't use JEI logic for display stacks. It just modifies the search bar text. In that case, this is a duplicate of #482

**Closed by raoulvdberge** 2016-10-20 18:57 UTC
Labels: feature request
