### ISSUE TITLE
Construction core color

### ISSUE THREAD

**Issue by Deshiba** [raoulvdberge/refinedstorage#875] opened 2017-01-16 10:14 UTC
Currently it's pretty hard to keep construction cores and advanced processors apart due to similar colours. Its my first time with the mod, crafting a grid and I made an advanced processor because of the "blue" but only saw there was a difference when hovering the item afterwards. Side by Side comparison:

![2017-01-16_11 04 04](https://cloud.githubusercontent.com/assets/10565800/21978802/77491624-dbdc-11e6-879c-f2cc7ee3b136.png)

Could you make the construction core texture be Emerald Green?

**Comment by way2muchnoise** [comment] 2017-01-16 10:23
Duplicate of #811

**Comment by CyanideX** [comment] 2017-01-17 03:36
Am I the only one who thinks they're very clearly different? I'm color blind and even I can tell them apart at a glance. :P

**Comment by Joshwoo70** [comment] 2017-01-17 06:13
looks you got like green blue colour blindness...
it to me looks likd blue.

**Comment by Deshiba** [comment] 2017-01-17 08:30
They look the same at first glance. But it doesn't matter. If the author doesn't want to change it for clarity sake then people can just go the texture pack route:

![compare](https://cloud.githubusercontent.com/assets/10565800/22013084/82177d8c-dc97-11e6-83c4-9724b2ec32e7.png)

**Comment by CyanideX** [comment] 2017-01-17 19:34
I have red-green color blindness @Joshwoo70. If anything, the teal would be more saturated than it appears to me.

You're right though, at first glance it may appear similar and I think I will be changing the design slightly to indicate a different core type; however, you can't tell me that these are the same color. 😛 

![Colors](http://i.imgur.com/9pi9ELa.png)

**Comment by Joshwoo70** [comment] 2017-01-18 00:32
@cyanideX nah they ain't the same colour even though i have slight colour blindness. but a more like lime green colour will be nice. it now looks like light turquoise...

**Comment by Deshiba** [comment] 2017-01-18 06:59
The are not the same at all. But with the grey around it, the size they are in game and no prior knowledge of the mod they look so similar in hue as to easily mistake them for each other.

Imo, changing it would be good. But as mentioned, texture packs are a thing.

**Comment by CyanideX** [comment] 2017-01-18 07:10
Is this any better?

![Changes](http://i.imgur.com/FVrDvwp.png)

**Comment by CyanideX** [comment] 2017-01-18 07:16
Or how about this? Colored rings.

![Colored Rings](http://i.imgur.com/wgxeI06.png)

**Comment by Deshiba** [comment] 2017-01-18 07:19
The colored rings look cool, could you do the same for the processor? Also it looks fine on here but in game might be different.

**Comment by CyanideX** [comment] 2017-01-18 07:22
In my opinion, it looks slightly more obvious. What do you think?

![Better?](http://i.imgur.com/MpioK2C.png)

**Comment by Joshwoo70** [comment] 2017-01-18 07:29
yeah it does :D could someone reopen this issue?

**Comment by CyanideX** [comment] 2017-01-18 07:30
No need. I'll just add them to the next version.

**Comment by Deshiba** [comment] 2017-01-18 07:30
Adding the ring around all of them would help to distinguish the even more.

**Comment by Joshwoo70** [comment] 2017-01-18 07:31
also.. i think the construction core should be green instead of blue. green is the direct opposite of red which makes it able to contradict well.. blue.. ehh not so much... as it is the opposite of orange instead.

**Comment by CyanideX** [comment] 2017-01-18 07:53
@raoulvdberge made it very clear that [he likes his blues](https://github.com/raoulvdberge/refinedstorage/issues/811#issuecomment-272718019) so we won't be making anything green. That would require the panel itself to also be made green and would not fit well alongside the blues of RS.

**Comment by Joshwoo70** [comment] 2017-01-19 01:15
issue with blue is that it is not the opposite of red >_>

**Comment by CyanideX** [comment] 2017-01-19 02:31
That means absolutely nothing. Why does it have to be opposite colors on the color wheel? Most multiplayer games have red team and blue team. The only exception I can think of is Rocket League which has blue and orange. Maybe I'll make the Destructor orange-ish.

**Comment by raoulvdberge** [comment] 2017-01-19 17:58
Your changes are ok.

**Closed by raoulvdberge** 2017-01-19 17:58 UTC
Labels: duplicate
