### ISSUE TITLE
External Storage and Storage Drawers

### ISSUE THREAD

**Issue by DracoClaw** [raoulvdberge/refinedstorage#2174] opened 2019-02-06 00:01 UTC
#### Issue description:
External Storage looses connection to Storage Drawers drawer controller every time i sign on.
#### What happens:
When I sign back in, the external storage is still there, but it wont recognize the drawer controller.
#### What you expected to happen:
I expect that all the items in drawers would still appear. 
#### Steps to reproduce:
1. Have External Storage on a Drawer Controller
2. Sign out
3. Sign back in
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2772
- Refined Storage: 1.6.12

Does this issue occur on a server? [yes/no]
No

**Comment by Darkere** [comment] 2019-02-06 00:05
Duplicate of #2120. Check there for some potential solutions.

**Closed** 2019-03-04 13:03 UTC
