### ISSUE TITLE
System not updating correctly w/ Storage Drawers hooked up

### ISSUE THREAD

**Issue by vlce-versa** [raoulvdberge/refinedstorage#515] opened 2016-10-25 16:02 UTC
#### Issue description:
I have a Storage Drawers inventory system hooked up to RS and every now and then the system kinda hangs, for example when I click the redstone mode on the RS Controller it does not change, only when I close the interface of the it and reopen it again. Sometimes I have to completely remove the RS Controller and place it back, but then I have to reconnect all Importers. Maybe I have to mention that my Storage Drawers inventory consists of about 400 individual inventories and the distance from the Drawer Controller to the RS Controller is about 20 blocks.
#### What happens:
see above
#### What you expected to happen:
working like a charm :)
#### Steps to reproduce:
1.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.2.2107
- Refined Storage:1.1.3

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment] 2016-10-25 16:03
this is a duplicate of another issue

**Closed by raoulvdberge** 2016-10-25 16:03 UTC
