### ISSUE TITLE
RS system does not seem to uphold priorities set

### ISSUE THREAD

**Issue by Sovereignty89** [raoulvdberge/refinedstorage#920] opened 2017-01-25 15:19 UTC
#### Issue description: 
The RS system does not seem to uphold priorities set

#### What happens: 
I have a room with Quantum Storage Units, I have placed External Storages on all of these. I have configured the External Storages to the correct item and at first I gave them all priority 10 but now that is set to 100 (doesn't make a difference). These QSU hold items that I gather from mining and chickens (Skyfactory 3). So a large influx of items and they all go nicely in to the QSUs they are supposed to go. Now I want to use my RS to store other items, in smaller quantities, I want it to have room for things I have my RS system craft etc. So I decide to add a Disk Drive set to priority 1 (tried 0, -1, -9999. Doesn't make a difference). Now what happens? Every once in a while, items end up on said drives even though they have a dedicated QSU with a higher priority. This results in the drives slowly filling and no more room being left for things my system crafts or other small things I want to store.

#### What you expected to happen: 
I expect the system to put all the items that belong in a QSU in to a QSU because the priority is said to be higher than the drives. Not have my drives fill and become useless unless I keep putting the drives in to the Disk Manipulator to have the system empty them in to their respective QSUs

#### Steps to reproduce:
1. Create a RS system.
2. Have only a QSU and connect it to your RS system via External Storage.
3. Set the External Storage to the item you want to have stored in said QSU.
4. Set the priority high.
5. Have the item that belongs in your QSU enter your RS system rapidly. (I use Dimensional Transceivers with Importers)
6. Wait till your QSU fills a bit.
7. Now build a Disk Drive and add a disk.
8. Set the priority low
9. Have the item that belongs in your QSU enter your RS system rapidly. (I use Dimensional Transceivers with Importers)
10. See your drive slowly fill up with items that should be in your QSU.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2215
- Refined Storage: 1.2.17

Does this issue occur on a server? [yes]

#### If a (crash)log is relevant for this issue, link it here:

I made a post on the FTB subreddit asking if anyone else ran in to this problem. I made a set of pictures to better explain the problem. http://imgur.com/a/7uhVx (https://redd.it/5prmlt)

**Comment by raoulvdberge** [comment] 2017-01-28 15:34
Duplicate of #370

**Closed by raoulvdberge** 2017-01-28 15:34 UTC
Labels: bug, duplicate
