### ISSUE TITLE
Crashing trying to load world

### ISSUE THREAD

**Issue by TheUnderTaker11** [raoulvdberge/refinedstorage#1056] opened 2017-03-12 21:56 UTC
#### Issue description:
Crash on trying to load world
#### What happens:
When I try to load the world, I get a NPE crash, something to do with autocrafting
#### What you expected to happen:
The game not crashing
#### Steps to reproduce:
No idea, can't load into world to test.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.3.2239
- Refined Storage: Lastest version, refinedstorage-1.2.23

Does this issue occur on a server? [yes/no] I'm on SP

#### If a (crash)log is relevant for this issue, link it here:

[Crash Report](http://pastebin.com/an38Nhgs)

**Comment by raoulvdberge** [comment] 2017-03-12 22:02
Seems to be an autocrafting issue indeed. I recommend removing the controller block through MCedit for now to be able to get your world open again, or toggling the "remove erroring tile entities" option with Forge.

**Comment by TheUnderTaker11** [comment] 2017-03-12 22:03
Alright thanks I did look further and saw the exact block was the controller, but I didn't know forge had that option.

**Comment by TheUnderTaker11** [comment] 2017-03-13 02:42
I should also say I went into MCEdit, removed the controller, then got in my world and place a new one down, and it worked fine until I closed out of the world. When I tried to come back I got the same exact crash

**Comment by TheUnderTaker11** [comment] 2017-03-13 03:50
Update: Breaking and re-placing all the crafters I had moved with Not enough wands' moving wand fixed the problem. I followed a hunch and it paid off, so you should test out moving crafters with those wands to reproduce the problem

**Comment by raoulvdberge** [comment] 2017-04-04 13:11
Duplicate of #1016

**Closed by raoulvdberge** 2017-04-04 13:11 UTC
Labels: autocrafting, bug
