### ISSUE TITLE
Cant see items on both a crafting grid or grid

### ISSUE THREAD

**Issue by slowbugatti** [raoulvdberge/refinedstorage#2326] opened 2019-10-14 05:36 UTC
#### Issue description:
i had just switched from applied energetics 2 to refined storage and i made the grid and the disk holder with the controler powered it and i put my items in and saw nothing in the grid i made a crafting grid same problem
#### What happens:
cant see the itmes
#### What you expected to happen:
to see the items
#### Steps to reproduce:
1. i honestly dont know
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:  1.12.2
- Forge: 1.12.2-14.23.5.2838
- Refined Storage:1.6.15

Does this issue occur on a server? [yes/no] nope

#### If a (crash)log is relevant for this issue, link it here:
none
[pastebin/gist/etc link here]
none

**Comment by slowbugatti** [comment] 2019-10-14 06:12
restarted pc and minecraft nothing worked also idk how to reporduce this i can give a list of mods i use if needed

**Comment by Darkere** [comment] 2019-10-14 09:02
Duplicate of #2279

**Comment by slowbugatti** [comment] 2019-10-14 09:12
well yes but i have 64 k disks and its ssp

**Closed** 2019-10-14 09:17 UTC

**Comment by slowbugatti** [comment] 2019-10-14 09:35
just tryed deleting my player.dat did nothing to help

**Comment by Darkere** [comment] 2019-10-14 09:51
To delete player data in singleplayer you need to edit the level.dat and delete the player data in there in addition to the UUID.dat in the playerdata folder. 

And sorry I misread your second message. Check your disk drives do the disks show 0/0 or something else?

**Comment by slowbugatti** [comment] 2019-10-14 09:54
uh no so they show a 4k out of 64k on the first drive and i put that in my disk maniplulator that extsanges the items to another drive and it sent the items to that disk but nothing happned and all i have going into it constently are my roost chickens i can send a vid of my set up if needed in the world

**Comment by Darkere** [comment] 2019-10-14 10:00
Hmm, now you have me doubting whether all the issues of this that I remember were on servers.

Try deleting player data properly.

To delete player data in singleplayer you need to edit the level.dat with NBTExplorer and delete the player data in there and also the UUID.dat in the playerdata folder. If either is left the data will just be restored.

**Comment by slowbugatti** [comment] 2019-10-14 10:01
okay ill try that

**Comment by slowbugatti** [comment] 2019-10-14 10:10
done about to start it up again

**Comment by slowbugatti** [comment] 2019-10-14 10:19
yeah nothing deleted everything you told me to and it still shows empty in the grids but taking up space on the disks such as 64k/64k drive 1 24k/64k frive 2 0/64k drive 3 0/64 drive 4

**Comment by slowbugatti** [comment] 2019-10-14 10:27
do you know like any posible mods that may be causing this because i can send you a screen shot of my mods

**Comment by Darkere** [comment] 2019-10-14 10:50
No. While it's possible that another mod is responsible I do not know any that would mess with that part of the mod. 

Some things to try: 
- create a separate system some chunks away and check if the problem persists.
- make a new world and check if the problem exists here
- move the world to a server and see if it persists

**Comment by slowbugatti** [comment] 2019-10-14 10:57
okay ill load it up again and try the first 2 and then try to do #3 latter when im not tired

**Comment by slowbugatti** [comment] 2019-10-14 11:06
worked in seperate wolrd worked in same world i did one in nether and tried 1 10 chunks away didnt work then 30 and then it worked keep in mind my render distance was ay 15

**Comment by slowbugatti** [comment] 2019-10-14 11:07
oh also i went back grabed the 2 disks and put them in the nether one they worked then the 30 chunks away one that worked but when put back in the origginal didnt work till i reloged and destroyed the setup reloged then rebuilt it
