### ISSUE TITLE
Feature request: Private networks.

### ISSUE THREAD

**Issue by TheKrister2** [raoulvdberge/refinedstorage#1149] opened 2017-04-09 19:12 UTC
Feature request: Able to make RS network private.

While playing with my friends is fun, I am terribly paranoid and I wish I could make my Refined Storage network private to only me or being able to allow a few other chosen users access. Mostly I want this because I'm paranoid, but also because some of my friends have the tendency to "borrow" items without asking me, which I don't like at all.

It would be nice to be able to make a network private to one or more players, maybe by specifying the player name?

Hopefully this is feasible in some way without having to do a major rewrite of code.

**Comment by BrianEdmonds** [comment] 2017-04-09 19:48
My understanding is that this is supported in 1.11, and there are no 
plans to backport it to 1.10.

**Comment by way2muchnoise** [comment] 2017-04-09 19:49
duplicate of #1148

**Closed by way2muchnoise** 2017-04-09 19:49 UTC
