### ISSUE TITLE
Lost all items and grid became unuseable

### ISSUE THREAD

**Issue by Symbai** [raoulvdberge/refinedstorage#1337] opened 2017-06-30 15:43 UTC
#### Issue description:

When leaving the chunk using teleporter and coming back, I lost all items in my grid.
The 64k storage disks show that items are stored in it but the grid is completely empty and I cannot put items in it as well. It reacts like if its out of energy but energy bar in controller is full.

#### Steps to reproduce:

This is reproduceable on my end. Not sure if you can reproduce it.

1. Put items in grid
2. Teleport away using Journal Map mod or just walk away for a great distance
3. Teleport back using Journal Map mod or walk back
4. All items in grid are gone. Grid is completely empty and unusable.

Some additional information:
Playing singleplayer with cheats.

**However when I save, close and then load the world all items are back in grid and grid is useable.
So it seems to be a temporarily problem.**

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 14.21.1.2387
- Refined Storage: 1.5.6

Does this issue occur on a server? [yes/no]

No idea, I dont play on servers.

**Comment by raoulvdberge** [comment] 2017-06-30 16:38
Yes and where is your crashreport?

**Comment by Symbai** [comment] 2017-06-30 18:52
I can only submit a crash report if a crash has occured. This is a bug, not a crash report.

**Comment by raoulvdberge** [comment] 2017-06-30 19:06
Wait, and what if you break & re-place the controller?

**Comment by chooven** [comment] 2017-07-01 05:55
Have the same bug, if you remove an replace one of your discs everything comes back for me

**Comment by raoulvdberge** [comment] 2017-07-01 07:58
Duplicate of #1259

**Closed by raoulvdberge** 2017-07-01 07:58 UTC
