### ISSUE TITLE
Disk manipulator emptied a disk to -448/64000

### ISSUE THREAD

**Issue by tivec** [raoulvdberge/refinedstorage#520] opened 2016-10-25 17:29 UTC
#### Issue description:

I'm not quite sure what happened here, I have an EnderIO conduit feeding the disk manipulator for emptying the contents into the system. I have an EnderIO conduit extracting empty disks (match NBT data). When I came to the disk manipulator I found a disk with -448/64000 available space in it.

http://i.imgur.com/6KAb7aB.png
#### Version (Make sure you are on the latest version before reporting):
- Minecraft: 1.10.2
- Forge: 12.18.2.2112
- Refined Storage: 1.2-beta2

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

No log

**Comment by tivec** [comment] 2016-10-25 17:37
And it just created one with -192/64000.. Here's the NBT info:
http://i.imgur.com/F3QQeFm.png

**Comment by tivec** [comment] 2016-10-25 18:41
I piped 40 disks with different contents and amounts total through the Disk Manipulator, and ended up with 29 normal empty disks (0/64000) and 11 disks with varying negative numbers.

**Comment by raoulvdberge** [comment] 2016-10-25 18:46
Can you try with just shift clicking manually (without the pipes) and see if it works that way?

**Comment by tivec** [comment] 2016-10-25 18:47
The disks go into the correct slot and start emptying out properly, it seems to be some form of overflow or such during the emptying process. Also, the first disk with the error was left within the Disk Manipulator since the NBT didn't match.

**Comment by tivec** [comment] 2016-10-25 18:51
More testing on this issue:
I set up a small RS system with just a disk drive, a crafting grid and a controller to run the test. The disk drive reports -1216/64000 (that is also the disk info):
http://i.imgur.com/HLJYrJb.png

After adding 1 stack of cobblestone:
http://i.imgur.com/f0Al8xo.png

**Comment by RealGrep** [comment] 2016-10-27 19:25
Wonder if the count went out of whack due to the other now fixed issue with it counting multiple imported items in a stack as one item. Just a shot in the dark. Wonder if it still does that with beta4.

**Comment by tivec** [comment] 2016-10-27 21:05
I don't know, but I could set up my system to empty out again, see if I get
any corrupted drives.

Just a thought though, perhaps you could add a possibility for someone to
clear a disk - just like you can shift right click patterns. Maybe
something more. A disk format kind of thing? That way at least I can
recover the 8 or so corrupted ones I have, but it could also serve as a
quick way of getting rid of unwanted things.

**Comment by danielhickman** [comment] 2016-11-09 12:29
I just wanted to share my drives after using the disk manipulator next to a torcherino, they are dramatic. I am in RS 1.2 and HermitPack 1.3.0, but this happened before those releases. But my items were also duplicated in the process. (Any ideas on that? I'm guessing the torcherino.)

The disks:
![2016-11-08_00 34 05](https://cloud.githubusercontent.com/assets/5341898/20137978/9f6c66a4-a632-11e6-821d-aad1fbe2c236.png)
In a drive:
![2016-11-08_02 32 14](https://cloud.githubusercontent.com/assets/5341898/20137979/9f6d6450-a632-11e6-9226-7bcaa80f96bd.png)
Why I'm sure everything was duplicated (item, xp, and durability all the same; never would've made two of these):
![2016-11-09_04 26 22](https://cloud.githubusercontent.com/assets/5341898/20138399/fdff4900-a634-11e6-819a-df594b628746.png)

**Comment by Simon-Bitdiddle** [comment] 2016-12-10 22:16
Is there a 'fsck' disk sanity check operation that could be part of either accessing the disk or when its inserted to the drive?
Great, now I'm thinking of a 'failure' mechanic of tiered disks and drives; cheap disks are fine but after a while items go missing and you can make better quality ones that are less prone to dropping items. Combine them into a Redundant Array of Item/Fluid Storage Disks for safety, but if your RAID goes bonk, you're boned.

**Comment by Joshwoo70** [comment] 2016-12-22 06:09
same.. lol... we should make a addon which adds it. back to the issue. we should add a sanity check for if it is less than 0 then we forcibly change it to 0.

**Comment by Zekralyx** [comment] 2017-05-23 00:38
I'm having almost the same problem this issue describes, but for me the Disk Manipulator emptied the a disk at 2380/64000, then I access it through a Grid and shows nothing. 

There is a way to get the Storage Disk back to normal without cheating?

Some pictures:
![2017-05-22_20 27 39](https://cloud.githubusercontent.com/assets/2272746/26333729/feffd30a-3f2d-11e7-9027-f04b7b3cb83b.png)
![2017-05-22_20 27 45](https://cloud.githubusercontent.com/assets/2272746/26333741/14c17a7c-3f2e-11e7-8226-b5e5434f8c2e.png)
![2017-05-22_20 29 48](https://cloud.githubusercontent.com/assets/2272746/26333747/1ef607b0-3f2e-11e7-9bf0-7e8ec985ee01.png)

**Comment by raoulvdberge** [comment] 2017-07-04 21:39
The cause of this issue is really #908

**Closed by raoulvdberge** 2017-07-04 21:39 UTC
Labels: bug
