### ISSUE TITLE
Client Lag occurs when RS is tied to a power setup that is browning out

### ISSUE THREAD

**Issue by mahldcat** [raoulvdberge/refinedstorage#845] opened 2017-01-08 04:54 UTC
#### What happens:
When there is a sever power spike, and the power storage fully drains, the RS controller/grids etc will trigger on and off rapidly causing client lag.  If I move out of range of the RS system, the lag goes away

As this was also on a server, I had the admins watch to see if there was server side performance (there was nothing to note)....

#### What you expected to happen:
In this case some sort of detection to see if the RS system is "flapping?" and then not switch the visual cues?

#### Steps to reproduce:
Setup assumes you also have enderio along with RS.
1.  Setup a powergen + capacitor setup + RS system such that you produce only slightly more than you consume.
2.  Set the RS controller so it is disabled when it gets a redstone signal, and attach a lever to it (turned off)...controller should still be active
3.  setup about 8-10 smelteries/sag mills on the system (with the highest capacitors on it), and load them up so they continually operate.
4.  Attach them to your power grid
5. Navigate back to your RS area....
6.  You should see the RS controller turn on and off VERY rapidly, and the game client will lag
7.  Flip the controller lever to disable the RS controller
8.  Now the client lag should go away...
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.12

Does this issue occur on a server? yes, but it does not cause server lag (that we could tell)

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment] 2017-01-08 10:37
Duplicate of #566

**Closed by way2muchnoise** 2017-01-08 10:37 UTC
