### ISSUE TITLE
pretty bad FPS lag even when you're not in grid

### ISSUE THREAD

**Issue by DoomSquirter** [raoulvdberge/refinedstorage#74] opened 2016-05-24 00:32 UTC
refinedstorage-0.6.11
Forge 1907

So, for quite a few versions, opening up the grid definately gives you the feeling as if you are getting fps lag but no real way to see, and because of this, I haven't tried till now, to make a real system with quite a few disks, etc.  I thought it might make sense to make separate systems, one to contain the main system that has things I need to craft, and another that is the catch-all that I'll pull things out of to put in other system manually.  I did this because it seemed that the more items that go into the system, the laggier the interface gets.

One thing I am noticing tho, is that lag is indicative outside of grid.  I have 3 systems now, all with one 64k disk and one of them has an additional 64k.  Whenever I approach the main system, within about 30-50 blocks, my FPS drops to about 8-12.  Breaking the components brings the FPS back to about 100-120.  Is this a known issue?  

In addition, I'm seeing the same as closed ticket regarding getting various other items other than one I had pulled.  even if you type in STONE and start getting stone out, out comes a  silver ore or something that shouldn't even be seen considering you are filtering this all out.  And yes, I guarantee lag has a hand in this, but this is not server lag.  This is lag caused by the mod itself.  

It's very nice to have something that's 10 times better than chests, but if the lag keeps up, I'll have to go back to using chests again, cause I do love my fps :)  

Thanks in advance

**Comment by DoomSquirter** [comment] 2016-05-24 00:52
wanted to add one more thing.  The lag I speak of definately seems to eminate from the main systems (disk, controller, who knows).  What I did to reduce some lag was to move my systems down to a very low basement and run cables up to my main room.  The fps definately does drop a tad bit but overall, performance is much better.  In addition, while you're in the crafting grid, performance also is much improved.

**Comment by raoulvdberge** [comment] 2016-05-24 14:55
Grid lag should be gone in the latest version. Can you replace your controller with a creative controller and see if you have less lag?

**Comment by DoomSquirter** [comment] 2016-05-24 23:47
Afraid I can't w/o op around to test this.  

Again, moving the grid 30-50 blocks away from controller/drives, there is very little lag while interacting with the grid.  But get near the main system and your fps itself starts to nosedive immediately.  I think the FPS of the main system affects the 'lag' of using the grid quite a bit.

**Comment by raoulvdberge** [comment] 2016-05-25 00:03
Can you open F3 and tell me how many chunk updates you get while in the area of problem?

**Comment by DoomSquirter** [comment] 2016-05-25 13:09
F3 shows 38-39 chunk updates near the main system
12-30 after putting creative controller down

I will be making a new box to test things in away from everything else and add stf back one by one to see where issue resides, maybe tomorrow.

When you say latest version removes grid lag, we're talking the 1.9 0.6.11 version or you mean the 1.9.4 version?  We're anticipating to move to 1.9.4 soon hopefully.

**Comment by raoulvdberge** [comment] 2016-05-25 16:42
What other blocks from mods are near the main system?

**Comment by raoulvdberge** [comment] 2016-05-25 22:30
Ok, looking forward to hear the results.
- 0.6.11 fixes a bit of grid lag
- 0.6.12 fixes a bit more of grid lag
- the 1.9.4 version should have a full fix for the grid lag

**Comment by raoulvdberge** [comment] 2016-05-27 19:22
Btw, 38-39 chunk updates is *not* normal. Is that constant? Are your connected machines turning off / on constantly due to low power in the controller? Is the lag gone with the creative controller?

**Comment by raoulvdberge** [comment] 2016-06-02 08:09
Going to close this as not reproduceable. Please reopen if you have the same issue on latest Refined Storage...

**Closed by raoulvdberge** 2016-06-02 08:09 UTC
