### ISSUE TITLE
CPU hits 100% when autocrafting

### ISSUE THREAD

**Issue by willsrobs1** [raoulvdberge/refinedstorage#878] opened 2017-01-16 22:32 UTC
#### Issue description: 
Some items I can't even auto craft some I can. Shortly after I start seeing lag spikes and 100 percent cpu ussage

#### What happens: 
when I try to craft something using a pattern I can select it and the amount I want. But when I hit start it shows that it has been click by going dark grey but then nothing happens and I have to hit cancel. Shortly after I start having leg spikes I first noticed it when I went to craft epic bacon on sky factory

#### Steps to reproduce:
1. go to crafter
2. start a crafting pattern
3. click start but nothing happens
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2215
- Refined Storage: 1.2.17

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by willsrobs1** [comment] 2017-01-16 22:36
[Sampler.zip](https://github.com/raoulvdberge/refinedstorage/files/709537/Sampler.zip)

**Comment by way2muchnoise** [comment] 2017-01-16 22:42
What are you trying to craft? Cause when you press the button it might take some time to calculate if it is a large task.

**Comment by willsrobs1** [comment] 2017-01-16 22:46
epic bacon from sky factory but it hapens with other things to. It does seem to be a thing happening with larger tasks but it causes lag spikes and maxes out my cpu after I hit start on the crafting.

**Comment by way2muchnoise** [comment] 2017-01-16 23:05
Are crafting the dyes using RS and the mystical crops essence? Cause that recursive crafting recipe might be causing issues.

**Comment by willsrobs1** [comment] 2017-01-16 23:09
Does RS and mystical crops have issues together because I did have some issues with crafting other things from mystical crops before

**Comment by willsrobs1** [comment] 2017-01-16 23:13
Took out the dye recipes, they weren't using mystical crops but I can now auto craft bacon.

**Comment by way2muchnoise** [comment] 2017-01-17 09:05
It is just the fact that some recipes of mystical crops (and maybe others) take as input a lower amount but the same item as the output. In general recursive crafting, although mystical crops isn't always an issue. I made quite some changes to try and support recursive crafting. eg. if you want to upgrade your essences just force start it, that way you won't need multiple stones. But I'll try and fix this issue in the near future (won't be for next SF update, but in a few weeks maybe).

**Comment by willsrobs1** [comment] 2017-01-17 14:54
Sounds great, Ill just avoid auto crafting dyes then thanks for all the help!

**Comment by HolyDLX** [comment] 2017-02-26 10:31
+1 [Raising Awareness]

Noticed the same issue on our server when one guy used the duping mechanic of botania (1 dust -> 2 dust).

We had to download the map and delete the controller with MCEdit. Everytime we logged in it started crafting and crashed/got stopped by watchdog.

I'd suggest to rename the issue.

**Comment by raoulvdberge** [comment] 2017-03-30 17:55
Thanks for the report. I'll close this for now, since this is a duplicate of #838.

But, since this issue and #838  are linked now thanks to this comment we'll obviously still look at your profiling report.

**Closed by raoulvdberge** 2017-03-30 17:55 UTC
Labels: autocrafting, performance
