### ISSUE TITLE
Creative mode with drives in inventory glitches them. 

### ISSUE THREAD

**Issue by Properpeanut** [raoulvdberge/refinedstorage#720] opened 2016-12-07 21:06 UTC
#### What happens:

I made a 4k drive and inserted it into the disk drive and it worked.
Went into creative with the same drive in my inventory and back to survival and the same drive would not be recognized by the disk drive.
This issue has happened multiple times on my own server.

#### What you expected to happen:

That the drive would pop into the disk drive and work.

#### Steps to reproduce:
1. make a drive or take one from creative
2. put it into the disk drive.
3. Tada!
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2124
- Refined Storage:1.2.4

Does this issue occur on a server? yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment] 2016-12-07 21:08
Why would you still be 1.2.4, we are at 1.2.9 already. You should really update. ([CurseForge](https://minecraft.curseforge.com/projects/refined-storage/files))

**Comment by raoulvdberge** [comment] 2016-12-08 15:04
Duplicate of #712 Also update

**Closed by raoulvdberge** 2016-12-08 15:04 UTC

**Comment by halvors** [comment] 2017-11-10 23:57
@raoulvdberge Still experiencing this on 1.12 with newest release.
