### ISSUE TITLE
Destructor in 1.11.2 can import air

### ISSUE THREAD

**Issue by kragnoth** [raoulvdberge/refinedstorage#1397] opened 2017-08-03 00:52 UTC
#### Steps to reproduce:
1. Setup RS system
2. Setup 4x4 water infinite water pool
3. Set destructor next to water to put water into system

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 2425
- Refined Storage: 1.4.20

Only tested on single player.

This behavior can be avoided for now by setting destructor to fluid and setting water as the fluid.  Only way I found of venting the water was removing my entire liquid storage system and dumping them in a garbage can.   Alternatively throwing them into the void might work.

**Comment by raoulvdberge** [comment] 2017-08-03 04:43
Good theory but no, this is not caused by destructors.

Duplicate of #1233

**Closed by raoulvdberge** 2017-08-03 04:43 UTC

**Comment by kragnoth** [comment] 2017-08-03 16:20
Ok, well that is the only way I get water into my system, so I kind of assumed. :P
