### ISSUE TITLE
Fuzzy Patterns

### ISSUE THREAD

**Issue by Californ1a** [raoulvdberge/refinedstorage#426] opened 2016-10-05 20:25 UTC
It'd be great to be able to set specific slots in a crafting pattern as fuzzy so it would use any type of wood/log/etc. instead of requiring 6 patterns for chests, another 6 for sticks, etc. (or even more if you have another mod with extra trees like Forestry). Even better would be if you could set a list of items that work in a slot for a pattern (i.e. if you have both Basic Electric Circuits from IC2 and Basic Circuits from Mekanism, they're interchangeable in most recipes). Maybe setting options on a pattern like this would only be available on an "upgraded/advanced" version of the pattern item, and the regular pattern item stays as-is with just the basic "singular" recipe.

Edit: Also, in relation to #412 the "advanced" pattern should use the item that has the most base materials in the system. If you have 500 osmium ore but only 200 copper ore, then the system would opt to use the Mekanism circuit for this autocraft, whereas if you had 500 copper and 200 osmium, then the system should opt for the IC2 circuit. Or, possibly there could be a manual option to select which one to use. With a manual option, you could override the "use most base materials" if you want to use a faster process where you have less base materials.

**Comment by LousyLynx** [comment] 2016-10-06 01:00
Is this not fixed by the "Oredict" option when creating your pattern in the Pattern Processor? And as for the second thing you mentioned, I'm not quite sure what you're asking, are you saying what if you have not enough items to make something? If so, then you can just make a pattern for that item. Then it would autocraft that item, then the next item up.

**Comment by Californ1a** [comment] 2016-10-06 01:50
>Is this not fixed by the "Oredict" option when creating your pattern in the Pattern Processor?

I don't see any options in the Processing Pattern Encoder or the Pattern Grid for any kind of filters like oredict or item ids. In the PPE there is [just the two grids with the slot for the pattern item and "create pattern" button](http://i.imgur.com/3uTBgRX.png), and in the PG there is [just the one grid with crafting result along with the slot for the pattern and "create pattern" button](http://i.imgur.com/1SCyAD6.png). No such options are presented after clicking the button either.

Also, oredict might solve some cases like the wood/logs/sticks thing so you're able to have one pattern for wood log->4 planks and it know to use that pattern for all wood logs, but there are also some other cases when a slot in a pattern/recipe is interchangeable with a completely different item that doesn't have the same oredict name, so what I'd like to see is the ability to specify more than one item for each slot within one pattern (without having to make a ton of Crafters to put a bunch of different patterns in just because there's more than one recipe) as long as the output is the same.

As for the second thing, it's not really about running out of a resource, but more of an optimization that the storage system/automatic crafting should take into account. If there are two recipes for the same requested output, then the crafting should use the pattern that includes the most plentiful resources rather than the most scarce. A simple example of this would be if you have a ton of dark oak logs, but only 5 or 6 birch logs total, and you have patterns set for logs->planks and planks->sticks, then when you request sticks it should use the dark oak rather than the birch. This way, the storage system polices itself to keep at least a few of every item in the system (I'd also love to see a way to specify "always keep X amount of this item available in the system," but that's for another topic).

**Comment by LousyLynx** [comment] 2016-10-07 23:29
> I don't see any options in the Processing Pattern Encoder or the Pattern Grid for any kind of filters like oredict or item ids

I'm just going to say, make sure you have the latest version of Refined Storage, because I know for a fact that it has the Ore Dict button. 😄 As for the second thing, yeah... @raoulvdberge get on that! 😛

**Comment by raoulvdberge** [comment] 2016-10-07 23:59
I got rid of the oredict button before releasing that version...

**Comment by raoulvdberge** [comment] 2016-10-08 00:00
But it might be possible with the new autocrafting system, thats why im leaving this open.

**Comment by choekstr** [comment] 2016-10-08 00:08
Really hoping you can figure out a way for OreDict and NBT options.  I appreciate the challenge you have but fingers crossed you can come up with something clever.

**Comment by Californ1a** [comment] 2016-10-08 00:10
Ah that'd be why then. I was definitely on 1.1.2 when posting, and updated to 1.1.3 earlier.

**Comment by raoulvdberge** [comment] 2016-10-09 13:51
This issue is a duplicate of #378

**Closed by raoulvdberge** 2016-10-09 13:51 UTC
Labels: feature request
