### ISSUE TITLE
Interface block hangs

### ISSUE THREAD

**Issue by Stabington** [raoulvdberge/refinedstorage#621] opened 2016-11-12 18:35 UTC
#### Issue description:
At seemingly random intervals, the Interface block just stops working.

#### What happens:
The interface neither import or export items.
The GUI is also desynced. Nothing happens when I click the toggle options until I re-open the GUI.

#### Steps to reproduce:
I honestly have no clue. I have had several interface blocks just stop working out of the blue. Breaking and replacing the blocks fixes it.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2122
- Refined Storage: 1.2.3

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Stabington** [comment] 2016-11-12 23:17
It seems Detectors also stop working.

**Comment by raoulvdberge** [comment] 2016-11-13 00:16
duplicate of #370

break+replace the controller for now

**Closed by raoulvdberge** 2016-11-13 00:16 UTC
