### ISSUE TITLE
Problem autocrafting when crafting pattern involves Processing as well

### ISSUE THREAD

**Issue by bignate1011** [raoulvdberge/refinedstorage#339] opened 2016-09-14 02:01 UTC
#### Issue description:
When trying to autocraft a pattern that has multiple pieces that need to be processed (such as an octadic capacitor) the alloy smeltery only processes one item instead of all needed, never allowing the autocrafting to finish. This also happens with any pattern that includes multiples of the same item that needs to be processed such as item conduit speed upgrades with electrical steel. I have not tested this with another mods machines, only the alloy smelter. I also tried importing to a chest with an importer and an importer attached directly to the alloy smelter. My processing does go across a network transmitter about 66 blocks away from my controller as well if that is relevant at all but all the crafters are on the same side of the network receiver.

#### What happens:
When trying to autocraft an octadic capacitor, the crafter hangs on the double layer capacitor because it only allows one energetic alloy to be processed (when there are none in my system)  instead of the two necessary for the double layer capacitor. I have no issue with double layer capacitors individually autocrafting, only when they are part of a larger pattern that needs them. This also happened with the item conduit speed upgrade from enderio. 

#### What you expected to happen:
Two energetic alloys to be processed, allowing the pattern to continue to craft.

#### Steps to reproduce:
1. Create crafter with alloy smelter attached to it.
2. Create crafter to craft all necessary parts of an octadic capacitor
3. Create all patterns to autocraft an octadic capacitor from raw materials
4. Attempt to autocraft.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.1.2086
- Refined Storage:1.0.1

Does this issue occur on a server? Not sure this was a single player world

**Comment by phantomholo** [comment] 2016-09-14 15:03
same issue here

**Comment by raoulvdberge** [comment] 2016-09-14 15:03
I'll look at it in a few hrs, temperature here make any serious work impossible unfortunately

**Comment by raoulvdberge** [comment] 2016-09-14 15:50
Please try this build and let me know if it works:

[refinedstorage-1.0.2.zip](https://github.com/raoulvdberge/refinedstorage/files/472589/refinedstorage-1.0.2.zip)

(rename .zip to .jar)

**Comment by bignate1011** [comment] 2016-09-14 15:57
Will try it when I get home but it will be later tonight. Thanks

**Comment by raoulvdberge** [comment] 2016-09-14 16:23
Actually, I can't reproduce this issue (a classic)

I set up autocrafting for the speed upgrades from Ender IO and it just crafted the 4 upgrades properly...

**Comment by bignate1011** [comment] 2016-09-14 16:49
Did that include having to process the electrical steel in an alloy smelter as a part of that process? Because that is where mine is hanging up.

**Comment by raoulvdberge** [comment] 2016-09-14 17:00
Okay, the build I just gave you didn't really fix it. But I fixed in the dev branch. Expect a release in a few hrs :)

Thanks for reporting

**Closed by raoulvdberge** 2016-09-14 17:00 UTC
