### ISSUE TITLE
[1.10.2] Loads of lag

### ISSUE THREAD

**Issue by Eufranio** [raoulvdberge/refinedstorage#1187] opened 2017-04-25 00:53 UTC
The server randomly starts lagging and the TPS goes to 2 sometimes. The Timings reports that the Refined Storage controllers are causing the lag spikes. The TPS is 20 most of the time, and randomly a lag spike happens.

Timings: https://timings.aikar.co/?id=61d1763540334d2986d9efd95bd1647e
And yes I tested in a pure forge server with no Sponge installed, the server has a lot of lag spikes too.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: (v12.18.3.2239)
- Refined Storage: 1.2.25

This issue ocurr in a server.

**Comment by raoulvdberge** [comment] 2017-04-25 06:14
https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by raoulvdberge** [comment] 2017-04-27 16:35
Missing profile report.

**Comment by Eufranio** [comment] 2017-04-29 00:53
The lag is coming from here:
```
	at java.util.AbstractCollection.toArray(AbstractCollection.java:199)
	at net.minecraftforge.oredict.OreDictionary.getOreIDs(OreDictionary.java:457)
	at com.raoulvdberge.refinedstorage.apiimpl.util.ItemStackListOredicted.initOreDict(ItemStackListOredicted.java:29)
	at com.raoulvdberge.refinedstorage.apiimpl.util.ItemStackListOredicted.<init>(ItemStackListOredicted.java:24)
	at com.raoulvdberge.refinedstorage.apiimpl.util.ItemStackList.getOredicted(ItemStackList.java:153)
	at com.raoulvdberge.refinedstorage.tile.TileController.getPattern(TileController.java:425)
	at com.raoulvdberge.refinedstorage.api.network.INetworkMaster.getPattern(INetworkMaster.java:154)
	at com.raoulvdberge.refinedstorage.api.network.INetworkMaster.hasPattern(INetworkMaster.java:164)
	at com.raoulvdberge.refinedstorage.RSUtils.writeItemStack(RSUtils.java:66)
	at com.raoulvdberge.refinedstorage.network.MessageGridItemUpdate.toBytes(MessageGridItemUpdate.java:41)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26)
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:73)
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:254)
	at com.raoulvdberge.refinedstorage.tile.TileController.sendItemStorageToClient(TileController.java:509)
	at com.raoulvdberge.refinedstorage.tile.TileController$$Lambda$1955/922617581.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.raoulvdberge.refinedstorage.tile.TileController.sendItemStorageToClient(TileController.java:504)
	at com.raoulvdberge.refinedstorage.apiimpl.storage.item.ItemStorageCache.invalidate(ItemStorageCache.java:57)
	at com.raoulvdberge.refinedstorage.tile.externalstorage.TileExternalStorage.onConnectionChange(TileExternalStorage.java:122)
	at com.raoulvdberge.refinedstorage.tile.TileNode.onConnected(TileNode.java:91)
	at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeGraph.rebuild(NetworkNodeGraph.java:140)
	at com.raoulvdberge.refinedstorage.api.network.INetworkNodeGraph.rebuild(INetworkNodeGraph.java:24)
	at com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:329)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:226)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2803)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjp000(WorldServer.java:2790)
	at net.minecraft.world.World.func_72939_s(World.java:6003)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2157)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Eufranio** [comment] 2017-04-29 00:55
@raoulvdberge

**Comment by raoulvdberge** [comment] 2017-04-29 07:34
Missing profile report.

**Comment by Eufranio** [comment] 2017-04-29 12:22
Isn't that sufficient? It's from Sampler too (stall-report), it's a text file so I could get it easier. If you still want, I can send a nps anyway.

**Comment by way2muchnoise** [comment] 2017-04-29 12:43
The report we want is the `.nps` file, we are next to nothing with text logs

**Comment by Eufranio** [comment] 2017-04-29 15:35
NPS file: http://dl.magitechserver.com/DL/report.nps

**Comment by raoulvdberge** [comment] 2017-05-15 19:23
Duplicate of #566

**Closed by raoulvdberge** 2017-05-15 19:23 UTC
Labels: investigate, performance
