### ISSUE TITLE
Constructor and cakes

### ISSUE THREAD

**Issue by popemichael** [raoulvdberge/refinedstorage#121] opened 2016-06-18 19:52 UTC
The constructor is unable to place down cake.

I originally tested the issue on version 0.7.13 (the one included in FTB Unstable). I then manually updated to the version 0.7.15 - That failed as well

To recreate: 
1. Attach a constructor to a controller, disk drive, grid
2. Add a 64k disk filled with cake into the diskdrive; confirm that it's full of cake VIA the grid
3. Connect a Constructor VIA cable to the diskdrive.
4. Set the filter within the Constructor as "cake" by picking up cake and then selecting the filter.
5. The caked fails to be placed

To confirm to see if it was just cake, I followed the same steps for dirt. The Constructor placed down dirt without an issue.

**Comment by raoulvdberge** [comment] 2016-06-18 20:36
Damn, I thought I fixed that bug like ages ago. Thanks for the good report.

**Comment by raoulvdberge** [comment] 2016-06-19 00:29
They work here?
![2016-06-19_02 28 36](https://cloud.githubusercontent.com/assets/10358424/16174519/9c3c6836-35c5-11e6-82c4-bee2fef3b3d4.png)

**Comment by raoulvdberge** [comment] 2016-06-19 00:30
Remember, cake can only be placed on a solid material.

**Comment by popemichael** [comment] 2016-06-19 00:51
It's on a solid grass block. I've taken screen shots of the setup. Could it have something to do with Pam's Harvest craft cake?

![cake_1](https://cloud.githubusercontent.com/assets/17892373/16174594/62422082-3596-11e6-9219-2461322d3cc3.png)
![cake_2](https://cloud.githubusercontent.com/assets/17892373/16174591/623eed36-3596-11e6-9336-bc482efc3349.png)
![cake_3](https://cloud.githubusercontent.com/assets/17892373/16174592/623ffcc6-3596-11e6-95de-e3cbbc9c051e.png)
![cake_4](https://cloud.githubusercontent.com/assets/17892373/16174593/62403be6-3596-11e6-9153-bb22ff7659cb.png)
![cake_5](https://cloud.githubusercontent.com/assets/17892373/16174590/623ed68e-3596-11e6-8783-bc8ee1efaebd.png)

**Comment by raoulvdberge** [comment] 2016-06-19 00:53
Yup, Pam's doesn't implement `canPlaceBlockAt` correctly.

**Comment by raoulvdberge** [comment] 2016-06-19 00:56
Hmm, it works on stone but not grass O_O

**Comment by raoulvdberge** [comment] 2016-06-19 00:59
Unfortunately, this is a vanilla issue. I call `canPlaceBlockAt` to check if it's placeable. `BlockCake` only accepts solid undergrounds, and grass is not solid :(

I could special case it, but then I'd have to special case everything.

**Comment by Zettt** [comment] 2016-11-05 10:18
Hello Raoul. I'm sorry to report that this issue still exists. The constructor can't place cake, no matter what material I use. It can't even place cake on top of itself (meaning the constructor itself would have to be a solid block, which it is not). ;-) 

Here are two screenshots of my setup. I'm on 1.2 of RS.

![2016-11-05_11 15 09](https://cloud.githubusercontent.com/assets/42497/20029329/722a0246-a349-11e6-9290-8d02f37912aa.png)
![2016-11-05_11 15 15](https://cloud.githubusercontent.com/assets/42497/20029330/76a440fc-a349-11e6-9fff-f2ee77745551.png)

**Comment by raoulvdberge** [comment] 2016-11-05 18:38
@Zettt Works for me:

![x](https://raoulvdberge.com/572rB9)

**Comment by Zettt** [comment] 2016-11-06 09:37
How is this answer supposed to help us?

**Comment by raoulvdberge** [comment] 2016-11-06 09:51
Well, I can't reproduce this, so, there's not much I can do...

**Comment by Zettt** [comment] 2016-11-06 15:01
So you are closing the issue although you have two people against one having the issue? I'd appreciate if you try to find the issue. Or help us help you find the issue, instead of closing it. What could possibly the issue here? I can't think of anything. Obviously the original poster @popemichael also doesn't.

**Comment by raoulvdberge** [comment] 2016-11-06 15:06
You seem to be the only one having the issue, as you're the only poster. I've told @popemichael already it's because it can't get placed on grass.

**Comment by Zettt** [comment] 2016-11-06 15:12
Yes, I can see that, and I had the same issue now for a couple of weeks. I've been watching this thread for things to progress. It's been closed. Now I've shown you that the grass is not the issue.

**Comment by raoulvdberge** [comment] 2016-11-06 15:27
And I've shown that stone isn't an issue either. I just can't reproduce it, again, not much I can do.

**Comment by raoulvdberge** [comment] 2016-11-06 15:42
I'll take another look.

**Comment by xenoflot** [comment] 2016-11-19 07:32
A player on my server reported this today. I just tested myself, placing onto cobblestone. The cake (vanilla) is dropped as an item.

Interestingly, Harvestcraft cakes are placed as a block. Go figure.

RS 1.2.4
Harvestcraft 1.9.4-1.10.2h

**Comment by way2muchnoise** [comment] 2016-11-19 09:28
Could this a issue being related to some security? Chuck claims and such so that other players can't place shit?

**Comment by xenoflot** [comment] 2016-11-19 11:25
Not in my case as we don't have any chunk claim utils that I'm aware of. We're running FTB Unleashed with some extra forge mods.

**Comment by way2muchnoise** [comment] 2016-11-22 18:01
I'm going to guess you mean FTB Unstable and not Unleased and that has chuck claiming as it is part of FTBU (it also keeps them chuck loaded)

**Comment by xenoflot** [comment] 2016-11-22 19:46
Ah yes, FTB Unstable and now I'm aware of a chunk claimer in our pack. Thanks!
We're not actively using that though.

**Comment by Theodosis** [comment] 2016-12-27 23:06
So, I was testing some stuff on a vanilla+RS1.2.12 and I stumbled upon this bug report so I figured I'd give it a try. It looks like placing cakes works fine for me, even on grass. It would be helpful if you guys could reproduce this in a new empty world with just the RS mod. If the bug does not occur in that build you can incrementally add the rest of the mods in your modpack to figure out which one is conflicting, if that's the case. That would probably be a lot more useful to the developers of the mod and it will get your issue resolved a lot faster.
![image](https://cloud.githubusercontent.com/assets/1080917/21510205/1527cec2-cc91-11e6-8143-e29f411e2353.png)

**Comment by raoulvdberge** [comment] 2016-12-27 23:18
@Theodosis Thanks for trying it out too.

I tried this out yesterday, couldn't reproduce this bug. The only reason this issue is still open is because I had it throw items instead of placing the block once a few weeks ago...

**Closed** 2017-01-25 01:30 UTC
Labels: bug, can't reproduce
