### ISSUE TITLE
Destructor not breaking blocks (non-FTB)

### ISSUE THREAD

**Issue by Nuinethir** [raoulvdberge/refinedstorage#868] opened 2017-01-15 04:40 UTC
#### Issue description:

The Destructor is not breaking blocks. This occurs in a Forge-modded Minecraft (not FTB's launcher) single player world.

#### What happens:

Destructor is not breaking blocks, despite whitelist, blacklist, or none.

#### Steps to reproduce:

1. Place Destructor connected to RS system with available storage.
2. Place cobblestone in front of Destructor.
3. Destructor sits idle.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 1.10.2-forge1.10.2-12.18.3.2202
- Refined Storage: refinedstorage-1.2.16

#### Does this issue occur on a server?

No.

**Comment by raoulvdberge** [comment] 2017-01-15 05:16
Can I have a *full* modlist? Is FTB utilities installed?

**Comment by Nuinethir** [comment] 2017-01-15 05:46
No FTB utilities installed. However, I solved the problem...

I had the Disk Drive and Crafting Grid attached directly to the Controller. The Cable went to the Destructor from the Controller directly.

However, if I attach the Disk Drive and Crafting Grid to the cable going to the Destructor, it works just fine. Does this mean that each face of the controller is a separate channel?

**Comment by Nuinethir** [comment] 2017-01-15 05:54
I removed and replaced all system components exactly where they were before and now it works. I also had this issue with cabling going to a Quantum Storage. Seems sporadic so not sure exactly why it behaves like this.

I do not have FTB installed for this mod, I am running it in the vanilla folder with Forge profile (custom modpack)...

http://pastebin.com/wZrYQXAx

**Comment by raoulvdberge** [comment] 2017-01-15 19:29
duplicate of #370

**Closed by raoulvdberge** 2017-01-15 19:29 UTC
