### ISSUE TITLE
[1.10.2] Large autocrafting orders cause MAJOR lag

### ISSUE THREAD

**Issue by hugeblank** [raoulvdberge/refinedstorage#838] opened 2017-01-07 10:12 UTC
#### Issue description:
So, I run a 1.10.2 server with a small amount of players online. We all started for the most part together, and as such, our bases are growing at the same speed. We got to the point where autocrafting was feasible, and immediately ran into issues. 
#### What happens:
We wanted to compress a large LARGE amount of coal that we had collected, and noticed that the server lagged when crafting...HARD. Everyone slows down, and eventually stops moving, chat is slowed, and other common effects of the dreaded server lag.
#### What you expected to happen:
Not that ^ XD
#### Steps to reproduce:
0. Run a server
1. Create a RSS with an autocrafting setup
2. Insert a large amount of items that can be crafted
3. Craft them, and enjoy as your server lags to hell

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2185
- Refined Storage: 1.2.14

Does this issue occur on a server? 
Yep.

**Comment by way2muchnoise** [comment] 2017-01-07 11:46
Could you profile the issue? More info about that: https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by raoulvdberge** [comment] 2017-01-09 04:52
@hugeblank Please run a profiling session while the lag is happening, or I'll have to close this issue because we can't do much otherwise.

**Comment by hugeblank** [comment] 2017-01-09 08:17
@raoulvdberge Yeah I can do that. Give me a few days, other than weekends, I'm not typically free to work on the server.

**Comment by linktlh** [comment] 2017-01-16 07:27
Please Please Please fix this we are having the same problem. here's what you're asking for
[RefinedStorage.nps.zip](https://github.com/raoulvdberge/refinedstorage/files/707492/RefinedStorage.nps.zip)

**Comment by linktlh** [comment] 2017-01-16 07:28
at the very end of the sample we stopped it before I had time to turn off the sampler. tell me if you need or want a longer sample.

**Comment by hugeblank** [comment] 2017-01-18 06:58
@linktlh well thank you for doing my work for me! :P

**Comment by linktlh** [comment] 2017-01-18 13:54
Naw I was just trying to help speed up the process cause I knew you were very busy. :)

**Comment by linktlh** [comment] 2017-01-18 13:57
Also without you I wouldn't have found what was causing the major lag on my server a user linked this forum after a bit I read it then went around looking for massive amount of auto crafting and sure enough someone was making 5,000 supremium essence. As soon as we canseled it the lag was 100% gone

**Comment by way2muchnoise** [comment] 2017-01-18 15:21
yeah the essence are quite the task for RS, it is one of those things that are better done before entering RS. But I'll keep trying to improve :p

**Comment by linktlh** [comment] 2017-01-18 17:16
I feel like I'm gonna have to ban auto crafters fro
 Here due to this >.> I REALLY don't want to do that...

**Comment by hugeblank** [comment] 2017-01-21 00:43
Yeah I can understand the pain of the decision, seeing as autocrafting is a key component to the mod, and also a desirable feature. 

Maybe as a feature request, servers should be able to set a max amount of craftable items. (as a temporary fix to this issue)

**Comment by linktlh** [comment] 2017-01-21 02:49
OO I like that idea like you can only craft Custom auto craftingarg1 amount of arg2

**Comment by hugeblank** [comment] 2017-01-23 08:11
That's not EXACTLY what I was saying, but it would be another cool idea. 

My idea was that if someone wanted, let's say, 5 million course dirt to be crafted, it would check the server configs for a limit to the amount of crafting operations that it can do. If it exceeds that amount, then it notifies the player, and begins the operation with the max amount.

**Comment by way2muchnoise** [comment] 2017-01-24 17:24
#876 should also help with the lag

**Comment by KaiKikuchi** [comment] 2017-01-24 22:52
Still lagging as hell.

Steps to reproduce:
- Make a very basic RS system with a Controller, a Grid, a Pattern Grid, a Disk Drive, a disk of any size, a Crafter and a Crafting Monitor
- Create a pattern for the Crafter that crafts Coal from Coal Blocks
- Start an auto crafting process from your Grid to craft a lot of Coal

Version:
- RS compiled from branch mc.1.10, commit https://github.com/raoulvdberge/refinedstorage/commit/3be7adb5915f1c4941f837ae92d554608c3a074c
- Forge 1.10.2-12.18.3.2221

VisualVM sampling while crafting coal with the Crafter reported this (33% used by that Controller):
![javaw_2017-01-24_23-16-07](https://cloud.githubusercontent.com/assets/8842403/22270417/b8eb25cc-e28f-11e6-86fc-b245b930dd1b.png)

And at some point after I stopped the sampling above, it completely stalled and VisualVM sampling reported this (100% writing NBT data forever?):
![javaw_2017-01-24_23-30-53](https://cloud.githubusercontent.com/assets/8842403/22270448/dde0d372-e28f-11e6-8bea-f43709351778.png)

I had to kill the process because after a minute it was still stalled.

**Comment by way2muchnoise** [comment] 2017-01-24 22:57
@KaiKikuchi How much did you order? And by start an autocrafting process you mean manually or with some redstone activated crafter?

**Comment by KaiKikuchi** [comment] 2017-01-24 23:00
I started the autocrafting process manually by specifying to craft 10000 coal after adding about 2000 coal blocks.

**Comment by way2muchnoise** [comment] 2017-01-24 23:07
I have no clue why you would be lagging, just did that exact task and my tps didn't dip at all. Running at 3.040 ms and my storage is a colossal chest. Do you have some hardware bottleneck?

**Comment by raoulvdberge** [comment] 2017-01-24 23:13
Did you try with oredict too @way2muchnoise ?

**Comment by way2muchnoise** [comment] 2017-01-24 23:19
Does change much, the oredict list does a exact search first. So it comes down to the same. See https://github.com/raoulvdberge/refinedstorage/blob/mc1.10/src/main/java/com/raoulvdberge/refinedstorage/apiimpl/util/ItemStackListOredicted.java#L81

**Comment by way2muchnoise** [comment] 2017-01-24 23:28
@KaiKikuchi in the screenshot of you posted the main thread is sleeping 50% of the time. And you NBT write is 10ms long. I really have no idea why your CPU would be at 100%.

![](http://puu.sh/tyGRK/042b003b6d.png)

**Comment by KaiKikuchi** [comment] 2017-01-25 00:09
It looks like you're unfamiliar with VisualVM. You don't have to see the ms, because that's based on the entire profile time (27391 ms on the first screenshot, 9960 ms on the second screenshot) so it's not tick based. By doing some math, you can get an average per tick. The average per tick for my test Controller/Crafter, based on data you see on the first screenshot, is 16.85 ms. This is just an average, in fact it comes with lag spikes every X ticks. Probably this happens because the crafter isn't crafting 9 coal every tick, but every 5-10 ticks.

The average TPS per second is not below 20 with just 1 controller (in fact, I haven't said my CPU is at 100%), but you can add 4 or more controllers doing the same thing and, based on my tests, the TPS will drop below 20.

About the second screenshot (stall while writing NBT data), it's probably another bug.

PS: I'm a developer too, and I'm using a computer with quite good performances.
Also I don't have time to waste by reporting fake profiles. Just saying.

**Comment by hugeblank** [comment] 2017-01-25 02:47
TPS per second is redundant as TPS is an acronym for **T**icks **P**er **S**econd
Might want to fix that :P

**Comment by Ryahn** [comment] 2017-01-25 04:50
@way2muchnoise I am not sure if this helps
https://forum.resonantri.se/upload/3KOrderServer.nps - 3K Item Order
https://forum.resonantri.se/upload/ImportBusServer.nps - 4 Import Bus with Speed and Stack
https://forum.resonantri.se/upload/OnServer.nps - 6k Item Order
https://forum.resonantri.se/upload/ClientNoOreDict.nps - 3K Order w/o oredict
https://forum.resonantri.se/upload/ClientOreDict.nps - 3K Order w/  oredict

**Comment by misterfixit** [comment] 2017-01-25 06:49
https://www.amazon.com/clouddrive/share/QRWQTcr1GHER8z65lm80nouAoCZk81tYfKq6NeyWlsr?ref_=cd_ph_share_link_copy

This is while testing three RS systems crafting 1000 items
1. was crafting 1000 pistons
2. was crafting 1000 solar panels from existing materials- aka only crafting patterns
3. was crafting 1000 solar panels using raw materials and a combo of of processing and crafting patterns.
The systems were in 3 different parts of the world

**Comment by way2muchnoise** [comment] 2017-01-25 10:00
@KaiKikuchi it is not that I'm unfamiliar with it is just that you are posting screenshots and no other information. I can't reproduce your bug in my dev, so there isn't much I can do about it. If you could just post the nps then I could see it in perspective to other things, instead of blindly guessing at a screenshot.

**Comment by way2muchnoise** [comment] 2017-01-25 10:20
@Ryahn In all of those the biggest offender is `Chunk.checkLight` which is likely cause by something redrawing the chunk every tick. Are you using any other mods that interact during the autocrafting (I saw some routerreborn stuff in the log)? If yes, could you try without them?

**Comment by way2muchnoise** [comment] 2017-01-25 10:24
@misterfixit the issue in your case seems to be a slow interaction with the SagMill from eio, when RS tries to insert items it takes a very long time checking if the input is valid. I advice using some buffer chest for but I'll contact the eio devs about this.

![](http://puu.sh/tzlh6/e4b6b6214b.png)

**Comment by HenryLoenwind** [comment] 2017-01-26 01:10
Just found out that Forge's SidedInvWrapper is bypassing our "reject fast" code, so we run the full validity check for nothing (but CPU load). The slot is full, there is no need to do any more testing on the input item...

https://github.com/MinecraftForge/MinecraftForge/issues/3658

**Comment by hugeblank** [comment] 2017-01-27 04:45
@HenryLoenwind Is that the sound of a patch coming soon? :D

**Comment by HenryLoenwind** [comment] 2017-01-27 08:20
A patch for Ender IO, yes. We don't need to use the Forge wrapper class, we can supply our own handler with all the optimizations we want. It's in testing right now.

tbh, it is nice that Forge provides wrappers, but any serious item-heavy mod should roll its own handlers.

**Comment by jk1895** [comment] 2017-01-27 23:19
I have a TPS of 1.112 with 898ms per tick when I craft 20 draconic solar panels. But I can craft 100000 levers, thats the same. :-(

**Comment by AEnterprise** [comment] 2017-02-06 13:24
been having the same issue on a server and after doing some testing i found that speed upgrades make things alot worse, i had 2 crafters with 4 speed upgrades each (none in the others) and when i took those out autocrafting big orders was having a much smaller tps impact

this even heapens if non of the recipes used in the autocrafting are in the crafter with speed upgrades or not

**Comment by Rubbertjuh** [comment] 2017-02-18 09:50
Having the same issue, any update on this?

**Comment by HenryLoenwind** [comment] 2017-02-18 20:23
As far as Ender IO in involved, the latest version should work better. But I'd recommend to wait for build 170, I missed some special cases of machines allowing input slots to be output.

**Comment by JaSpr** [comment] 2017-02-20 11:17
Same issue. When set to auto-compress items, even if there are no base items to compress, it causes massive lag on the server.

**Comment by raoulvdberge** [comment] 2017-02-20 14:32
We are working on it.

**Comment by Rubbertjuh** [comment] 2017-02-22 12:51
https://gyazo.com/1caaaf0b9fb9ec73a0d26e4aa9d7c85f
Here is another VisualVM subtree that might help fixing some issues. Running latest Refined Storage on SF3 modpack.

**Comment by HenryLoenwind** [comment] 2017-02-22 15:27
yeah, getOreIDs() is slow. I recently replaced that call in Ender IO with a cached list (https://github.com/SleepyTrousers/EnderIO/commit/b33d3fe3c90beaf3bbe0754e805800c40b5e52df ), feel free to copy this for RS (CC0).

**Comment by Rubbertjuh** [comment] 2017-02-25 16:39
Any progres on this @raoulvdberge ?

**Comment by raoulvdberge** [comment] 2017-02-25 18:01
I'm not working on this, @way2muchnoise is. And he is currently recovering from an operation.

**Comment by JaSpr** [comment] 2017-02-25 18:25
Thanks for the update @raoulvdberge

**Comment by hugeblank** [comment] 2017-02-25 21:55
oh darn, I hope you have a quick and easy recovery @way2muchnoise

**Comment by Rubbertjuh** [comment] 2017-03-05 09:41
Take care @way2muchnoise 
Hope you get better soon. 

In the meanwhile, is there anything you could possibly do? @raoulvdberge this issue is really big and causes a lot of servers to straight out ban the mod.

**Comment by raoulvdberge** [comment] 2017-03-05 11:14
I said I didn't work on the autocrafting code, please be a little respectful.

**Comment by raoulvdberge** [comment] 2017-03-05 11:15
Simple solution: stop starting large orders.

**Comment by JoshHawley** [comment] 2017-05-24 14:13
Just want to add a "me too" to this thread. I am willing to run profiling/testing/etc if you need/want it.

**Comment by raoulvdberge** [comment] 2017-12-22 13:53
Is this still an issue in 1.12.2? If yes, can anyone send some profiling reports my way?

(I know lots of people have posted reports here already - but those were for 1.10.2. I'm interested in NPS files on 1.12 - Thanks)

**Comment by aplanetsabc** [comment] 2017-12-26 18:38
How DO I post a NPS file? I'm currently having this issue with the DW20 pack on 1.12

**Comment by raoulvdberge** [comment] 2017-12-26 18:43
https://refinedstorage.raoulvdberge.com/wiki/profiling

You can include the NPS file as a zip through Github uploading.

**Comment by aplanetsabc** [comment] 2017-12-26 18:46
Ok. I'll do it later this afternoon and upload. Also, The system can't craft Flux capactitors from thermal expansion. It says the lower tiers are missing, even though the system knows how to craft them

**Comment by raoulvdberge** [comment] 2017-12-26 21:53
That is a separate issue! Please make a new issue for that.

**Comment by hugeblank** [comment] 2017-12-28 08:37
I know you want input contrary to the response I'm providing, but I figure a response is better than none at all: I (so far) haven't had any problems with the 1.12.2 version of RS. However this is the kind of issue I wouldn't instantly stamp off as resolved and close. If you're not totally sure that this should be resolved I'd keep it open until you're certain beyond reasonable doubt. (But I assume that's what you're going to do anyways making a large section of this message pretty much moot...)

**Comment by vollda** [comment] 2018-01-11 15:46
![2018-01-11_16 19 38](https://user-images.githubusercontent.com/35340471/34833069-d5f156b8-f6ee-11e7-84bb-b3770bb7ea61.jpg)
We have exact this Problem with ATM 3 Modpack and updated to the latest RS.
If we start autocrafting from 40k iron the forge tps goes up to
about 80ms (normal is about 22ms). On the Server side it skips
ticks (can't keep up! Did the system time change,...). If we stop the autocrafting task it goes back to normal. We also used mekanism furnace same problem.
Find attached the NPS File and the Screenshot of our construction.
Thank you very much

[rs.zip](https://github.com/raoulvdberge/refinedstorage/files/1623160/rs.zip)

**Comment by derdotte** [comment] 2018-01-30 13:38
@raoulvdberge Just profiled the very same issue with autocrafting 60k Glass through a Thermal expansion redstone furnace. I have 4 Speed upgrades inside the crafter and a rather fast signalum furnace as you can see in the screenshot.
![image](https://user-images.githubusercontent.com/18185863/35568805-73e91416-05ca-11e8-850e-1757d0d4cf7a.png)
Metainfo:
Modpack: Modern skyblock 2.8.1.1 expert mode
version: refinedstorage-1.5.31.jar

**Comment by Paril** [comment] 2018-02-04 04:19
So, I thought I'd provide some input from using this in Modern Skyblock 2 Expert Mode as well.
I have a setup with a lot of craftables. RefinedStorage's controller block seems to be ticking the most out of everything on my server, and I'm thinking it's related to crafting in some way. I'm getting a profile for you set up as I write this.

I'm using RebornStorage to give me a lot of pattern space, and my crafting stuff is mostly in CompactMachines, but the CMs are rather new for me and was lagging before I implemented them. It doesn't specifically happen when I cause a pattern to build. 

[samples.zip](https://github.com/raoulvdberge/refinedstorage/files/1692462/samples.zip)

It seems that something is causing the storage networks to keep rebuilding:
![](https://i.imgur.com/ogEQBTn.png)

Obviously, by the looks of it, RebornStorage is constantly causing the network to rebuild. @derdotte, are you also using the RebornStorage multiblock crafter?

**Comment by derdotte** [comment] 2018-02-04 16:59
@Paril yes, i was using the rebornstorage multiblock crafter, although it was not specifically tasked to craft my 60k glass, as that is a processing pattern which the multiblock is unable to do. So that entirely falls out of the calculation.

**Comment by raoulvdberge** [comment] 2018-06-18 16:22
In 1.6, crafting tasks that take more than 5 seconds to calculate will not be executed anymore.

**Closed by raoulvdberge** 2018-06-18 16:22 UTC
Labels: autocrafting, performance
