### ISSUE TITLE
JEI Recipes get edited when you program a pattern with the items.

### ISSUE THREAD

**Issue by truehunterethan** [raoulvdberge/refinedstorage#2255] opened 2019-06-06 22:24 UTC
#### Issue description:
Let's say i program a processing recipe for 9 iron plates to 1 dense iron plate, now all item recipes that use iron plates will display that 9 iron plates need to be used, even in crafting bench recipes, this does not apply when you craft something manually, so it does not physically change the recipe, but if you use it in a craft it requires that 9:1 ratio, ending up using 9 times as much.
#### What happens:
programming recipes "edits" recipes for items that were used to program a processing recipe.
#### What you expected to happen:
for the JEI recipes to be correct, and autocrafters to use the right amount of resources.
#### Steps to reproduce:
1.program a pattern in processing to use x amount of y resource (ex. iron, gold)
2. then look in jei/program a crafting table recipe that needs y resource. 
3.  or try to use an existing programmed crafting table recipe to see it's been edited to use x amount of y resource.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: forge-14.23.5.2836
- Refined Storage: refinedstorage-1.6.14.

Does this issue occur on a server? [yes/no]
don't know. probably.
#### If a (crash)log is relevant for this issue, link it here:
not relevant.
[pastebin/gist/etc link here]

**Comment by Darkere** [comment] 2019-06-07 05:29
Duplicate of #2216
Avoid using oredict when possible.

**Closed** 2019-06-07 07:08 UTC

**Comment by truehunterethan** [comment] 2019-06-07 20:29
So do you know how to fix this? like is it just a "i'll get to it" kinda thing?

**Comment by Darkere** [comment] 2019-06-07 20:44
You can fix your world by doing the same thing you did just in reverse. Aka make an oredicted processing recipe where you reduce the quantity of the item to 1 before creating it. 

Fixing the bug itself is hopefully not hard but I don't think anyone has looked at it just yet.

**Comment by truehunterethan** [comment] 2019-06-07 21:50
I have thousands of recipes that I'd have to re program. i want to know if I have to, or just wait for an update

**Comment by Darkere** [comment] 2019-06-07 22:03
You do not need to fix each individual pattern. What you need to fix is the item/recipe registry which is what JEI shows/appears when auto crafting. 

For example, if you have any recipe that shows you need 36 iron instead of 1 iron to make. Then all you need to fix is the iron ingot. By creating any random processing recipe that has 1 Iron ingot in it.

It is unfortunately very unlikely that an update will fix that issue for you.

**Comment by truehunterethan** [comment] 2019-06-07 22:06
Everytime a pattern with an iron ingot that was encoded pre-fix brings the bug back to life.

**Comment by truehunterethan** [comment] 2019-06-07 22:33
oops nevermind.

**Comment by truehunterethan** [comment] 2019-06-08 20:37
wait so i could just downgrade RS and itll fix it temporarily
