### ISSUE TITLE
Destructors aren't currently breaking blocks.

### ISSUE THREAD

**Issue by dorkinator** [raoulvdberge/refinedstorage#626] opened 2016-11-13 18:23 UTC
#### Steps to reproduce:
1. Place destructor
2. Place block on destructor
#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 8.0.99.99
- Refined Storage: 1.2.4

Does this issue occur on a server? [yes/no] Yes

**Comment by InusualZ** [comment] 2016-11-13 21:10
Do you have space for the "upcoming" block? How it's setup your system? 

Please elaborate a little bit more the issue.

**Comment by KaneHart** [comment] 2016-11-14 00:08
Any chance that you are using it on protected land of some sort?

https://github.com/raoulvdberge/refinedstorage/commit/71e11909b9eb68831090d90da3c39f57f33e6393

Recent they call for the break event now and you might not be able to break it on your property. If you use FTB Utilities and such. You might have to refer to their manual.

**Comment by Sniper3** [comment] 2016-11-14 00:17
I'm on the same server as Dork, what KaneHart said was the issue. The destructor stopped working on FTB claimed land, even your claimed land. Thanks for the input!

**Comment by raoulvdberge** [comment] 2016-11-14 00:24
Aha, thanks for finding the cause @KaneHart!

I can close this now.

**Closed by raoulvdberge** 2016-11-14 00:24 UTC
