### ISSUE TITLE
Refined Storage Auto Crafting Mekanismn machines broken

### ISSUE THREAD

**Issue by eihns** [raoulvdberge/refinedstorage#1990] opened 2018-09-14 20:56 UTC
#### Issue description:
So, first of all, thanks your that great mod, and since i last played so many things has improved, really good work. 

THANKS!

Now ive found a problem i didnt find on the internet.

The problem is that i cant auto craft the crusher from mekanismn with refined storage. If i manual put the correct items in the refinded storage grid, it works fine. The problem is that refined storage always tell me the tier before is missing (like if i want to create a advanced crusher, he says, the normal crusher is missing - he doesnt recognice the receipes correct. Or adds the receipes incorrect. I dont know how to descripte it technically, but i see in the grid that the manual crafted crusher is not in the same place like the receipes (which should be, since its the same item)

#### What happens: / #### Steps to reproduce:
1.) Ive set new receipes for crusher -> advanced crusher -> ... -> elite crusher
2.) Added all other receipes, which are working perfectly, it just says the "tier before" crusher is missing

#### What you expected to happen:
I expect that Refined storage crafts this machines correctly.

I actually want to add all other machines to auto crafting, so ill edit if that is only happening to the crusher or all machines. (tested, also happens with purification chamber, so i guess its all machines)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2760
- Refined Storage: 1.6.5

Does this issue occur on a server? [yes/no]
no - singleplayer

**Comment by eihns** [comment] 2018-09-14 21:13
Just btw, i also tried ore dict on and off, no difference. (i also set the drives to ignore nbt and ignore dmg, just to test) - didnt worked tho.

**Comment by eihns** [comment] 2018-09-14 22:00
So, i dont know where to start, now i noticed also while tryin to add the capacitators from ender io (the batteries placed on ground). These is refined storage also not recognizing.. so the issue may be on my side, but where to look? I have so many mods, i make now a new world with only needed mods and test in creative and willr eport back.

**Comment by eihns** [comment] 2018-09-14 22:43
Okay, it also happens in a minimal installation. My guess is refined storage is broken?

**Comment by eihns** [comment] 2018-09-15 13:43
Hi, i will try 1. I guess taht would fix it. So is this a JEI bug? Or Mekanismn?

2. What do you mean with that, sorry my mother language isnt english. Whats a tier installer (i know what tier means, but together with installer it doesnt make sense for me xD)

**Comment by VT-14** [comment] 2018-09-15 13:54
I assume its on Mekanism's side.  It has a bit of a reputation for doing things a bit strangely.

Basic/Advanced/Elite/Ultimate tier installers are universal upgrade items that can be right clicked on blocks to upgrade them to the next tier.  I don't think they work on cables/pipes, but should work on any other block that has tiers (Machines/Factories, Gas Tanks, Energy Cubes, etc.).

**Comment by eihns** [comment] 2018-09-15 18:41
I tried it with manual casting and adding... Its not working. You cant auto craft any mekanism maschines....

**Comment by raoulvdberge** [comment] 2018-09-15 18:59
What VT-14 said.

**Comment by eihns** [comment] 2018-09-15 19:07
What exactly? He said manual build the blocks and it shoudl work, but it doesnt work.

If you dont want / can fix this, where i need to report this? Is it a meka bug? But they will say "blabla manual crafting works, its refined storage problem".

**Comment by raoulvdberge** [comment] 2018-09-15 19:10
It's being finicky with nbt in it's recipes. It does not play well with autocrafting. This is a mekanism problem.

**Comment by raoulvdberge** [comment] 2018-09-15 19:11
I will reopen this for you and take another look tomorrow. But it's most likely not on RS' side.

**Comment by DarkHelmet433** [comment] 2018-09-16 02:15
This does actually work. The problem is the metadata that is registered in JEI does not match reality.

Specifically, what you must do to make this work:

- create pattern for Energized smelter, autocraft it to RS storage.
- create pattern for Basic smelting factory. clear the JEI-supplied energized smelter, drag/place the previously crafted one from the grid above into the pattern.
- repeat for each tier

Although I don't believe it applies in this particular case, for certain mods it is *VITAL* to never pick up the crafted items and either place them in your character inventory or hotbar - the act of doing with those mods does things like add an NBT tag for the last owner, or adds the initial damage/charge values to NBT, or an chargeable item gets charged, etc.

Demonstration, crafting *two* Elite Smelting Factory after doing the procedure above:

- https://i.imgur.com/i11xOCF.png  (showing the intermediates)
- https://i.imgur.com/SIPdazc.png (the whole crafting plan)
- https://i.imgur.com/5EfRKwO.png (the result, two elite factories)

All I did to make this work was replace the input component from JEI with the actual component that was produced by the previous step.  If there was an 'Ignore NBT' toggle for the pattern, this could also solve it.

**Comment by eihns** [comment] 2018-09-16 10:00
Yeah, thats what i also did (make manual and place) doesnt seem to work for every factory.

**Comment by eihns** [comment] 2018-09-16 10:04
If a ignore NBT would fix it, i would be happy to get this added :D

**Comment by raoulvdberge** [comment] 2018-09-16 10:13
Of course that wouldn't be a fix. That would break crafting recipes that do depend on NBT. And making that a user choice isn't an option, as then the user decides what recipes break and what doesn't. Closing this as @DarkHelmet433 has provided a solution (thank you!).

**Closed by raoulvdberge** 2018-09-16 10:13 UTC
Labels: Area: Autocrafting, Area: Crossmod, Status: Invalid, Type: Bug

**Comment by thelapisfox** [comment] 2019-03-15 06:48
I'm requesting this to be reopened as this has not been fixed and the above fix added by DarkHelmet433 does not work. I have tried that solution on multiple recipes to no avail. For example;

I am trying to autocraft the Solar Generator from Mekanism so I do the following;
1. Set up a pattern for the Energy Tablet;
2. Use the RS system to create the Energy Tablet;
3. Set up a pattern for the Solar Generator;
4. Remove the Energy Tablet from the pattern and drag & drop it from the RS system inventory to the pattern;
5. Attempt to autocraft the Solar Generator. System states it cannot find any Energy Tablets nor is it able to craft the item itself through the Solar Generator's pattern.

This issue is making it extremely inconvenient.

**Comment by Darkere** [comment] 2019-03-15 16:37
Make sure you have Oredict turned off as this has been working for me without issues for as long as I remember.

**Comment by thelapisfox** [comment] 2019-03-29 01:55
That is technically not 'without issues' as 'without issues' would mean it would work regardless and yes, turning off oredict on the recipes seems to fix it. So now I have to fix dozens of recipes.

**Comment by turret001** [comment] 2020-03-08 02:54
This is still happening unfortunately. Sorry for the bump but I've tried tracing the steps of DarkHelmet433 but didn't work. 

List of things I've tried:

- removed my flux capacitor so it doesn't automatically power the machine, tried using it in the recipe, didn't work.

- tried placing and breaking the machine and used that in the autocrafting recipe, didn't work as well.

- tried placing a freshly crafted, non-placed, non-powered Enrichment Chamber as material for the autocrafting recipe, that didn't work as well.

**Comment by Jacob345k** [comment] 2020-05-18 01:45
This is still not working, trying to make induction cells and cant auto craft

**Comment by eihns** [comment] 2020-05-18 20:29
yeah, nearly all of the maschines (i think all of them) are not working. But refined storage says its mekanismn fault, mekanismn say its refined storage fault... problem have the users...

**Comment by Darkere** [comment] 2020-05-18 20:32
Here is a demonstration on how you make it work.
https://gfycat.com/FloweryOpulentAmericankestrel

If this doesn't work for you some other mod is messing with it. No idea which mod that would be.

Also, this is only a problem in 1.12. In 1.15 mekanism changed to allow it to just work. So as the mekanism devs don't work on 1.12 anymore don't expect any fixes to come for this.

**Comment by eihns** [comment] 2020-05-18 20:42
The gif you shared, is for 1.15?

**Comment by Darkere** [comment] 2020-05-18 20:46
No for 1.12.

**Comment by eihns** [comment] 2020-05-18 20:48
Ill retest.

**Comment by Lallyp123** [comment] 2020-06-23 19:48
If anyone is wondering whether doing whats in the gif fixes the problem the anser is yes well at least for me.

**Comment by luizhj** [comment] 2020-10-31 01:25
just to help other peoples with the same problem in the 1.12.2
this problem apparently also occurs with energy cubes.

to solve it in my game I crafted the energy cube on the crafting grid, put it into the system, then used this crafted item into the pattern.
