### ISSUE TITLE
Network graph doesn't work well on chunk borders

### ISSUE THREAD

**Issue by ShaCraft** [raoulvdberge/refinedstorage#370] opened 2016-09-20 18:30 UTC
When ever there is a server restart I have to break half the blocks in RS and put them back down for them to work again.

Many blocks stop working after reboot.  Solderer, Grids, importer, exporter.. ect. 

It can be a big pain to have to break a mid sized network for automation to work. 
- Minecraft: 1.10.2
- Forge:  2029
- Refined Storage: 1.0.4

Does this issue occur on a server? yes

**Comment by raoulvdberge** [comment] 2016-09-20 22:06
As a workaround, just breaking + replacing the Controller would work

**Comment by ShaCraft** [comment] 2016-09-20 22:42
I thought I tried that but maybe it was just a grid. I'll give that a shot next reboot and report if it worked here. Thanks.

**Comment by ShaCraft** [comment] 2016-09-21 04:12
Nope you have to break each block to get them to work. Breaking the Controller will not fix the issue.

**Comment by ShaCraft** [comment] 2016-09-21 04:25
https://youtu.be/jeyL_Mt7Seo

**Comment by ambassadorkosha** [comment] 2016-09-24 20:39
http://pastebin.com/qYKHC0eB

**Comment by N-kay** [comment] 2016-10-17 10:20
For me, this only started happening after I hid my cabling with Chisel & Bits.

>Nope you have to break each block to get them to work. Breaking the Controller will not fix the issue.
That workaround actually works for me.

**Comment by eslachance** [comment] 2016-12-19 06:08
Would be nice to have an update on this issue. It's still present in version 1.2.11...

**Comment by raoulvdberge** [comment] 2016-12-19 10:08
I haven't found a fix for this issue yet because I don't know what causes it in the first place, and, it's not 100% reproduceable. Chunk loading mechanics and network building in MC are very complicated.

**Comment by raoulvdberge** [comment] 2016-12-22 00:15
This issue has been fixed for mc1.11.

**Closed by raoulvdberge** 2016-12-22 00:15 UTC
Labels: bug

**Comment by way2muchnoise** [comment] 2016-12-22 09:02
Related commits 58695b1ab4c8e8819d1ed0b5a8f29eaf162a4d5e 2dc6a39da44f8586fd36aad2bddae1f2fa2cb320 9b1b52daea4203a1236b28a163c583614c096bdc

**Comment by tomasdev** [comment] 2017-01-07 08:40
When would this be released?

**Comment by way2muchnoise** [comment] 2017-01-07 11:48
It is in the 1.11 branch, might get backported at some point as it is quite the rewrite and not 100% stable yet.

**Comment by DietmarKrause** [comment] 2017-03-17 06:29
I have seen it too and at least in my case it was an issue of ftb utils chuncloading system. In my case everything works fine with chicken chuncs chunkloader with otherwise unchanged system (modded 1.10.2 , SP World). i would recomend not to use ftb utils chunkloader unless the issue there is solved. Issue is described there: https://github.com/LatvianModder/FTBUtilities/issues/360

**Comment by Yorkforce** [comment] 2017-03-17 12:49
I guess the chance of getting this backport pushed forward would be difficult?
We just ran into this problem on one of our servers, which is locked to the modpack, as pretty much 90% of modpacks are settled on 1.10 now and this is a bit of an issue for most/all modpack servers.

**Comment by raoulvdberge** [comment] 2017-03-17 16:00
I've stated MULTIPLE times this *might* get backported to 1.10. Stop. Asking. The. Same. Fucking. Question. I know how much this causes an impact, and no, I have not had time to fix this yet.
