### ISSUE TITLE
Processing patterns not displaying recipe

### ISSUE THREAD

**Issue by wesker1213** [raoulvdberge/refinedstorage#2199] opened 2019-03-25 02:26 UTC
#### Issue description:
Whenever in my autocrafting setup, I go to make a processing pattern, the recipe grid fails to show the recipe, but will still make the pattern. So say 1 ore (I know we don't do it that way) = 1 ingot, nothing in the recipe/result grid displays, but the create button will creates the recipe.
#### What happens:
See above
#### What you expected to happen:
I expected it to display properly so that I can chose which dictionaried items to use like in the past.
#### Steps to reproduce:
1. Pattern Terminal
2. Make processing pattern
3. 
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2772 (still exists for current version of forge as of this posting)
- Refined Storage: 1.6.12

Does this issue occur on a server? [yes/no]
Occurs both on server, and in single player
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment] 2019-07-21 09:46
Duplicate of #2200

**Closed by raoulvdberge** 2019-07-21 09:46 UTC
Labels: Bug
