### ISSUE TITLE
Can't take a Stone Jetpack from Just Jetpacks mod out of the Grid

### ISSUE THREAD

**Issue by c0rn3j** [raoulvdberge/refinedstorage#167] opened 2016-07-07 14:59 UTC
http://i.imgur.com/4N3wcl7.png

JustJetpacks-1.10-1.0.0.jar
refinedstorage-0.8.5.jar
forge-1.10.2-12.18.0.2007-1.10.0-installer.jar

**Comment by raoulvdberge** [comment] 2016-07-07 15:06
Duplicate of another issue

**Closed by raoulvdberge** 2016-07-07 15:06 UTC
