### ISSUE TITLE
Epic lagg when a disk fills then frees up space.

### ISSUE THREAD

**Issue by Maszter2015** [raoulvdberge/refinedstorage#1055] opened 2017-03-12 20:22 UTC
#### Issue description:
Epic lagg when a disk fills then frees up space.
#### What happens:
When a disk fills up and frees up space continuously(autocrafting) the fps drops to unplayable.
#### Steps to reproduce:
1. Do a complex autocrafting like solar panel 6 in ftb infinity lite with 1 full and 1 half filled disk.
2. IF the system is big enough underpowering it cause lag too(continously turn off and on).
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2234
- Refined Storage:1.2.22

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment] 2017-03-12 21:14
Please add a nps file, the link below describes what to do.

https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by Maszter2015** [comment] 2017-03-13 15:40
https://www.dropbox.com/s/koe7tcquvx6188t/logs.zip?dl=1

**Comment by raoulvdberge** [comment] 2017-04-01 17:54
Duplicate of #838

**Closed by raoulvdberge** 2017-04-01 17:54 UTC
Labels: investigate, performance
