### ISSUE TITLE
[1.15.2]Console error

### ISSUE THREAD

**Issue by EnterFor** [raoulvdberge/refinedstorage#2472] opened 2020-04-04 11:46 UTC
#### Issue description:
I don't know if this is normal. I don't feel anything in the game
#### What happens:
Console error
#### What you expected to happen:
None
#### Steps to reproduce:
None
#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.15.2
- Forge:31.1.35
- Refined Storage:1.8.1

Does this issue occur on a server? [yes/no]
yes!!!!

#### If a (crash)log is relevant for this issue, link it here:
![image](https://user-images.githubusercontent.com/10114685/78448743-ba48b100-76ac-11ea-8328-e09206de1fbe.png)

**Comment by raoulvdberge** [comment] 2020-04-25 18:26
Not sure what to do. Some pattern is no longer a valid pattern. Can't reproduce this either, so closing.

**Closed by raoulvdberge** 2020-04-25 18:26 UTC
