### ISSUE TITLE
Controller Randomly Stops Working

### ISSUE THREAD

**Issue by Mohron** [raoulvdberge/refinedstorage#133] opened 2016-06-21 10:31 UTC
Version: refinedstorage-0.7.16

My Refined Storage system will randomly stop working while being used remotely for storage via an EnderChest exporting to an interface.  The system is chunkloaded and that may have something to do with the issue.  Essential what happens is the system will stop accepting items and when I return to it I find the system has stopped working: all of the components have disappeared off the controller's GUI (see screenshot) and are non-operational.  Toggling through the redstone settings on the controller completely through one-time seems to "restart" the controller and everything works as if it never happened.

![deadcontroller](https://s32.postimg.org/kfikcpwpx/RSDead_Controller.png)

**Comment by raoulvdberge** [comment] 2016-06-21 14:04
This is a duplicate of #104

**Closed by raoulvdberge** 2016-06-21 14:04 UTC
