### ISSUE TITLE
Thermal Foundation Bronze OreDict Problem [1.10.2, SF3]

### ISSUE THREAD

**Issue by XxZajoZzO** [raoulvdberge/refinedstorage#1045] opened 2017-03-10 21:25 UTC
#### Issue description:
Crafting system thinks Lead gears are the same thing as Bronze ingots when oredict is enabled. I checked ore dictionary entries for gears and bronze and there is nothing wrong. So I assume this is a RS problem.

#### What happens:
It says it will craft lead gears then it crafts them but it can't use them in a recipe so it crafts them again. I had 100+ lead gears in RS system after half a minute. (When crafting Bronze gears from TF).

#### What you expected to happen:
I was expecting bronze gears to be crafted.

#### Steps to reproduce:
1. Teach it how to make Lead and Bronze gears.
2. Request Bronze gears

#### Version (Make sure you are on the latest version before reporting):
- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Refined Storage: refinedstorage-1.2.22

Does this issue occur on a server? No

#### If a (crash)log is relevant for this issue, link it here:
https://dl.dropboxusercontent.com/u/92370990/MC/fml-client-latest-6.log
#### Screenshot
http://i.imgur.com/LpHQiuk.png

**Comment by L0laapk3** [comment] 2017-03-19 15:19
Ive seen a similar problem in version 1.2.18 with different color dyes on pam's harvestcraft epic bacon recipy with oredict enabled: [http://imgur.com/a/CgyEe](http://imgur.com/a/CgyEe)
The pack had botania dyes and gendustry dyes, tahts why I enabled oredict.

**Comment by raoulvdberge** [comment] 2017-07-04 21:43
Duplicate of #1045

**Closed by raoulvdberge** 2017-07-04 21:43 UTC
Labels: autocrafting, bug
