### ISSUE TITLE
Server Crash Ticking Entity.

### ISSUE THREAD

**Issue by SgtSnipey** [raoulvdberge/refinedstorage#1583] opened 2017-12-21 16:59 UTC
#### Steps to reproduce:
1.Load  my edited direwolf20 pack and world and watch it fail to start
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.1.2568
- Refined Storage: 1.5.28

Does this issue occur on a server? [yes/no] Yes

#### If a (crash)log is relevant for this issue, link it here:
 
  ##https://pastebin.com/GbMNe0A1

[pastebin/gist/etc link here]

If I missed something up sorry. Also if ya need more let me know.

**Comment by raoulvdberge** [comment] 2017-12-22 13:28
Duplicate of #1580

**Closed by raoulvdberge** 2017-12-22 13:28 UTC
