### ISSUE TITLE
Issue with external crafting making doubling the necessary ingredients

### ISSUE THREAD

**Issue by utoc** [raoulvdberge/refinedstorage#592] opened 2016-11-06 21:37 UTC
#### Issue description:

Using external crafting for materials, RS will create twice as much material as needed to make the item.  This is new behavior in 1.2.3 that didn't exist in 1.2.beta5 and friends

Lets say you need 10 of A which needs 80 of B and 10 of C total.  C is a resource you have available and needs no crafting.  B has external crafting that needs 8 of D and 4 of E to make 8 of B.  RS will make 160 of B even though it only needed 80.

If you request autocrafting of B directly, any quantity, it crafts the correct number of items with no overflow
If you request autocrafting of A, quantity of one, it crafts the correct number of items with no overflow.
If you request autocrafting of A, >1, it will always double the amount requested for B.

The crafting preview ALWAYS shows the right number though!

#### What happens:

See here:  http://i.imgur.com/cUAMnFn.gifv

its YUUUGE, just wait for it to load.  RIP Mobile Data

The image shows some very weird blinky blinky behavior that may or may not be a clue to the issue.  I'm a little stumped on this one

#### What you expected to happen:

It should not craft double the items.

#### Steps to reproduce:

See above.  I don't have a vanilla case that works; these are using Mekanism as an example.  This did work prior to 1.2.3 (beta5 was a known working example)

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2122
- Refined Storage: 1.2.3

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by moRt1MC** [comment] 2016-11-06 21:41
I have same problem made a little video of the problem:

https://www.youtube.com/watch?v=ux0mw4a3ibs

**Comment by utoc** [comment] 2016-11-06 21:48
@moRt1MC My issue and yours aren't quite the same; I'm having autocrafting issues.

**Comment by moRt1MC** [comment] 2016-11-06 22:00
@utoc Yea i posted it in the wrong page. I deleted the post sorry.

**Comment by raoulvdberge** [comment] 2016-11-06 22:34
Can you reproduce this issue on a new world with just a 64k storage block as storage?

**Comment by brad18** [comment] 2016-11-06 22:59
Update: The bug is in beta 1.5(perhaps lower versions). I just ordered 64 steel casings from mekanism and its outputted about 2k extra steel than needed.

What would you like me to test?

**Comment by raoulvdberge** [comment] 2016-11-06 23:08
Can you tell me the exact beta 1.2 where this bug starts?

**Comment by brad18** [comment] 2016-11-06 23:39
I've noticed that you have taken down the beta downloads, any chance you're still hosting them somewhere so I can test it?

**Comment by raoulvdberge** [comment] 2016-11-06 23:49
Agh, that is true.. forgot about that :/ In fact, we might not need them anymore for testing. We know enough now that we know that this bug existed in the betas already.

**Comment by brad18** [comment] 2016-11-07 00:03
Ok. Thought I'd give 1.1.3 a quick try and can confirm it does work correctly in 1.1.3 so it is definitely something in 1.2.

**Comment by brad18** [comment] 2016-11-07 00:10
This might help in tracking down the bug. When I order the steel on it's own, it works fine. It's only when it needs to autocraft for something else (such as a steel casing) that it messes up. I've noticed that in the "Items crafting" section of the monitor, it will count down the steel despite the steel not actually being received. Once the steel reaches 0 on the counter, it will flicker and go back up to somewhere around the original amount. When it does this, it will spit out another load of iron and coal to craft even more steel.

**Comment by way2muchnoise** [comment] 2016-11-20 19:16
@brad18 Is there for some reason something that just inserts steel for some reason? Cause you can see it go down in the monitor, at which point the autocrafting assumes it is in the systems. But when trying to do the next step it won't have the materials and reschedule thus making more steel (which was still processing).

Could you share your setup, cause I can't reproduce with mine. (That being a single alloy smelter processing steel dust to steel)

**Comment by brad18** [comment] 2016-11-20 19:51
http://imgur.com/a/nlVbl

This is the setup which makes steel for me. A crafter exports (via a pattern) 8 iron and 2 compressed carbon to craft 8 steel ingots.Note that the upper chest is the only place in the system where steel gets inserted. The setup then does its stuff and outputs to the upper chest with an importer on it. If I order 512 steel on its own, I will get 512 steel. If I was to order 64 steel casings which require 512 steel ingots then I get the 64 casings however the crafting goes insane. It will the output the initial amount of stuff, then it will wait and spit out some items then do that again and again and again until I end with about 2k more steel than I need.

Note that I also got this behaviour on many other things. Yesterday, I autocrafted 16 induction cells and ended up with abour 48k red alloy from mekanism.

**Comment by way2muchnoise** [comment] 2016-11-20 19:56
As I said you can see the items go down in the monitor, right? That means somewhere there is steel being inserted. Or what ever other material for that matter. That causing a reschedule and inserting more into your input chest. Could there be any io flow of steel in your system that is messing up the status and thus causing reschedules?

**Comment by brad18** [comment] 2016-11-20 20:00
Yeah I can see the number of steel going down but that is the only place in the system where steel can get inserted and it looks like the number is going down faster than the setup can make it.

**Comment by way2muchnoise** [comment] 2016-11-20 20:05
So for some reason it thinks more gets inserted that actually is. Hmmm, no clue where that is coming from. Also kinda related to #597 now.

**Comment by brad18** [comment] 2016-11-20 20:07
If it's any help, I was playing about with the betas a while ago(compiled myself) and I noticed that the initial issue existed in beta 1 where it would approximately make double what was needed. Then I believe the transition from beta 3-beta 4 or beta 4 -beta 5 introduced the run away crafting where it made tons of items.

**Comment by way2muchnoise** [comment] 2016-11-20 20:11
I can't recall when I implemented the rescheduling, but that is for sure causing the extras here. Although the root of the problem is the system reporting that more ingots are done than really are. If the calculation preview shows the correct numbers that it isn't related to the calculation, but further down the line.

**Comment by brad18** [comment] 2016-11-20 20:15
I can confirm that the calculation preview does report the right numbers. Although I have noticed that on very large, multiple stage crafts that it will be fine and calculate the number of items properly however if I enter a large number of items to craft, it will freeze trying to open the calculation screen. For example, I am unable to make a stack of mekanism induction cells as it gets stuck but I can craft 16 of them. Want that in another bug report?

**Comment by way2muchnoise** [comment] 2016-11-20 20:17
If there is anything in the log than yes, but tbh mekanism is really buggy and unstable. We already have lot of hacky fixes just for it to work with the horrible mekanism state atm.

**Comment by brad18** [comment] 2016-11-20 20:20
ok. I'll have to wait for utoc to get back to see if there is anything in the logs.

**Comment by utoc** [comment] 2016-11-20 23:35
Still hunting @brad18 but you can get with @3pixel for log in the meantime.

It sounds like we need to find a mis-scheduling of ingots in a non Mekanism
route though to confirm if this is Mek issue or RS. I have some ideas we
can test after Thanksgiving @brad18

**Comment by brad18** [comment] 2016-11-21 21:55
Been testing a bit more and the results are interesting. This is going to be a long one :) . 

Let's start off with the original problem. 8 compressed iron and 2 compressed carbon goes to 8 steel ingots in a crafting pattern. Crafting steel on its own is fine but when nested inside another recipe, the craft will produce significantly more steel than necessary. 

First, I have located the reason for the significant extra amount of items. The problem is not really the rescheduling. Let me start by explaining my testing process. I recreated the recipe for the steel casing using vanilla-ish items. 
I made a recipe containing 8 stone and 1 crafting table goes to a Terraqueous CraftBench where the stone is acquired via a  1 cobble ->  1 stone external crafting process. This worked perfectly to make 64 CraftBench's. Then I realised that I didn't recreate the recipe properly so I recreated it to be 2 compressed carbon and 8 cobble -> 8 stone where the carbon just sits in a chest. Now this is where it gets interesting, this recreated the problem with the steel ingots. I noticed in the crafting monitor that when the recipe is 1 - 1, it monitors incoming items correctly however **when the recipe is something like 2 items + 8 items -> 8 items, the system is grossly overestimating the incoming items**.This would be fine on a single craft as the items will just flow in after RS thinks the craft done however in a nested craft, the system thinks everything has arrived, realises it has nothing to craft with and then spits out another batch of items. So say I order 64 CraftBench's, it will make the first one, spit out items for 63 benchs, make the next one then spit out enough items for 62 CraftBench's and so on.

**Comment by brad18** [comment] 2016-11-21 22:14
Found the problem. If you set a pattern to return anything other than a single item, it will count a single item as x number of items defined in the craft. For example, if the craft returns say 1 steel, it will count each item correctly, if the craft returns 8 steel, it will count each steel coming in as 8 steel in the monitor. A craft returning 16 items will count each imcoming item as 16 of that item thus making the count in the monitor decrease rapidly.

**Comment by way2muchnoise** [comment] 2016-11-21 22:31
Yeah, I noticed and I might have a fix ready soon™ :D

**Comment by way2muchnoise** [comment] 2016-11-21 22:34
Didn't really wanna close it with that commit, but it should be gone 💯

**Closed** 2016-11-21 22:34 UTC
Labels: autocrafting, bug

**Comment by way2muchnoise** [comment] 2016-11-21 22:36
Would also like to give my humble thanks for the great debugging work you guys did on this. This is an example bug report and interaction.

## Making RS great again!

**Comment by brad18** [comment] 2016-11-21 22:44
Not a problem. Keep up the good work 👍

**Comment by brad18** [comment] 2016-11-21 23:12
Just tested the build and I can confirm that the problem has been fixed @way2muchnoise 
Thank you 👍 

You can probably close #597 now.

**Comment by raoulvdberge** [comment] 2016-11-22 10:36
Yay! Thanks @way2muchnoise
