### ISSUE TITLE
A pattern with a chest recipe does not show the chest icon when pressing SHIFT

### ISSUE THREAD

**Issue by calloatti** [raoulvdberge/refinedstorage#1133] opened 2017-04-06 16:31 UTC
#### Issue description:

A pattern with a chest recipe does not show the chest icon when pressing SHIFT

See screenshots here:

http://imgur.com/a/AToqD

Add a chest pattern to a crafter, open the crafter GUI, press SHIFT to see the pattern result icons

#### What happens:

A pattern with a chest recipe shows a blank icon

#### What you expected to happen:

A pattern with a chest recipe should show a chest icon

#### Steps to reproduce:
1.Add a chest pattern to a crafter, open the crafter GUI, press SHIFT to see the pattern result icons
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:v12.18.3.2254
- Refined Storage:

  EnderCore-1.10.2-0.4.1.65-beta
  EnderIO-1.10.2-3.1.179
  MCMultiPart-1.4.0-universal
  refinedstorage-1.2.25

Does this issue occur on a server? [yes/no]

N/A

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment] 2017-04-06 17:02
Duplicate of #609

**Closed by way2muchnoise** 2017-04-06 17:02 UTC
