### ISSUE TITLE
Items on RS Disks not showing up on Crafting Grid after move.

### ISSUE THREAD

**Issue by YATYAS82** [raoulvdberge/refinedstorage#821] opened 2017-01-04 08:10 UTC
#### Steps to reproduce:
1.Place items in RS system
2.Move RS system somewhere else
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.3.2185
- Refined Storage:1.2.8
- Hermitpack: 1.5.1

Does this issue occur on a server? [yes]

#### If a (crash)log is relevant for this issue, link it here:N/A

Made a [video](https://youtu.be/74Yg-UzLP_o) of what I'm seeing. 
This is my first report so I hope I described everything as best as possible

**Comment by way2muchnoise** [comment] 2017-01-04 10:30
Seems related to #712 , I have never had this happen and tbh 1.2.8 is a really old version. Hermitpack should update that.

**Comment by raoulvdberge** [comment] 2017-01-04 15:16
On that video, was your grid still full *before* removing the drives?

**Comment by YATYAS82** [comment] 2017-01-05 06:12
Yes, 4 out of 5 of them were full the other about 2/3rds full. 

There are a few mods HP needs to update. You might have noticed the Mekanism mods textures in inventory as well as the atomic disassembler in hand are broken as well. If all it needs is the update I can wait. #712 isn't what I'm experiencing though. I can put the disks in and take them out just fine as shown in the video. 

Thanks for your time.

**Comment by raoulvdberge** [comment] 2017-01-08 19:34
I can't reproduce this (on a server):

![x](https://raoulvdberge.com/RaHF9m)

This might be a crossmod issue?

**Comment by YATYAS82** [comment] 2017-01-09 03:45
Hermitpack updated RS to .16 hoping that it will solve the problem. In your vid you didn't break down the whole system and move it somewhere else.

**Comment by raoulvdberge** [comment] 2017-01-09 04:36
I did move the system, but didn't have it on a gif. This is what I did:

- Broke the disk drive manually with a pickaxe, put all the disks somewhere else in another system
- Took all the disks out manually, put all the disks somewhere else in another system

Still wasn't able to reproduce.

**Comment by YATYAS82** [comment] 2017-01-10 16:03
Sorry for the delay. We had server issues when updating to the new version of HP. I'll test today and try to reproduce. We are now running RS .16 on Hermitpack 1.6. Hopefully the issue was just from the outdated RS version

**Comment by raoulvdberge** [comment] 2017-01-10 16:32
If it's not fixed, please try with those 2 mods removed. Thanks.

**Comment by YATYAS82** [comment] 2017-01-14 05:01
Issue still exists. https://youtu.be/kCzaR4rb8dw I forgot to take off those 2 mods but I'm doing another test now without those installed

**Comment by YATYAS82** [comment] 2017-01-14 05:18
Just finished testing without those mods https://youtu.be/C87_47Rrqhs It does seem like it's those mods that are bugging out the 64k disks. Just in case I should add that it was done on a single player world.

**Comment by raoulvdberge** [comment] 2017-01-14 11:10
Great to know! Once I can I'll spin up a test server and test with those mods as well.

**Comment by Twonkk** [comment] 2017-01-15 00:11
I don't mean to steal someone else's thread, but this same issue has happened on my FTB Infinity Lite 1.10 (using 1.5.1 mod pack).. I created a Solderer, Controllor, Grid, 4k drive and disk drive.. had it all set up, moved my items from chest to it and then decided to move the entire grid down stairs.. I broke everything with a pickaxe (i did not remove disks from disk drive prior to breaking). Reset everything and it shoes the disk drive has something on it, but nothing appears in the grid.

Version (Make sure you are on the latest version before reporting):

Minecraft: 1.10.2
Forge:12.18.3.2185
Refined Storage:1.2.14
Infinity Lite Pack 1.5.1

**Comment by raoulvdberge** [comment] 2017-01-15 01:08
Can you try removing InvTweaks and see if you can still reproduce this? @Twonkk

**Comment by Twonkk** [comment] 2017-01-15 04:18
@raoulvdberge

Will try that tomorroq after work.. I'll set up a small test server and see if I can reproduce it with out invtweaks.. will let you know

Twonkk

**Comment by raoulvdberge** [comment] 2017-01-15 05:17
Thank you!

**Comment by TNTchicken99** [comment] 2017-01-31 13:17
I have a Sky Factory 3 server, running version 3.0.6. All mods are supposedly up to date. I was moving my entire base, put everything into my RS system, then broke the drive cages, and transferred the system. Upon arrival at the new base, I loaded my 10+ 64k drives, all completely full, and none of my items showed up. I tried everything to solve this issue client side and nothing worked. Different controllers, different drive cages, different grids, nothing. Inventory tweaks is not a mod in the pack, however there is an inventory organizer called Inventory sorter.

**Comment by Hugekase** [comment] 2017-02-04 19:17
Hi there, I am running a server on SF3 and the same thing happened. A friend moved his system, and everything glitched and now he lost all his items.. What is going on?

**Comment by raoulvdberge** [comment] 2017-02-05 10:35
I have no idea.

**Comment by thebigpixl** [comment] 2017-02-05 18:09
Had the same just happen to me, tried to move my system, some of the drives are borked.  following from logs / tickprofiler :  http://pastebin.com/i873yqBW

Custom mod pack
Minecraft: 1.10.2
Forge:12.18.3.2185
Refined Storage:1.2.8

**Comment by TNTchicken99** [comment] 2017-02-05 18:20
I gave up trying to solve. luckily I had a previous backup form before
building the new base. restored to the backup, and used world edit to copy
and paste the base back into the old world with uncorrupted drives. Lesson
learned, Refined Storage is still a work in progress, and DO NOT
EVER destroy a drive cage before REMOVING THE STORAGE DISKS BY HAND.

**Comment by thebigpixl** [comment] 2017-02-05 18:24
I remember seeing in a log an error along the lines of there being an NBT tag with a length error (long).  I can't find that one or I would pastebin it.

**Comment by TNTchicken99** [comment] 2017-02-05 18:27
if the problem is an NBT tag being too long, then the problem could be
replicated by simply using the same drives. However the first person to
report this to this thread said they couldn't reproduce it correct?

**Comment by thebigpixl** [comment] 2017-02-05 18:32
I can provide a player.dat with the effected drives in inventory if @raoulvdberge or someone else wants to examine it.

**Comment by earthy329** [comment] 2017-02-08 07:08
Playing Direwolf20 1.10.2,1.3.2 on a home server (private) when moving base around and dissembled RS noticed that a 4k storage cell reads 1k in Walla but gui says 4k moved it with pick axe and replaced it with 64k storage cell and still says 1k. remove all items from 4k cell and used disk manipulator to dump all onto a 64k drive and have lost all items . this is second time of trying to move disk drive after 1st time reset world to old save to try again. what am i doing wrong!!

**Comment by raoulvdberge** [comment] 2017-02-08 07:21
You are doing nothing wrong, this is a Forge bug most likely...

**Comment by TNTchicken99** [comment] 2017-02-09 05:17
Don't break the drive cage. Remove the storage cells by hand, then break the cage once EMPTY. that seems to avoid the problem

**Comment by smiths1696** [comment] 2017-02-12 00:41
Just had this issue as well.  I had a basic system 1 controller, 1 drive cage, 1 crafting grid.  I had a 4k disk in the drive cage.  I moved the controller, not the drive cage, and connected an importer.  The 4k storage filled up once the importer was connected I then went to open the system, and only the items being showed were the items being imported.  I restarted my client without InvTweaks and MouseTweaks.  It's not so much of an issue, because I'm a senior admin on the server so I can get my stuff back, and replace the lost items, but it is disconcerting because players cant do that.  The server is running on MC 1.10.2, Forge 12.18.3.2185, and Refined Storage is version 1.2.20.  It's the latest Hypothermia pack on Curse.

http://prntscr.com/e7l3fj
http://prntscr.com/e7l4c0
http://prntscr.com/e7l55t
http://prntscr.com/e7l4tq
http://prntscr.com/e7l4y8

**Comment by raoulvdberge** [comment] 2017-03-04 19:55
This is a Forge bug.

**Closed by raoulvdberge** 2017-03-04 19:55 UTC
Labels: bug, can't reproduce

**Comment by techbrew-mc** [comment] 2017-11-18 03:32
This just happened to me on 1.12.1 with Forge 14.22.1.2478 and RS 1.5.23.  All mods:
![modlist](https://user-images.githubusercontent.com/2521490/32976561-4a2f8f34-cbd6-11e7-9f0e-4f973f2698ec.png)

**Comment by raoulvdberge** [comment] 2017-11-18 10:12
Forge bug unfortunately, that was fixed but came back.

**Comment by NotAnnieGood** [comment] 2018-02-02 09:57
So, how can I retrieve the items that were in the system prior to the bug?
A creeper blew mine up and the same thing happened xD

**Comment by raoulvdberge** [comment] 2018-02-02 10:02
Retrieve from backup.

**Comment by NotAnnieGood** [comment] 2018-02-02 10:12
Why did I not think of that even after reading this *sigh* 
Thank you xD

**Comment by ZephD** [comment] 2018-08-27 20:01
Heya.
This issue seems to be about again/still.
I even rolled back my server to before I even made the RefStore system.
When I made it all, and added a disk, and connected another chest, I could not see any items from the chest or disk.
Luckily I only have ~25 items on the disks which I cannot retrieve.

Strange though, I can still use it to craft items. So the items _are there_, we just cannot see them.

Is there any news on this issue from the Forge guys?

**Comment by raoulvdberge** [comment] 2018-08-27 20:03
On which version are you.

**Comment by ZephD** [comment] 2018-08-27 22:28
Sorry, 1.6.3 (FTB Revelations)

**Comment by Meepin** [comment] 2018-10-02 20:54
I am getting this same problem on a much later version of Forge(14.23.4.2760) when the forge bug should have been long resolved. The contents of the disk are not visible in the grid, despite replacing all the components, I made sure to removed the disks before breaking the storage drive. I can still use JEI to shift-click items into the crafting grid though. 

I am playing the Modpack Stoneblock v1.0.17 without mouse tweaks or inventory sorter installed. Problem is still persisting though.

Please help, I am about 25 hours into this save and all my items are in the system.

**Comment by raoulvdberge** [comment] 2018-10-02 20:59
On which RS version are you.

**Comment by Deragonis** [comment] 2018-10-08 23:48
was playing stoneblock when this happened, disabled the tweaks mods but i mighta disabled the wrong one and messed up the crafting recipes, about to try a fix i think might work

**Comment by Deragonis** [comment] 2018-10-09 00:13
ok, so i disabled all the tweaks mods, that fixed it, but messed up the crafting recipes, so i  reinabled them and i saw on another forum that someone else was able to still see the items on a server so i took everything out of my inventory and deleted my player data (only player data) to see if that would work, i dont know if it was the temp disabling of the tweaks mods or the player data but one of them fixed the problem

**Comment by DMCK96** [comment] 2018-10-19 20:48
Still occurring RS version 1.6.5 and Forge 14.23.4.2760

**Comment by urikkiru** [comment] 2019-02-14 04:40
This just happened to me on RS 1.6.12 / Forge 14.23.5.2781. It occurred when I moved a crafting grid. It should be noted this was my second crafting grid (along with a single pattern grid) on the network, if that's relevant. 

Restarting the pack fixed the issue.

**Comment by CC3301** [comment] 2019-11-30 21:13
Same happended here. Drive got blown up by a creeper, the disks themselves are still there. One of them (4k) is full and i can't put any items in it when it is in the drive i replaced. I have one 16k drive about half-full where i CAN store new items and retrieve them, however the "old" ones are gone. The drive reports the disks being filled tho.


RS version: 1.2.26
FML version: 8.0.99.99
Forge: 12.18.3.25.11
MC: 1.10.2

latest version of space astronomy 2 pack.

**Comment by PetNoire** [comment] 2020-06-09 02:45
i cant see anything in any RS drive. i didnt break anything. i used it fine, walked away, came back and nothing showed.  another setup on the server wont show anymore either. i dont know if its related to this issue or a different cause entirely

**Comment by Tahakk** [comment] 2020-06-09 07:22
make a new issue, don't resurrect the old one
