### ISSUE TITLE
[1.11]Bug with fluid grid

### ISSUE THREAD

**Issue by Myknakryu** [raoulvdberge/refinedstorage#751] opened 2016-12-13 17:08 UTC
#### Issue description:
Placing bucket in fluid grid GUI duplicates fluid bucket. Shift clicking bucket does not duplicate bucket.
#### What happens:
Placing bucket in fluid grid GUI duplicates fluid bucket.
#### What you expected to happen:
Getting empty bucket.
#### Steps to reproduce:
1.Get working RS network with liquid storage and fluid grid
2.Get some fluid in bucket
3.Place the bucket in the fluid grid GUI and place bucket back in inventory
#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.11
- Forge: 2188 and 2189
- Refined Storage: 1.3.4

Does this issue occur on a server?
Yes and no

Video for forge version 2188
https://youtu.be/tijblN2ZLXg
Video for forge version 2189
https://youtu.be/tijblN2ZLXg

**Comment by raoulvdberge** [comment] 2016-12-13 20:36
Duplicate of #742

**Closed by raoulvdberge** 2016-12-13 20:36 UTC
Labels: bug, duplicate
