### ISSUE TITLE
Crafting Grid config options freeze

### ISSUE THREAD

**Issue by bgarrison25** [raoulvdberge/refinedstorage#160] opened 2016-07-06 02:43 UTC
I am playing the latest FTB unstable which has version 0.8 of refined Storage. I have a refined storage system and am having troubles with the crafting grid. Randomly the config options on the left side (redstone / sort by / etc) freeze up and won't let me click anything. The grid still works but the options are reset to default. 

I apologize that there isn't more information. Ask me for anything and i will provide what i can.

**Comment by raoulvdberge** [comment] 2016-07-06 09:37
Duplicate of #150

**Closed by raoulvdberge** 2016-07-06 09:37 UTC
