### ISSUE TITLE
(suggestion) multipart cables,terminals and such

### ISSUE THREAD

**Issue by NarigudoBR** [raoulvdberge/refinedstorage#244] opened 2016-08-04 21:39 UTC
yeah,you know how good is to hide your system and having all things inside of walls.

**Comment by oitsjustjose** [comment] 2016-08-04 22:17
Yeah, this would be excellent!! I've heard MCMP is reasonable to implement, but haven't ever done so myself.

**Comment by raoulvdberge** [comment] 2016-08-04 22:45
duplicate of #113

**Closed by raoulvdberge** 2016-08-04 22:45 UTC
