### ISSUE TITLE
Crash whenever I try to access crafting grid

### ISSUE THREAD

**Issue by PLWRush** [raoulvdberge/refinedstorage#759] opened 2016-12-16 03:06 UTC
#### Issue description:
I'm getting a crash everytime I try to access my storage network
#### What happens:
Upon opening my storage network via Crafting grid/pattern grid
#### What you expected to happen:
Access my storage network
#### Steps to reproduce:
1. Open the GUI for storage in any relevent grid
2. The crash stops happening when I remove my second 64k disk from my drive, so there is something stored inside that is causing the crash I believe, I don't think I have any way of knowing what item/items is causing it to crash.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.2.1

Does this issue occur on a server? [yes/no]
no
#### If a (crash)log is relevant for this issue, link it here:
[20:02:19] [Netty Server IO #5/ERROR] [FML]: NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
	at net.minecraft.network.play.server.SPacketCustomPayload.<init>(SPacketCustomPayload.java:27) ~[gl.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toS3FPackets(FMLProxyPacket.java:156) ~[FMLProxyPacket.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:531) ~[NetworkDispatcher.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) ~[DefaultChannelPipeline.class:4.0.23.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) ~[AbstractChannel.class:4.0.23.Final]
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:247) [eo$4.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [SingleThreadEventExecutor.class:4.0.23.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [NioEventLoop.class:4.0.23.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:4.0.23.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[20:02:19] [Server thread/INFO]: PLWRush left the game
[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment] 2016-12-16 07:05
Duplicate of #673

**Closed by raoulvdberge** 2016-12-16 07:05 UTC
