### ISSUE TITLE
Portable Grid and Pattern Grid

### ISSUE THREAD

**Issue by Notlucky101** [raoulvdberge/refinedstorage#2203] opened 2019-03-26 14:26 UTC
#### Issue description:
The blank patterns or the disk on not there till I click on the space they are suppose to be
#### What happens:
Either logging on the server or coming from anther dimension they disappear 
#### Steps to reproduce:
1.log on the server or go to another dimension
2. go to either grid and click on either of them
3.the patterns or disk is gone until you click on the spot
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:
- Forge:forge 1.23.5.2815
- Refined Storage:1.6.1.4

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
![image](https://user-images.githubusercontent.com/42447191/55004942-62a34000-4f98-11e9-86be-6982421d4b15.png)
![image](https://user-images.githubusercontent.com/42447191/55004979-78186a00-4f98-11e9-8c8b-e6e3b9c07638.png)

**Comment by kreezxil** [comment] 2019-05-08 15:40
I've got a player experiencing an issue similar to this. Their grid is entirely empty, and yet when I look at it, it's full.

https://cdn.discordapp.com/attachments/550346536408580111/575499263136759819/unknown.png

**Comment by wolforcept** [comment] 2019-05-08 15:53
I am, as stated above, experiencing this issue.
I played for a couple of days and everything was fine. I went in and out of mystcraft dimensions, and the hunting dimension, logged and relogged many times and everything was fine. 
The problem started when I was connecting an "external storage" cable to a drawer with upgrades.
I don't know exactly when but i was playing with Tech Reborn Scrapboxes and Recycler.
I crafted a ton of scrapboxes in the RS grid and opened them by hand and tossed in the results.

My RS setup consisted only of: 1 controller being fed by Ender IO conduits, 1 crafting grid, 1 disk drive with 8 disks (the smallest, i think its 1k?)

The modpack was "God Block", doesnt have a ton of mods, its on Twitch.

I dont know if any of that helps but i wanted to present exactly what im doing.

GPU: GeForce GTX 1060 6GB
CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Memory: 16 GB RAM (15.94 GB RAM usable)
Current resolution: 1680 x 1050, 60Hz
Operating system: Windows 7

**Comment by kreezxil** [comment] 2019-05-08 16:27
We've discovered that when the player's dat file is deleted. and they relog they can see everything in the grid again.

**Comment by raoulvdberge** [comment] 2019-07-21 14:31
This is a duplicate of #2200 and was finally fixed today.

**Closed by raoulvdberge** 2019-07-21 14:31 UTC
Labels: Bug

**Comment by raoulvdberge** [comment] 2019-07-21 14:36
@kreezxil  You are experiencing a different issue, described in #2279
