### ISSUE TITLE
Filter and Pattern disappearing after loading screen/dimension change

### ISSUE THREAD

**Issue by Kurczak57** [raoulvdberge/refinedstorage#2276] opened 2019-07-07 09:59 UTC
#### Issue description:

Filter (in every grid) and patterns (in Pattern Grid) disappearing after changing dimension (and after loading screen(?) )

#### What happens:

Every time I tried to change dimension or jump to another location via Draconic/RFTools/EnderIO/Vanilla portal my empty patterns in Pattern Grid and Filters (in any grid) disappearing. Tests confirmed that these items are in fact in slots but needs to be picked up and installed again to work correctly. Video below.

#### What you expected to happen:

Pattern and filter function correctly after loading screen.

#### Steps to reproduce:

1. Place Filter in filter slot.
2. Change dimension.
3. Come back to Crafting Grid.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.24.5.2838
- Refined Storage: 1.6.14

Does this issue occur on a server? 

Yes

[pastebin/gist/etc link here]

Video:  https://imgur.com/a/2CFP8Qc

**Comment by Darkere** [comment] 2019-07-07 10:04
Duplicate of #2200

**Comment by Kurczak57** [comment] 2019-07-07 10:15
Yes you are right it's excacly same problem. I am sorry that I did not notice this Issue before.

**Closed** 2019-07-20 10:37 UTC
