### ISSUE TITLE
OC integration - getMissingItems ignores missing fluids (and not getMissingFluids())

### ISSUE THREAD

**Issue by Garagoth** [raoulvdberge/refinedstorage#2072] opened 2018-11-01 20:42 UTC
https://github.com/raoulvdberge/refinedstorage/blob/68e857cc9c32f996c599db4223e38267e45f66b8/src/main/java/com/raoulvdberge/refinedstorage/integration/oc/EnvironmentNetwork.java#L117

getMissingItems returns just missing items from crafting task; it ignores missing fluids.
But there is not getMissingFluids() - please ass information about missing fluids as well.

**Comment by raoulvdberge** [comment] 2018-11-01 20:43
This is a duplicate of #1907

**Closed by raoulvdberge** 2018-11-01 20:43 UTC

**Comment by Garagoth** [comment] 2018-11-01 20:47
Sorry, that one had no description and title was not exactly what I had in mind.
I just reported that there is no way to check if request will fail or not; fluid autocrafting works as long as fluids are there :-)

**Comment by raoulvdberge** [comment] 2018-11-01 20:51
No problem, I understand.
