### ISSUE TITLE
Autocrafting breaks when recipe WITH oredict enabled has ingredients in storage drawers via external storage

### ISSUE THREAD

**Issue by gameplaysyou** [raoulvdberge/refinedstorage#921] opened 2017-01-26 03:32 UTC
#### Issue description:
The outcome of a request to autocraft an item/recipe that has its ingredients solely in storage drawers connected via external storage is dependent upon whether or not oredict is on. If on, autocrafting fails. If off, autocrafting succeeds.

I'm going to give 1 example of the issue to best explain the bug. 

I have storage drawers with the ingredients for binder composite (Ender IO): clay, gravel, and sand. These drawers are connected via external storage to the RS network. No (or very little) quantities of these ingredients are stored on the drives.

I created a pattern for binder composite with oredict enabled. I request 1 (or 64) binder composite. The crafting monitor says the item is crafting. (If I try to craft conduit binder or a conduit, the monitor says that corresponding machine is in use). Nothing happens.

I then changed the recipe so oredict is disabled and retry. Worked like a charm.

I then tried to confirm this was related by re-enabling oredict, then removing a stack each of the ingredients via grid, returning these stacks via grid (i.e. I am moving them from storage drawers to the RS drives), and requesting more binder composites than possible based off the ingredients' quantities. e.g. 5 gravel, 2 clay, 2 sand = 8 binder composite; therefore, I added those ingredients' quantities, but requested, 16 binder composite. It is important to note that the grid sees my storage drawers just fine.

Troubleshooting I tried before disabling oredict: break and replace controller block, swap controller with new controller, swap with creative controller, vice versa, reposition controller in various ways: so it touches crafters (laid out in 5x5x1 against a wall), touches disk drives and crafters, touches just disk drives with a cable between controller and crafters, " " but cable between drive & crafters, etc. etc.

#### Steps to reproduce:
1.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage: 1.2.18, (1.2.14)

Does this issue occur on a server? [yes/no]
yes, I have confirmed this issue on 1.2.18. Server is running DW20 1.4.1 MC1.10.2. I had similar issues in 1.2.16 with the solderer (and importer - but that's a separate issue), which prompted me to update to 1.2.18. I experienced this issue in 1.2.18, couldn't fix it, and decided to return to 1.2.14 (was stable in Skyfact3). The issue remained in 1.2.14, but I did not confirm the issue as I have in 1.2.18. 
I returned to 1.2.18 via restoring a world backup I made before downgrading. For each mod version change, I deleted the config (no idea if they differ in minor mod updates). 

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment] 2017-01-26 10:56
Duplicate of #885, fixed in c5fb66ca56bfcf33941b4ef9f8e4194929a60dde

**Closed by way2muchnoise** 2017-01-26 10:56 UTC
