### ISSUE TITLE
Autocrafted Fluix Seeds stored as Certus Quartz Seeds

### ISSUE THREAD

**Issue by Aberzhulan** [raoulvdberge/refinedstorage#2136] opened 2018-12-12 00:18 UTC
#### Issue description:
Fluix Seeds that are crafted manually in the Crafting Grid are stored in the system as Certus Quartz Seeds, making it impossible to autocraft Pure Fluix Crystals. 

#### What happens:
Added recipe for Pure Fluix crystals and upon crafting attempt, see I have 1 Fluix Seed. I had just manually crafted two inventories full so I know I have more than one. I also had 6.4k Certus Quartz Seeds, which I never crafted. Clicking on that (the Certus Quartz Seeds) gives me a Fluix Seed.

Interesting note, Fluix Seeds (when transmuted from Project E's Transmutation Tablet) are stored as Fluix Seeds.

Fluix Seeds stored as Certus Quartz Seeds (note the IDs):
https://imgur.com/a/v4Iu3zp

Certus Quartz Seeds stored as Certus Quartz Seeds:
https://imgur.com/a/ODAcfNC

Fluix Seeds stored as Fluix Seeds:
https://imgur.com/a/IziVlMo

#### What you expected to happen:
Fluix Seeds to be stored as Fluix Seeds.

#### Steps to reproduce:
1. Put 1 sand and 1 Fluix Dust into crafting grid
2. Craft any number of Fluix Seeds
3. Drop them into the storage window above

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Refined Storage: 1.6.5

Does this issue occur on a server? Yes

#### If a (crash)log is relevant for this issue, link it here:
N/A

**Comment by Darkere** [comment] 2018-12-12 18:37
This was either fixed by one of the updates ( You are 7! Versions behind.) or a pack specific Issue. I cannot reproduce it in my test instance.

Forge: 2772
AE:rv6-stable-4
RS: 1.6.12

**Comment by raoulvdberge** [comment] 2018-12-12 18:40
Can you retry on the latest version? @Aberzhulan

**Comment by Aberzhulan** [comment] 2018-12-14 16:40
Weird. I had just updated it. At least, I downloaded the update. Will try again, thanks.

**Comment by raoulvdberge** [comment] 2018-12-14 17:12
Are you sure that you're on a build from curse?

**Comment by Aberzhulan** [comment] 2018-12-14 20:49
Yes. That happened the other day and I re-downloaded a fresh version earlier and same thing.

**Comment by raoulvdberge** [comment] 2018-12-15 19:00
That is weird. The latest version has been out for almost a month now and I haven't gotten that bug report yet. It would be weird if this build was up for a month without anyone complaining that it doesn't work on servers...

Can anyone else confirm this on a server?

**Comment by tenten8401** [comment] 2018-12-16 21:18
1.6.12 from curseforge works fine over here on our server. The TPS gets *really* bad after a while because of it according to VisualVM, though I think that's another issue...

**Closed** 2019-01-28 22:09 UTC
