### ISSUE TITLE
World Crash at autocrafting wither

### ISSUE THREAD

**Issue by mrtomwolf** [raoulvdberge/refinedstorage#967] opened 2017-02-07 06:17 UTC
#### Issue description:
World crash when autocrafter trying to place a wither skull
#### What happens:
Game crashes
#### What you expected to happen:
Wither to be created ;)
#### Steps to reproduce:
1. set up a wither creator
2. link with network card
3. try to create wither ;)
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2221
- Refined Storage: 1.2.20

Does this issue occur on a server? [yes/no]
no
#### If a (crash)log is relevant for this issue, link it here:

http://pastebin.com/nX75Xg45

[pastebin/gist/etc link here]

I went back to 12.2.18 and could start the world again and the wither was created with no problem.

**Comment by way2muchnoise** [comment] 2017-02-07 10:31
Duplicate of #958

**Closed by way2muchnoise** 2017-02-07 10:31 UTC
