### ISSUE TITLE
[1.11.2] Network Controller goes dead after leaving the area

### ISSUE THREAD

**Issue by kwpugh** [raoulvdberge/refinedstorage#1255] opened 2017-05-27 15:52 UTC
#### Issue description:
I have a simple RS setup that connects a controller, grid, and crafting grid to external storage.
 
#### What happens:
When a player leaves the area and comes back, the controller is dead.   It needs to be broken and replaced, then everything works fine

#### What you expected to happen:
Not go dead

#### Steps to reproduce:
1. Setup controller and crafting grid
2. leave the area (via /tp or other method
3. return to the area
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 2304
- Refined Storage: refinedstorage-1.4.10.jar

Does this issue occur on a server? [yes/no]
Yes

#### If a (crash)log is relevant for this issue, link it here:
No crash

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment] 2017-05-28 13:10
Define dead. Does the controller still blink, are the devices still connected, ...?

**Comment by kwpugh** [comment] 2017-05-28 13:57
The controller, grid, and crafting grid go dark and nothing works.

**Comment by kwpugh** [comment] 2017-05-28 14:02
With a chunk loader, it does not go dark

**Comment by kwpugh** [comment] 2017-05-28 14:45
Logging out from the server in front of the RS system and logging back in results in the system going dark

**Comment by raoulvdberge** [comment] 2017-05-28 16:50
If you open the controller GUI what does it look like?

**Comment by kwpugh** [comment] 2017-05-28 17:48
It shows full power and everything connected, still dark

**Comment by raoulvdberge** [comment] 2017-05-28 20:55
Of course I cannot reproduce this bug!
Before...
![x](https://raoulvdberge.com/WeSJZU)
Go off the server..
![y](https://raoulvdberge.com/G8gGtM)
And then, rejoin! Result:
![z](https://raoulvdberge.com/MRf0X7)

**Comment by raoulvdberge** [comment] 2017-05-28 20:59
Any relevant logs like exceptions when this happens?

**Comment by Boyownik** [comment] 2017-06-01 09:13
Same problem, but when i relog, controller is blue, full powered, i can pull out items but autocrafting is not working. I have to replace controller to make it work again.

**Comment by raoulvdberge** [comment] 2017-06-01 14:56
Define "not working", please..............

**Comment by kwpugh** [comment] 2017-06-01 15:14
Raoul,

Are you testing with the creative controller or the regular?   My problem seems to occur with the regular one that needs power.   

I have tried several different power sources and the controller is dark when I leave and return.  Looking inside the controller GUI shows plenty of power stored up.

I am using a custom modpack I created: https://minecraft.curseforge.com/projects/pughland-plethora

Also, when I leave a chunkloader on in the area, the controller is still dark when I return.

There are no relevant messages in the server log during the time of leaving/returning to the area.

**Comment by Boyownik** [comment] 2017-06-01 17:07
I can see in grid that i can craft Cable for example, but when I send order to make some of them, literally nothing happens. Crafting monitor is empty, no scheduled tasks.

**Comment by Ash70** [comment] 2017-06-05 22:37
Just a quick note for now; I am having the same problem. Whenever I leave the area (e.g. go to the nether and return) the controller is either not powered (no lights) and nothing works, OR the controller still works (lighted) but the grid (inventory) shows as empty (grayed out). breaking the controller and replacing it fixes it. I am currently not home, but will post more info, inc. a log/mod-list if relevant either tomorrow or Wednesday.

**Comment by Ash70** [comment] 2017-06-06 13:52
hmm, seems this is a forge issue. Updating to 2314 resolves the issue; I was on 2290 before.

**Comment by raoulvdberge** [comment] 2017-06-06 14:38
Good to hear!

**Comment by Ash70** [comment] 2017-06-07 12:08
Nope, I spoke too soon. Today I went back and forth between my two bases and sometimes it does happen (controller not powered, replacing it solves it), and sometimes it doesn't. It seems to be related to the amount of time I am gone?
There are no entries in the log related to refined storage. [Here is a list of mods](https://pastebin.com/tte0dzyR).

**Comment by kwpugh** [comment] 2017-06-07 12:31
II updated to Forge 2314, and nothing changed.   Same behavior as Ash70 described.

**Comment by rHermes** [comment] 2017-06-15 00:19
I'm also having the same problem, it seems that just chunkloading the machine isen't enough. This also happens with wireless receivers, when I'm not close to them.

**Comment by rHermes** [comment] 2017-06-18 17:45
Just an update on my problem, I found that the problem disappereared when I used persistent bits instead of FTBUtils to do my chunk loading. The two things might not be releated, but it atleast fixed the issue for me.

**Comment by Andronomos** [comment] 2017-06-22 12:19
I have the same problem using Refined Storage 1.4.17

Whenever I unload the chunk my RS system is in either by walking far enough away, teleporting or switching dimensions you can no longer access items in it when you return. It acts as if their is no power even though the controller is still lit up and everything is powered.

In order to get it working again I have to break the controller and replace it.

My setup: http://i.imgur.com/HSHeXKX.png

**Comment by raoulvdberge** [comment] 2017-06-22 14:08
Any logs when this happens?

**Comment by Andronomos** [comment] 2017-06-22 14:22
@raoulvdberge Not that I'm aware of since the game doesn't crash.

Though I did create a new world and have no problems with RS when unloading chunks. So I'm hoping it was just that world. Guess I'll have to wait a few days and see if the problem reoccurs.

**Comment by raoulvdberge** [comment] 2017-06-22 14:48
You can still have logs, even if the game doesn't crash.

**Comment by Andronomos** [comment] 2017-06-22 14:55
@raoulvdberge Correct but I wouldn't know what to send you. Not only was my log overwritten when I created a new world but the logs are full of generic information and searching for anything related to Refined Storage just showed typical loading messages.

If you can point me to a specific file or a general area to look for any relevant information I'd be happy to send you more data but at the moment it looks like just a fluke with that world save so I'm not sure there is any useful data to send you.

**Comment by raoulvdberge** [comment] 2017-06-22 15:01
I don't think either.

**Comment by skittishtrigger** [comment] 2017-06-25 16:34
Unfortunately I wanted to add some logs to maybe assist but as so far I have one user with this issue.  Right now I have about 4 users with ae2 Me systems and about 4 with RS systems.  This is on a FTB Beyond Pack(v1.10b) on a server.  I did some testing on mine and was able to spread out the grids and such pretty far with no issues. The one player having issues I had them use manipulator and put all items on new disks, break all old rs items and trash them(as well as cables, and had them completely redo with all new items.   The issue is still present.  No other storage systems are  are affected(ender storage, me, etc) and I can not reproduce.   If there is any logs I can provide you other than the ones I already have let me know. I'll do what I can to help.
I could not find anything relevant  but maybe it will help you:
[Latest-Client-log](http://repo.storagedragon.com/mods/logs/jade/latest-client-jade.log)

**Comment by DingoX3** [comment] 2017-07-03 06:49
I'm using version 1.5.6 in MC 1.12. The issue im having is if you leave the area where the refined storage  (controller,grid,and disc drives) is and the chunk unloads, when you return it will be lit up(blue) but you can not put in anything in it and there are no items showing. If you then break the controller and replace it everything is fine. So chunk unloading = controller losing connection to network. To recreate the issue I would suggest going to another dim like the nether and coming back. 

Also there is an issue when placing cables and the rendering of them connecting to other cables. If you relog sometimes it will fix the issue. 

mc: 1.12
refined storage: 1.5.6
modpack: All The Mods 3
forge: 2387

**Comment by Andronomos** [comment] 2017-07-03 09:20
@DingoX3 

That was the exact issue I had on 1.10.2 but it was only on one world. I couldn't replicate it after and had no relevant data in the logs.

**Comment by DingoX3** [comment] 2017-07-03 18:33
We actually tested it with one person in console looking at the fml logs and console logs and me on the server going back and forth to the nether to cause it to disconnect or stop working. There were no relevant logs that showed up during this test.

**Comment by Morpheus1101** [comment] 2017-07-06 09:14
@raoulvdberge I have a very similar possibly exact issue, however everything remains lit up an connected, but when i open crafting grid no items for me appear until such time as i remove a storage drive an replace it. My area is supposed to be chunkloaded, but occurs reguardles

**Comment by raoulvdberge** [comment] 2017-07-06 13:12
The issue with the items not showing up has been fixed.

However, I still can't reproduce the "controller going dark" issue...

**Comment by Morpheus1101** [comment] 2017-07-06 13:18
Ive not been able to trigger this issue either no matter which way I try an do it

**Comment by raoulvdberge** [comment] 2017-07-06 13:46
Me neither, I guess some people confused this bug for the items not showing up issue.

Closing

**Closed by raoulvdberge** 2017-07-06 13:46 UTC
Labels: bug, can't reproduce
