### ISSUE TITLE
Server Tick Loop Crash on Server Start

### ISSUE THREAD

**Issue by kosakriszi** [raoulvdberge/refinedstorage#1720] opened 2018-03-24 11:39 UTC
#### Issue description:
The thing I've been able to trace this crash back to in my world is having the system export Fluxed Phyto Gro from Thermal Expansion with a crafting card.

#### What happens:
The server crashes, and then proceeds to crash on launch.

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.12.2
- Forge: 14.23.2.2632
- Refined Storage: 1.5.32

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:
Gotchu fam
https://pastebin.com/L06U83FD

**Comment by raoulvdberge** [comment] 2018-04-04 17:31
Duplicate of some other issue i couldn't bother searching

**Closed by raoulvdberge** 2018-04-04 17:31 UTC
