### ISSUE TITLE
[1.11.2] [1.4.2] java.lang.NullPointerException: Rendering screen

### ISSUE THREAD

**Issue by savosdarkran** [raoulvdberge/refinedstorage#1183] opened 2017-04-23 15:18 UTC
#### Issue description:
When I scroll through the grid it shows a bunch of items with 0 quantity and no textures and then crashes the client to desktop.  The grid is filtered by mod.
#### What happens:
Crashes client to desktop when scrolling in a filtered grid.

#### What you expected to happen:
To not 

#### Steps to reproduce:
1. Set grid filter for a specific mod
2. put filter into grid upgrade slot
3. scroll with mouse wheel
4. crashes to desktop
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.11.2
- Forge: 13.20.0.2282
- Refined Storage: 1.4.2

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:
[crash-2017-04-23_11.10.37-client.txt](https://github.com/raoulvdberge/refinedstorage/files/949793/crash-2017-04-23_11.10.37-client.txt)
[crash-2017-04-23_07.27.34-client.txt](https://github.com/raoulvdberge/refinedstorage/files/949792/crash-2017-04-23_07.27.34-client.txt)
[crash-2017-04-23_07.21.35-client.txt](https://github.com/raoulvdberge/refinedstorage/files/949791/crash-2017-04-23_07.21.35-client.txt)

**Comment by savosdarkran** [comment] 2017-04-23 15:20
Just noticed a new version of 1.4.3 that addresses a "grid crash".  I will try that and report back.

**Comment by savosdarkran** [comment] 2017-04-24 00:08
Upgraded and it's still crashing.
[crash-2017-04-23_20.07.30-client.txt](https://github.com/raoulvdberge/refinedstorage/files/950141/crash-2017-04-23_20.07.30-client.txt)

**Comment by raoulvdberge** [comment] 2017-04-25 18:40
Duplicate of #1183

**Closed by raoulvdberge** 2017-04-25 18:40 UTC
Labels: bug

**Comment by savosdarkran** [comment] 2017-04-25 19:17
Thank you kind sir!
