### ISSUE TITLE
Crash when autocrafting, prevents world from loading afterwards

### ISSUE THREAD

**Issue by Xalxa** [raoulvdberge/refinedstorage#399] opened 2016-09-29 23:03 UTC
#### Issue description:
Client crash when trying to autocraft processor
#### What happens:
CTD with crash report and prevents the world from being loaded back into
#### What you expected to happen:
Autocrafting to begin
#### Steps to reproduce:
1. Have network setup to autocraft processors and their requirements in the Solderer
2.  Put Construction/Destruction Core pattern in a Crafter on the network line somewhere
3. Attempt to autocraft
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.1.2094
- Refined Storage: 1.1.1

Does this issue occur on a server? [yes/no]

No
#### If a (crash)log is relevant for this issue, link it here:

http://pastebin.com/wgGW7Lmb

**Comment by raoulvdberge** [comment] 2016-09-30 06:31
When you reload the world and it crashes, which crash do you get?

**Comment by Xalxa** [comment] 2016-09-30 12:32
http://pastebin.com/pgU6pEtq That's the crash log I got after trying to reload the world. Reading through it, it's something about JEI. Which is odd. I'm going to test that a bit on my own

**Comment by Xalxa** [comment] 2016-09-30 12:37
That's strange. Managed to start the world up just fine this time. I tried several times last night and it wouldn't, so I guess something about restarting my computer fixed it.

**Comment by Xalxa** [comment] 2016-09-30 12:47
And I should mention, I was unable to recreate the crash in my world. However autocrafting (basic recipes, machine automation still works) isn't doing anything. I even tried making a new pattern with logs to planks, and it gets stuck at 20% creating the planks, but won't do anything.

**Comment by raoulvdberge** [comment] 2016-09-30 17:23
Duplicate of #395

**Closed by raoulvdberge** 2016-09-30 17:23 UTC
