### ISSUE TITLE
Valhelsia 2 Server Crashes Due to Crafting Monitor Interactions

### ISSUE THREAD

**Issue by backlands** [raoulvdberge/refinedstorage#2533] opened 2020-05-24 22:50 UTC
#### Issue description:
MC 1.15.2 server crashes when access the Crafting Monitor and a task completes or a complex task is cancelled. This does not occur every time, however it is consistent enough that our group of players knows not to access the monitor unless absolutely necessary.

This may have been reported already, however I did not see a mention of a specific commit fixing the issue so wanted to post a new report in case it has come back. Not sure if the previously noted fix [here](https://github.com/raoulvdberge/refinedstorage/issues/2508) has been merged into the current release for 1.15.2.

#### What happens:
When cancel is clicked on a complex auto-crafting task the server crashes.

#### What you expected to happen:
The server should not crash when cancelling tasks or a task completes and a player is viewing the crafting monitor.

#### Steps to reproduce:
1. Queue several tasks in the RS crafting system.
2. View the tasks in the RS Crafting Monitor.
3. Allow a complex task to complete, or manually cancel a task using the Crafting Monitor.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.2.0 (was also occurring on earlier versions)
- Refined Storage: 1.8.3

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:
https://gist.github.com/backlands/a4fd1a0a24cfb3e6452dadfc28225cbd

**Comment by Darkere** [comment] 2020-05-25 10:00
Duplicate of #2508

Fixed in dev

**Closed** 2020-05-25 10:04 UTC
