### ISSUE TITLE
Singleplayer FTB Confusion

### ISSUE THREAD

**Issue by Angelicgrim** [raoulvdberge/refinedstorage#2401] opened 2020-01-13 19:39 UTC
#### Issue description:
The Crafting Grid, Wireless Transmitter and Controller blocks in FTB revelations work just fine but their textures have disappeared and look like ghost blocks.
#### What happens:
you can see through it like the block doesnt exist but nothing behind it exists either.
#### What you expected to happen:
not this, them looking normal
#### Steps to reproduce:
1.i log into my game
2. it just randomly happened once and wont stop
3. i was changing the quality options in optifine before it, i just turned off random textures and it happened but turning it back on did not fix it.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 8.0.99.99
- Refined Storage: 1.6.15

Does this issue occur on a server? [yes/no]
no
#### If a (crash)log is relevant for this issue, link it here:

![image](https://user-images.githubusercontent.com/13468922/72286064-fb7b7880-3609-11ea-8220-b6c80091dadc.png)

dunno if i messed something up somehow or something just corrupted, even restarting my game hasnt fixed it

**Comment by Darkere** [comment] 2020-01-13 19:44
Duplicate of #2205

This happens when you reload the textures. So on some graphics options and when applying/removing resource packs. A restart will fix it. (unless you change things in the main menu again)...

**Comment by Angelicgrim** [comment] 2020-01-13 20:04
appreciated, ill completely reboot it then and see if that fixes it

**Closed** 2020-01-13 20:23 UTC
