### ISSUE TITLE
Crafting Grid don't accept GameStages recipes

### ISSUE THREAD

**Issue by GuerreroCraft61** [raoulvdberge/refinedstorage#2482] opened 2020-04-16 14:48 UTC
#### Steps to reproduce:
1. Add locked stage recipe (but having the stage)

#### Version (make sure you are on the latest version before reporting): 

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Refined Storage: 1.6.15

Does this issue occur on a server? yes

Example:
![Captura1](https://user-images.githubusercontent.com/30746531/79470724-0a573a00-8002-11ea-9c11-162d5d977b32.PNG)
![Captura2](https://user-images.githubusercontent.com/30746531/79470726-0aefd080-8002-11ea-839d-9de39e5db15d.PNG)
![Captura3](https://user-images.githubusercontent.com/30746531/79470727-0b886700-8002-11ea-8655-41cfddf8d38c.png)

**Comment by Darkere** [comment] 2020-04-16 14:56
Duplicate of #2229

**Closed** 2020-04-16 15:41 UTC
