### ISSUE TITLE
cant make CHEST PATTERN!

### ISSUE THREAD

**Issue by BlackHoleTON618** [raoulvdberge/refinedstorage#2178] opened 2019-02-13 14:46 UTC
#### Issue description:
minecraft shut downs 
#### What happens:
when i want to chest pattern nad shift click to chest recipe while on pattern grid it says payload may not be larger than 32K bytes
#### What you expected to happen:
i wanted to make chest pattern
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge:14.23.5.2784
- Refined Storage:1.6.9

Does this issue occur on a server? [yes/no]
no
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment] 2019-02-13 21:15
Duplicate of #1790

Make the pattern for the chest manually (without JEI).

**Closed** 2019-02-13 22:52 UTC

**Comment by BlackHoleTON618** [comment] 2019-02-14 21:09
dont close that topic i cant do manually too

**Comment by Darkere** [comment] 2019-02-14 22:02
What happens if you do it manually?

**Comment by BlackHoleTON618** [comment] 2019-02-14 22:46
it errors and says payload may not be more than 32k and it quit world

**Comment by Darkere** [comment] 2019-02-14 22:56
What specifically are you doing? That error only appears when you use JEI. 

When I say manually I mean taking wood and putting the recipe it into the patter grid by hand.

**Comment by BlackHoleTON618** [comment] 2019-02-14 22:57
i put 8 planks by my hand not jei and in pattern grid (not processing ) when i put 8 th plank minecraft quit world same thing on crafting table too

**Comment by Darkere** [comment] 2019-02-14 23:00
Do you mean in a vanilla crafting table?

**Comment by BlackHoleTON618** [comment] 2019-02-14 23:05
no it occurs only crafting grid and pattern grid

**Comment by BlackHoleTON618** [comment] 2019-02-14 23:05
yes i cant craft vanilla crafting table too

**Comment by Darkere** [comment] 2019-02-14 23:25
Alright, then we might have a related or even entirely different issue. 
Please Upload a log of it happening (or a crashlog if the entire game crashes). 

Also, I'm curious about what kind of modpack you are playing that would cause such an issue?

Lastly, it would be awesome if you could test if the issue also occurs with the newest version of Refined Storage.

**Comment by BlackHoleTON618** [comment] 2019-02-16 08:47
[2019-02-16-1.log](https://github.com/raoulvdberge/refinedstorage/files/2871750/2019-02-16-1.log)
