### ISSUE TITLE
Lag when opening grid

### ISSUE THREAD

**Issue by jephrei** [raoulvdberge/refinedstorage#1158] opened 2017-04-12 05:02 UTC
#### Issue description:
When a grid is opened, the mouse can move, but the system can't be interacted with for over 10 seconds.

I solved this by removing all vanilla armor, weapons, and tools from the system.

#### Version:
- Minecraft: 1.10.2
- Forge: 8.0.99.99
- Refined Storage: 1.2.22 
- Skyfactory 3: 3.0.8

#### Does this issue occur on a server? 
Only tried on single player Skyfactory 3 (maybe creates a local server? not sure).

#### Issue details
The items had accumulated from mob farms but I figured they were OK since i had space. It was only a few thousand items with different durability and enchantments. Once i removed the bulk of them, the lag disappeared.  No items from the Storage Drawers or Colossal Chests mods were connected to the network. Hope this helps! Let me know if you need any other info to debug.

**Comment by raoulvdberge** [comment] 2017-04-15 22:22
Duplicate of #1041

**Closed by raoulvdberge** 2017-04-15 22:22 UTC
