### ISSUE TITLE
FPS lag when RS/RF power is inadequate

### ISSUE THREAD

**Issue by Howsyomamanem** [raoulvdberge/refinedstorage#912] opened 2017-01-24 02:40 UTC
#### Issue description:
Running DW20 pack version 1.3.2.  I run my system off Immersive Engineering windmills augmented by ExtraUtils generators.  When the ExtraUtils generators run out of "fuel", my windmills don't supply enough power alone.  The RS system is powering up and down at a fast rate and causes huge FPS lag.  down to 7 FPS from normal 120 FPS.

#### What happens:
FPS lag.

#### What you expected to happen:
RS system should more gracefully handle inadequate power.  I imagine it's reanalyzing all it's components each time power is added after being depleted.  Could it not do that?  ;-)  I suppose it could be a chunk update issue w/ repainting the powered version of the blocks v/s the non-powered version so rapidly.  Not that I know how all that works really.

#### Steps to reproduce:
1.  Setup a system that requires X (RS/RF)/t.  
2.  Only provide X-n (RS/RF)/t.
3.  Watch the FPS die.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:  12.18.3.2185
- Refined Storage:  1.2.14

Does this issue occur on a server? [yes/no]  Yes, running on a server.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment] 2017-01-24 09:25
Duplicate of #566

**Closed by raoulvdberge** 2017-01-24 09:25 UTC
