### ISSUE TITLE
[1.5.31] RS crafting preview calculation [STDERR]

### ISSUE THREAD

**Issue by Blackcatz1911** [raoulvdberge/refinedstorage#1647] opened 2018-01-28 11:48 UTC
#### Issue description:

Autocrafting of the Resonant Upgrade Kit from Thermal Foundation not craftable

#### What happens:

After declaring the number of crafts and hitting the Start button the Start Button gets disabled and the exception is thrown in the server console.

#### What you expected to happen:
The Autocraft of the Kit.

#### Steps to reproduce:
1. Have n steps to craft Kit.
2. Something is missing from the network.
3. Try to craft the recipe.
4. Recipe is not craftable.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.1.2590
- Refined Storage: 1.5.31

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

```
[12:37:02] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at java.lang.Thread.run(Thread.java:748)
[12:40:07] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[12:40:07] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at com.raoulvdberge.refinedstorage.apiimpl.util.StackListItem.remove(StackListItem.java:44)
[12:40:07] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at com.raoulvdberge.refinedstorage.apiimpl.util.StackListItem.remove(StackListItem.java:17)
[12:40:07] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:260)
[12:40:07] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:252)
[12:40:07] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:252)
[12:40:07] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:109)
[12:40:07] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at com.raoulvdberge.refinedstorage.apiimpl.network.grid.handler.ItemGridHandler.lambda$onCraftingPreviewRequested$0(ItemGridHandler.java:186)
```

**Comment by raoulvdberge** [comment] 2018-01-28 14:43
Duplicate of #1629

**Closed by raoulvdberge** 2018-01-28 14:43 UTC
