### ISSUE TITLE
64k Drive Unuseable

### ISSUE THREAD

**Issue by mercsniper** [raoulvdberge/refinedstorage#754] opened 2016-12-15 05:03 UTC
#### Issue description:
Similar to https://forum.feed-the-beast.com/threads/items-vanish-off-of-a-64k-disk-drive-refined-storage.197600/
64k drive suddenly inaccessible from Disk Manipulator and Grid Systems.
#### What happens:
Empty Grid. Can place 16k disk in and access it, but it is bare. 
#### What you expected to happen:
64K Inventory accessible. 
#### Steps to reproduce:
1.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Refined Storage: 1.12.11

Does this issue occur on a server? [yes/no] Yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment] 2016-12-15 12:46
Duplicate of #754

**Closed by raoulvdberge** 2016-12-15 12:46 UTC
