### ISSUE TITLE
Autocrafting stop working for some items to restart server

### ISSUE THREAD

**Issue by Opicka879** [raoulvdberge/refinedstorage#1702] opened 2018-03-07 16:24 UTC
#### Issue description:

sry for my english

I cant craft items via grid request. Everything did work fine for a week. Now i have cca 30 crafters full of patterns (normal even processing even oredict etc.) and now i want to craft some item, so i choose how many item want to craft, hit start, but start just go to grey color and nothing happen. Just server write some exeption to putty window. After restart server, this item can be crafted, but another cant. After another restart another items cant be crafted etc.

#### What happens:
For example i want to craft Elite enriching factory from Mekanism and after push start button nothig happen.

#### What you expected to happen:
Table with requested/available items should show to accept.

#### Steps to reproduce:
1. Play for a week and build kind a big network.
2. Request some item and be angry becouse it doesnt work.
3. Restart server and be angry again and be afraid of needs to use AE2 insted of RS.
4. Look for solution on github mod forum.
5. Read multiple similar issues but dont find solution.
6. Create account on github
7. Try to write request for help.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.2.2619
- Refined Storage: 1.5.31

Does this issue occur on a server? [yes/no]

Yes

#### If a (crash)log is relevant for this issue, link it here:

Now i have server down and i dont have a log right now. If it will be important i will reproduce the situation and post it later.

**Comment by raoulvdberge** [comment] 2018-03-07 16:32
I do need a log

**Comment by Opicka879** [comment] 2018-03-07 16:40
Ok. My friend did try some things with RAID field on server and he did fail so i need to wait to server be online. It should be done after an hour i hope. I will upload log immediately after start server.

**Comment by raoulvdberge** [comment] 2018-03-07 16:41
Only upload the relevant parts, so the actual crash.

**Comment by Opicka879** [comment] 2018-03-07 17:36
Ok, so now it happend if i want to craft Laser Base from Industrial Foregoing.

Exception in thread "RS crafting preview calculation" [18:34:08] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[18:34:08] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at com.raoulvdberge.refinedstorage.apiimpl.util.StackListItem.remove(StackListItem.java:44)
[18:34:08] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at com.raoulvdberge.refinedstorage.apiimpl.util.StackListItem.remove(StackListItem.java:17)
[18:34:08] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:260)
[18:34:08] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:252)
[18:34:08] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:252)
[18:34:08] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:109)
[18:34:08] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at com.raoulvdberge.refinedstorage.apiimpl.network.grid.handler.ItemGridHandler.lambda$onCraftingPreviewRequested$0(ItemGridHandler.java:186)
[18:34:08] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at java.lang.Thread.run(Thread.java:748)

**Comment by raoulvdberge** [comment] 2018-03-08 19:30
Duplicate of #1595

**Closed by raoulvdberge** 2018-03-08 19:30 UTC
