### ISSUE TITLE
Extreme server lag with updating grid with new version of refinedstorage

### ISSUE THREAD

**Issue by L0laapk3** [raoulvdberge/refinedstorage#1075] opened 2017-03-19 14:22 UTC
Hello. I just upgraded refinedstorage on my server from version 1.2.16 to 1.2.24. However, in this version of refinedstorage, whenever I open any item grid: The grid opens instantly, but it does not show up to date items, The server freezes for 2-10 SECONDS, then the grid shows the items. There was no noticable lag in the older version of refinedstorage.

I was using ftb hermitpack with a couple of mods upgraded/added. (For a full list of changed mods, please refer to [this pastebin](http://pastebin.com/CvSQ2qqy) )

I have a midtier storage system with:
~60 crafters for crafting with recipies (I have to admit that many of them have ore dictionary, I was not aware of the performance consequences when I made them)
~20 crafters for machines
~20 external storage deep storage units
-3 disk drives
-The system is split over 2 remote locations in the same dimensions

The lag does not occur with fluid grids.
**I want to stress that I did not experience any lag in version 1.2.16 when opening the grid.**

I took some profiles of the lag:
[https://transfer.sh/EmO8n/refinedstorage.nps](https://transfer.sh/EmO8n/refinedstorage.nps)
I started recording, opened the crafting grid once, used /forge tps a couple times to see if the lag was gone, stopped recording

[https://transfer.sh/ZWqzQ/refinedstorage.nps](https://transfer.sh/ZWqzQ/refinedstorage.nps)
I started profiling, opened the crafting grid twice, used /forge tps once and stopped recording

#### Version:

- Minecraft: 1.10.2
- Forge: 12.18.3.285
- Refined Storage: 1.2.24

Does this issue occur on a server? yes

**Comment by rYanGap** [comment] 2017-03-20 21:42
I have the same issue. This was not a problem with the same exact setup in earlier versions of Refined Storage. Here's a video demonstrating the problem: https://www.youtube.com/watch?v=VUnEgZCzfTg

**Comment by raoulvdberge** [comment] 2017-03-22 12:27
This is a duplicate of #1041, it is linked to that issue so I will check out your NPS files as well still.

**Closed by raoulvdberge** 2017-03-22 12:27 UTC
Labels: investigate, performance
