### ISSUE TITLE
Ticking Block Entity Tile Controller - Server Loop Crash

### ISSUE THREAD

**Issue by timeherald** [raoulvdberge/refinedstorage#2260] opened 2019-06-11 19:20 UTC
#### Issue description:
Server stuck in a crash loop
#### What happens:
Refined Storage tile controller causing a ticking block entity
#### What you expected to happen:
No crash
#### Steps to reproduce:
1. 64k storage was added to disk drive
2. Server crashed
3. Stuck in crash loop
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: forge-14.23.5.2838
- Refined Storage: 1.6.14

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

https://paste.dimdev.org/carayipupu.mccrash

**Comment by Darkere** [comment] 2019-06-11 20:25
Duplicate of #2241

**Closed** 2019-06-12 10:45 UTC
