### ISSUE TITLE
Breaking a full Disk Drive only drops the Drive, no disks are dropped.

### ISSUE THREAD

**Issue by tolly7654** [raoulvdberge/refinedstorage#1171] opened 2017-04-16 17:54 UTC
#### Steps to reproduce:
1. Get an RS system (specifics don't matter, as long as it has a Drive, some disks, the controller and a way of putting items into the disks).

2. Break the drive block (creative/survival, tool/bare fist, it doesn't matter)
 
3. Observe the damage. 
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2 
- Forge: 8.0.99.99 (Latest Recommended version in FTB Beyond)
- Refined Storage: 1.2.25 (Latest Recommended version in FTB Beyond)

Does this issue occur on a server? [yes/no] Yes

**Comment by tolly7654** [comment] 2017-04-21 19:04
We've scanned through the logs ourselves, but nothing has actually come up in them.

**Comment by ktole1999** [comment] 2017-04-21 19:06
@tolly7654 he meant post your log so he can look.

**Comment by tolly7654** [comment] 2017-04-21 19:07
I'll see if I can provide a log then, but no promises on it coming in the next ten minutes. Internet isn't the greatest for me atm

**Comment by raoulvdberge** [comment] 2017-04-21 19:08
I'd like to scan the log myself, please only send a single relevant one.

**Comment by raoulvdberge** [comment] 2017-04-21 19:08
Or perhaps even better, send a recent log (so we're sure it's the right log) when you break a disk drive.

**Comment by tolly7654** [comment] 2017-04-21 19:10
Gonna see if I can do that then @raoulvdberge. Again, my internet isn't the greatest so I apologise if it takes a little while

**Comment by raoulvdberge** [comment] 2017-04-21 19:17
No problem, I'll take a look as soon as you upload it. No hurry.

**Comment by KasperFranz** [comment] 2017-04-21 19:19
There is not generating any exceptions or anything there can show what the issues is when the item is broken.

If it is any help we are running sponge

**Comment by raoulvdberge** [comment] 2017-04-21 19:20
Seems like a typical Sponge issue to me.

**Comment by KasperFranz** [comment] 2017-04-21 19:28
Well it might be a sponge issue, but the problem doesn't happen with enderIO or any of the other mods where this behavior is expected

**Comment by ktole1999** [comment] 2017-04-21 19:33
@raoulvdberge typical sponge issue? please explain.

**Comment by raoulvdberge** [comment] 2017-04-21 19:40
Sponge does things differently than Forge in some cases. In case of fragile code like TE inventory contents dropping (which relies on order of execution), I can see it doing something incompatible than what Forge mods rely on.

**Comment by ktole1999** [comment] 2017-04-21 19:48
thanks for the info. i have seen reports where items do not drop properly because of sponge.

**Comment by raoulvdberge** [comment] 2017-04-21 19:51
RS also does some extra work before the block is broken, like saving disk data before dropping, which might also cause issues.

**Comment by raoulvdberge** [comment] 2017-04-23 12:07
I'm going to close this, as I can't reproduce this.

Reasons could be:
- Sponge compatibility
- External mod causes the drops to not be dropped

**Closed by raoulvdberge** 2017-04-23 12:07 UTC
Labels: awaiting, bug, can't reproduce
