### ISSUE TITLE
[1.12] Crash when opening crafting grid

### ISSUE THREAD

**Issue by Ash70** [raoulvdberge/refinedstorage#1412] opened 2017-08-09 10:40 UTC
#### Issue description:
It does not happen always. But when I open the crafting grid, there are no buttons on the left side (sorting, redstone, grid size etc.) the game hangs for a second and then it shuts down internal server and goes to desktop.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 2443
- Refined Storage: 1.5.14

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/8PPGcC37

**Comment by raoulvdberge** [comment] 2017-08-09 10:58
Duplicate of #1410, a bug which I fixed today.

**Comment by Ash70** [comment] 2017-08-10 10:54
I updated to 1.5.16 but it still happens. I also noticed now that my regular inventory shows as empty when opening the grid just before it crashes.

https://pastebin.com/AqSdnAAx

**Comment by Knito58** [comment] 2017-08-11 08:21
Same here withe refinedstorage-1.5.16.jar.
NPE when updating screen events.
https://www.dropbox.com/s/0pnoerwf7gova5h/crash-2017-08-11_10.15.52-client.txt?dl=1

**Comment by winsrp** [comment] 2017-08-16 17:24
same here on 1.5.16, opening crafting grid, inventory looks empty just before crashing

https://pastebin.com/QA3tcBZc

**Comment by raoulvdberge** [comment] 2017-08-16 21:16
Thanks for the crashreports guys, that crash is for issue #1416.

I'll look into it tomorrow.

**Closed by raoulvdberge** 2017-08-16 21:16 UTC
Labels: bug
