### ISSUE TITLE
Refined Storage doesn't autocraft mekanism induction cells

### ISSUE THREAD

**Issue by MrLuxALot** [raoulvdberge/refinedstorage#2426] opened 2020-02-12 22:12 UTC
#### Issue description:
I want to make a autocrafting recipe for my induction cells, but the Crafting Manager says that i am missing the energy cubes. Even if i have the amount to make all induction cells it still says the same.
#### What happens:
I try to autocraft induction cells. Crafting Manager says i dont have any Energy Cubes
#### What you expected to happen:
I successfully autocraft the cells 
#### Steps to reproduce:
1.Make the Energy Cube recipe
2.Make a Induction Cell recipe
3.Try to autocraft the Induction Cell

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: forge-14.23.5.2847
- Refined Storage: refinedstorage-1.6.15.jar

Does this issue occur on a server? [no]

**Comment by Darkere** [comment] 2020-02-12 22:16
Duplicate of #2334 , #2064 

Make the recipe by hand and disable oredict to make it work.

**Closed** 2020-02-12 22:56 UTC
Labels: Autocrafting, Bug, Duplicate
