### ISSUE TITLE
Multipe Crafters

### ISSUE THREAD

**Issue by Sayomie** [raoulvdberge/refinedstorage#874] opened 2017-01-16 03:28 UTC
#### Issue description: 
RS network only using one machine for auto crafting when multiple machines have the same pattern.

 I have two solderers working both with the same patterns and when I told the system to produce 3 64k storage discs it only utilized one of the solderers and never used the second.

#### What happens: 
It is only using one machine

#### What you expected to happen: 
It to use multiple machines

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:
- Refined Storage:
- Sky Factory 3 Latest Update

Does this issue occur on a server? [yes/no] Yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment] 2017-01-16 10:24
Implemented in 1.11 (aedaa0740765ef09eab10aab9a6b1a390fd77596), duplicate of #704. Might get backported at some point.

**Closed by way2muchnoise** 2017-01-16 10:24 UTC

**Comment by bghyt** [comment] 2018-03-27 17:21
@way2muchnoise please back port it, i cannot find a fix to craft loads of processors in 1.10, it's currently the only thing limiting me from moving on (crafting x64 64K drives) but using only 1 solderer it took 3-4 hours to make just 16 of the 64k drives please fix this
