### ISSUE TITLE
Feature Request - Increase Detector quantity entry field as display truncates numbers >1k

### ISSUE THREAD

**Issue by KodiakJak** [raoulvdberge/refinedstorage#911] opened 2017-01-24 01:42 UTC
#### Steps to reproduce:
1. Place Detector
2. Enter quantity >1000
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2215
- Refined Storage: 1.2.17

Does this issue occur on a server? [yes/no] Yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment] 2017-01-24 09:24
Literally a duplicate of #910

**Closed by raoulvdberge** 2017-01-24 09:24 UTC
