### ISSUE TITLE
Server Crash when player near area

### ISSUE THREAD

**Issue by VallenFrostweaver** [raoulvdberge/refinedstorage#2080] opened 2018-11-08 15:19 UTC
#### Issue description:
When a specific player's base is loaded on the StoneBlock modpack the player is kicked and the server assumes a crash and shuts down.
#### What happens:
same as above
#### What you expected to happen:
no crash
#### Steps to reproduce:
Unknown. It would appear to be a corrupt autocrafting function but the players couldn't remember anything and the the locations of said issue were not in the crash logs.
#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2768-universal.jar
- Refined Storage: 1.6.8 (& addons 0.4.2)
- StoneBlock modpack version: 1.0.25
#### Does this issue occur on a server?
Yes
#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/bBZZmcg7

**Comment by raoulvdberge** [comment] 2018-11-08 15:28
This is a watchdog crash, which may or may not be an RS problem. Can you reproduce this without RS?

**Comment by raoulvdberge** [comment] 2018-11-09 13:45
Okay, then I'll have to close this since there's not anything more I can do.

**Closed by raoulvdberge** 2018-11-09 13:45 UTC

**Comment by VallenFrostweaver** [comment] 2018-11-16 12:19
@raoulvdberge This has happened again on another pack (World of Dragons) not long after the creation of a max size auto crafting setup that was chunk loaded. I can provide crash logs for that too if it'll help.
